### ISSUE TITLE
Disconnect doesn't close the connection

### ISSUE THREAD

**Issue by cfrost** [vmware/pyvmomi-community-samples#118]
Disconnecting the Service Instance only logs out of the instance and not disconnecting the connection. This leaves the socket open and causes a problem if the python session doesn't terminate by exceeding the open socket limit.

**Comment by hartsock** [comment]
I'm re-starting work on this 29Jan2015.

**Comment by nlamirault** [comment]
hi,
any news ib this bug ?

**Comment by hartsock** [comment]
I'm carving out some time to work on it over the next 2 weeks. We know what we need to do. I just need time to do it in.

**Comment by hartsock** [comment]
See bug: https://github.com/vmware/pyvmomi/issues/194
