### ISSUE TITLE
[Question] Getting list of vms from vswitch

### ISSUE THREAD

**Issue by ghost** [vmware/pyvmomi-community-samples#138]
Guys,

I'm trying to get the association between a standard vswitch and a virtual machine through pyvmomi.

From the vsphere client, click the appropriate vhost->Manage->Networking. Then click the vswitch and you get a list of VMs by network. I want that list.

When I try to get this from pyvmomi I can't seem to find the right data. I can get the vswitch for a physical nic through the host list, but looking for something similar through the VM list. (ie. given a VM what vswitch is it associated with, or given a vswitch, what VMs are associated)

From the following code I get close, 'network1' I got through my VM (see below), I know its on 'VM Network'.
'pg1' I got from a vswitch (via host) it returns a portgroup key with the 'VM Network' label tagged on.
So it feels like I'm close, but not close enough. 

------output
Plexxi>>> network1.name
'VM Network'
Plexxi>>> pg1
u'key-vim.host.PortGroup-VM Network'

------code (Vconnector call removed)
from pyVim.connect import SmartConnect, Disconnect
import pyVmomi
from vconnector.core import VConnector
vconn = VConnector(host="host", pwd="pwd?", user="user")
vconn.connect()
hosts = vconn.get_host_view()
sets = ['name', 'hardware.systemInfo.uuid','config.network.dnsConfig.address', 'config.network.vnic','config.network.pnic','config.network.portgroup','network', 'config.network.vswitch']
hostlist = vconn.collect_properties(view_ref=hosts,obj_type=pyVmomi.vim.HostSystem,path_set=sets)
host1 = hostlist[0]
vswitch = host1['config.network.vswitch']
vswitch1 = vswitch[0]
pg1 = vswitch1.portgroup[0]
sets = ['name', 'config.hardware.device', 'network']
vmlist = vconn.collect_properties(view_ref=vms,obj_type=pyVmomi.vim.VirtualMachine,path_set=sets)
vm1 = vmlist[0]
networks = vm1['network']
network1 = networks[0]
network1.name
pg1

any ideas?

**Comment by hemskgren** [comment]
Is it possible to have vlan id aswell?
That would help alot when planing to remove a vlan in the switch infra and the pg aswell.
