### ISSUE TITLE
Error while importing vim

### ISSUE THREAD

**Issue by Jain123** [vmware/pyvmomi-community-samples#142]
I am using pyVmomi5.5.0 with python 2.7
When I am using "from pyVmomi import vim" and "from pyVmomi import vmodl", it's showing error message.

But when I am writing the same import line in command prompt, it's working.

Can you please help me to find the rectify the issue.

Thanks.

**Comment by karthi81** [comment]
vim is not working via script but its working in CLI.

RHEL 7
Python 3.7.4

>>> from pyVmomi import vim
>>> vimype = vim.VirtualMachine
>>> conn._get_obj(vimype, 'test-001')
<class 'pyVmomi.VmomiSupport.vim.Datacenter'>
'vim.VirtualMachine:vm-731'
>>>

but same thing did not work in script. Any help will be apprecaited.
