### ISSUE TITLE
virtual_machine_device_info.py error: unicode problem (utf-8)

### ISSUE THREAD

**Issue by phlo-c** [vmware/pyvmomi-community-samples#150]
Traceback (most recent call last):
  File "virtual_machine_device_info.py", line 255, in <module>
    print("    {0:{width}{base}}: {1}".format(name.encode('utf-8'), value, width=15, base='s'))
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe4' in position 8: ordinal not in range(128)

**Comment by hartsock** [comment]
*that* is interesting... can you do something like [this](https://github.com/vmware/pyvmomi-community-samples/blob/master/samples/hello_world_vcenter_with_yaml_recorder.py) and share the recording via gist or pastebin? Be *sure* to *remove* any sensitive **passwords** or other data before posting! Or you can share with me directly via email.

**Comment by michaelrice** [comment]
What about adding this to the top of the file?

    # coding=utf-8
