### ISSUE TITLE
help in retrieving human readable vmfolder name and cycling through them

### ISSUE THREAD

**Issue by dariusjs** [vmware/pyvmomi-community-samples#152]
Hi,

I'm trying to hack my way through the getallvms.py example script to document the whole vcenter environment I have. The vcenter environment I am working on is sorted into folders where we have production, QA, dev and in each environment there are further subfolders based on applications and roles. I am working towards trying to print off each specific folder name and then print the child vms contained in each folder. 

Looking at the docs https://www.vmware.com/support/developer/vc-sdk/visdk41pubs/ApiReference/vim.Folder.html I cant seem to find the function I need to call if I want the vmfolder name in vsphere, I only get the folder ID which shows as format vim.Folder:group-v22

In my bcase pyvmomi seems to reference this to the root folder vim.datacenter.vmFolder. I havent gotten to the part year where I can print all the folder names themselves. Perhaps someone has been through a similar excercise before. The powercli equivalent for what I am searching seems to be the 'get-foider' cmdlet which can loop through and print the vms contained in them. Any pointers would be greatly appreciated.

**Comment by hartsock** [comment]
Hey there... so this is pretty simple. It's not a function, it's a property from the parent object. You use the `.name` property to access the name. It comes from the deepest [base type](https://www.vmware.com/support/developer/vc-sdk/visdk41pubs/ApiReference/vim.CustomFieldsManager.FieldDef.html#managedObjectType) of the object hierarchy. I can understand why you didn't see it right away.

So, in the place where you printed your folder... just put `my_folder.name` and that should work.
