### ISSUE TITLE
Create VM Inside a specific VM directory 

### ISSUE THREAD

**Issue by bigmyx** [vmware/pyvmomi-community-samples#154]
Can anyone provide an example of creating a VM inside a specific VM directory?
(Sorry if it sounds dumb)

**Comment by michaelrice** [comment]
@bigmyx What part of [this sample] (https://github.com/vmware/pyvmomi-community-samples/blob/master/samples/create_random_marvel_vms.py) could I help you understand better so that would answer your question?

**Comment by bigmyx** [comment]
Assuming I have "vmfolder = datacenter.vmFolder" and "hosts = datacenter.hostFolder.childEntity", how can I "tell" it to look at the specific VM folder (for which only I have a permissions) ?
thanks !

**Comment by michaelrice** [comment]
@bigmyx You will have to find that folder if you dont know where its at already. If you have a lot of folders what I suggest is a property collector to pull all the folders and the permission on them with the principal (this property will contain the username of who has access to it)

```python
from pyVim import connect

si = connect.SmartConnect(host=host, user=user, pwd=password)
root = si.content.rootFolder
root.permission
(vim.AuthorizationManager.Permission) [
   (vim.AuthorizationManager.Permission) {
      dynamicType = <unset>,
      dynamicProperty = (vmodl.DynamicProperty) [],
      entity = 'vim.Folder:group-d1',
      principal = 'VSPHERE.LOCAL\\Administrator',
      group = false,
      roleId = -1,
      propagate = true
   },
   (vim.AuthorizationManager.Permission) {
      dynamicType = <unset>,
      dynamicProperty = (vmodl.DynamicProperty) [],
      entity = 'vim.Folder:group-d1',
      principal = 'root',
      group = false,
      roleId = -1,
      propagate = true
   }
]
```

Once you find your username in the principal field of a folder then you can use that folder object as the folder for the create vm task.

This is easier if you know where in your inventory the folder you want to use is at. For example if you know of another VM in that folder you can find that vm by name or even better instance uuid then do a vm.parent and you will find its folder.

**Comment by bigmyx** [comment]
@michaelrice , thanks for detailed explanation !
I don't seem to have a permission to call root.permission method.
Given the fact I know the folder name, what will be the bare minimum code to create a VM inside it?
thanks again !
