### ISSUE TITLE
project gh-pages are getting 404

### ISSUE THREAD

**Issue by bobfraser1** [vmware/pyvmomi-community-samples#163]
http://vmware.github.io/pyvmomi-community-samples/ is returning 404.

**Comment by michaelrice** [comment]
Im pretty sure its related to the new vmware.github.io site that was created.

**Comment by michaelrice** [comment]
Yeah I think they may need to use the master branch when using that repo name.. The way there is a gh-pages and a master I think they broken any other pages for other repos below it..

**Comment by hartsock** [comment]
@michaelrice yep. I agree with that assessment.

**Comment by michaelrice** [comment]
I opened a bug here: https://github.com/vmware/vmware.github.io/issues/1

**Comment by michaelrice** [comment]
I wonder if its not though.. the photon gh-pages seems to be working fine.. strange.

**Comment by hartsock** [comment]
@michaelrice I see nothing in documentation that directly explains why these pages were removed from publication. We're working the problem now. @bobfraser1 is taking point at the moment.

**Comment by hartsock** [comment]
@bobfraser1 & @michaelrice  I'm seeing the pages at http://vmware.github.io/pyvmomi-community-samples/ but I don't see any intervention on our end.

**Comment by michaelrice** [comment]
Im seeing them now too..

**Comment by michaelrice** [comment]
Glitch in the Matrix?

**Comment by bobfraser1** [comment]
I'm seeing the pages too. I think we can close this.
