### ISSUE TITLE
hello_world_vcenter.py throws an ValerError

### ISSUE THREAD

**Issue by georgepatterson** [vmware/pyvmomi-community-samples#192]
Note sure if this is a bus or not but I tried running the hello_world_vcenter.py script and received an error. Output was as follows: (ip address obfuscated)

```
./hello_world_vcenter.py -s 192.168.x.y -u root
Enter password for host 192.168.99.10 and user root:

Hello World!

If you got here, you authenticted into vCenter.
Traceback (most recent call last):
  File "./hello_world_vcenter.py", line 104, in <module>
    main()
  File "./hello_world_vcenter.py", line 85, in main
    print "The server is {}!".format(args.host)
ValueError: zero length field name in format`
```

Let me the best way to attach a diff file and whether it would be unified or not. This is a two line change. Just spotted a typo for the word authenticated.

**Comment by michaelrice** [comment]
Hello @georgepatterson 

Im just curious. Are you using python 2.6.x? I can see how it would be failing for you if so..

**Comment by georgepatterson** [comment]
Yes, Python 2.6.6  on Centos 6

**Comment by michaelrice** [comment]
That sample uses new style formatting.

On python 2.6 you would need to use 

```python
print "The server is {0}!".format(args.host)
```
To work.
