### ISSUE TITLE
Sample: Add new disk where the controller doesn't exist on the VM (yet)

### ISSUE THREAD

**Issue by exolain** [vmware/pyvmomi-community-samples#203]
Basically what the title said, I saw that there is a sample to add a new disk but the VM that I have created does not have the VirtualDisk controller in order to add it. So one needs to be created.
Can we have that added to the existing sample?

Just to add to disk I tried different solutions but I'm getting this error "Caught vmodl fault : The device '0' is referring to a nonexisting controller '1,000'."
I'm using this:

cdspec.device.controllerKey = 1000

I was thinking that there should be a way to create (I found a way to do it but it was with psphere)
I read somewhere that the key 1000 is the VirtualHardDisk key

Thanks :smile:

**Comment by exolain** [comment]
I was able to figure out how to add the controller:

```python
def add_controller(vm):
    vm.ReconfigVM_Task(
        spec=vim.vm.ConfigSpec(
            deviceChange=[
                vim.vm.device.VirtualDeviceSpec(
                    operation=vim.vm.device.VirtualDeviceSpec.Operation.add,
                    device=vim.vm.device.VirtualLsiLogicSASController(
                        sharedBus=vim.vm.device.VirtualSCSIController.Sharing.noSharing
                    ),
                )
            ]
        )
    )
```

**Comment by Youw** [comment]
Unfortunately this solution doesn't allow to add more than one SCSI controllers, i.e., if I need to connect more that 15 hard drives to VM (need specify ).
When I try to add more VirtualLsiLogicSASController - it successfully does nothing =(

Any workaround for my case?

**Comment by bishopbm1** [comment]
I am not sure if anyone has solved this yet but the way to add more then one SCSI controller is to specify the bus number. The bus number defaults to 0 which if you have a controller attached already should have bus 0 by default.

`def add_controller(vm):
    vm.ReconfigVM_Task(
        spec=vim.vm.ConfigSpec(
            deviceChange=[
                vim.vm.device.VirtualDeviceSpec(
                    operation=vim.vm.device.VirtualDeviceSpec.Operation.add,
                    device=vim.vm.device.VirtualLsiLogicSASController(
                        sharedBus=vim.vm.device.VirtualSCSIController.Sharing.noSharing,
                        busNumber = 1
                    ),
                )
            ]
        )
    )`

**Comment by craynic** [comment]
I want to add a new SCSI controller with one existing, and get error something like "cannot modify existing SCSI device scsi0". I'm sure I'm using different busNumber and operation=add. Seems vSphere thinks I'm modifying the existing SCSI controller.

    vim.vm.device.VirtualDeviceSpec(
        operation=vim.vm.device.VirtualDeviceSpec.Operation.add,
        device=vim.vm.device.VirtualLsiLogicSASController(
            key=1001,
            sharedBus=vim.vm.device.VirtualSCSIController.Sharing.noSharing,
            slotInfo=vim.vm.device.VirtualDevice.PciBusSlotInfo(pciSlotNumber=161),
            controllerKey=100,
            busNumber=2,
        ),
    )

**Comment by uddyan92** [comment]
@prziborowski 
waitfortasks(vm.ReconfigVM_Task(
        spec=vim.vm.ConfigSpec(
            deviceChange=[
                vim.vm.device.VirtualDeviceSpec()) ...This is recommened practise right 
adding wairfortasks is a must?? else it might give an error "Another task is already in progress"
if for some reason the task just hung up.?

**Comment by prziborowski** [comment]
@uddyan92 waiting for the task would be a good idea so that you know if it succeeded or failed (and reason for failure). Also if you want to perform another operation on the object, then you would have to serialize your code otherwise as you state you might get a TaskInProgress fault for the subsequent operation.
pyVim.task has a WaitForTask method you can use.

Also if you want to add a controller and disk in the same operation, for the disk's controllerKey, you would specify the key for the controller you are adding.
Typically it is recommended to use negative numbers for adding new devices so that they can't conflict with existing devices (which are always positive).
So you might have:
controller.key = -1
disk.controllerKey = -1
disk.key = -2
