### ISSUE TITLE
Sample Request: How can I get hosts' vim.HostSystem instance when connected to vCenter

### ISSUE THREAD

**Issue by Jianbo-Gao** [vmware/pyvmomi-community-samples#208]
For method of vim.DiagnosticManager:
QueryDescriptions(host)'s Args:
host (vim.HostSystem, optional):
Specifies the host. If not specified, then it defaults to the server itself. For example, if called on VirtualCenter, then the value defaults to VirtualCenter logs. When called on an ESX server host, the host should not be specified.

How can I get the vim.HostSystem instance? When I connect to a host, how can I know whether it is vCenter or ESX?

I get confused when reading the docs and programmer guide. I can get ESX's logs easily when I connect to ESX directly, but cannot get it when I connect to vCenter.
Thanks!

**Comment by GarfyPKU** [comment]
I have already connected to the hosts using view. But I still cannot distinguish vCenter and ESX... They seem the same when I connect them using Smartconnect.

**Comment by pathcl** [comment]
@GarfyPKU you might want to look at this https://github.com/pathcl/pyvmomi-community-samples/blob/get_datacenter/samples/get_datacenter.py

**Comment by jeffhu** [comment]
When you connect to a ServiceInstance, you can figure out if you are connected to vCenter or ESXi by accessing the [AboutInfo] (http://pubs.vmware.com/vsphere-60/index.jsp?topic=%2Fcom.vmware.wssdk.apiref.doc%2Fvim.AboutInfo.html). 

For example,

    # Getting AboutInfo from vCenter host
    >>> si_vc = pyVim.connect.SmartConnect(host="10.20.124.80", user="administrator@vsphere.local", pwd=vc_password)
    >>> si_vc.content.about
    (vim.AboutInfo) {
       dynamicType = <unset>,
       dynamicProperty = (vmodl.DynamicProperty) [],
       name = 'VMware vCenter Server',
       fullName = 'VMware vCenter Server 6.0.0 build-2656761',
       vendor = 'VMware, Inc.',
       version = '6.0.0',
       build = '2656761',
       localeVersion = 'INTL',
       localeBuild = '000',
       osType = 'linux-x64',
       productLineId = 'vpx',
       apiType = 'VirtualCenter',
       apiVersion = '6.0',
       instanceUuid = '0b1b10bb-c1ce-4cad-af0f-0e38d54b50a7',
       licenseProductName = 'VMware VirtualCenter Server',
       licenseProductVersion = '6.0'
    }
    >>>
    
    # Getting AboutInfo from ESXi host
    >>> si_esx = pyVim.connect.SmartConnect(host="10.20.125.245", user="root", pwd=esx_password)
    >>> si_esx.content.about
    (vim.AboutInfo) {
       dynamicType = <unset>,
       dynamicProperty = (vmodl.DynamicProperty) [],
       name = 'VMware ESXi',
       fullName = 'VMware ESXi 6.0.0 build-2715440',
       vendor = 'VMware, Inc.',
       version = '6.0.0',
       build = '2715440',
       localeVersion = 'INTL',
       localeBuild = '000',
       osType = 'vmnix-x86',
       productLineId = 'embeddedEsx',
       apiType = 'HostAgent',
       apiVersion = '6.0',
       instanceUuid = <unset>,
       licenseProductName = 'VMware ESX Server',
       licenseProductVersion = '6.0'
    }
    >>> 

If you are connected to ESXi host, there will only be 1 HostSystem object.  If connected to vCenter, you will have zero or more HostSystem objects.  get_datacenter.py shows how to enumerate the HostSystem in both cases.
