### ISSUE TITLE
How to delete a disk from a vm

### ISSUE THREAD

**Issue by psinghsp** [vmware/pyvmomi-community-samples#216]
Hi

I looked at the sample to add a disk to a vm. I want to do opposite. Does anyone have a sample for that? I tried modifying the "add sample" by changing the operation to "remove" and setting the unitNumber in the diskSpec to delete the one I want - but I keep getting errors.

**Comment by PradeepJigalur** [comment]
i used the following

hdd_prefix_label= 'Hard disk '
hdd_label = hdd_prefix_label + str(15)
virtual_hdd_device = None
for dev in vm_obj.config.hardware.device:
    if isinstance(dev, vim.vm.device.VirtualDisk) and dev.deviceInfo.label == hdd_label:
        virtual_hdd_device = dev


virtual_hdd_spec = vim.vm.device.VirtualDeviceSpec()
virtual_hdd_spec.operation = vim.vm.device.VirtualDeviceSpec.Operation.remove
virtual_hdd_spec.device = virtual_hdd_device

spec = vim.vm.ConfigSpec()
spec.deviceChange = [virtual_hdd_spec]
task = vm_obj.ReconfigVM_Task(spec=spec)
