### ISSUE TITLE
How to get multiple IP addresses for multiple NICs of a VM

### ISSUE THREAD

**Issue by psinghsp** [vmware/pyvmomi-community-samples#218]
I see that I can get a single IP address associate with a VM using:

vm.summary.guest.ipAddress where vm is the vim.VirtualMachine object.

But in my case, I have three NICs and there are three IP addresses. This object returns random IP address of the three (after every reboot of the vm).

Is there a way to get all three IP addresses?

**Comment by lemke1458** [comment]
Look for ipConfig in the NicInfo.  It should contain the complete list of IPs.  Note that I'm using the VMODL names, and pyvmomi may adjust these, but it should be at the same layer as the simple ipAddress.

**Comment by munib07** [comment]
I do't see any such config object [i.e. ipConfig] inside vm.summary or vm.config. I can see IpAddress at vm.summary.guest.ipAddress, and  MAC address at vm.config.hardware.device. If there are 2 NIC , there will 2 entries for device object. Each one will have its own device.macAddress and device.deviceInfo.summary, which tells the name of the network. If the network name is standard defined for IP [example: local, public etc], then you can link with it to IP. This is the closest I am able to figure out. Please let me know if you got something better to figure out MAC to IpAddress mapping !!

vm_hardware = vm.config.hardware
    for each_vm_hardware in vm_hardware.device:
        if (each_vm_hardware.key >= 4000) and (each_vm_hardware.key < 5000):
            print ('{} | {} | {}'.format(each_vm_hardware.deviceInfo.label,
                                                each_vm_hardware.deviceInfo.summary,
                                                each_vm_hardware.macAddress))

**Comment by lemke1458** [comment]
I'm not sure how pyVmomi names it, I'm looking at the vSphere API.

See https://www.vmware.com/support/developer/converter-sdk/conv60_apireference/vim.vm.GuestInfo.NicInfo.html

**Comment by tatref** [comment]
Here is my solution:

```
for nic in my_vm.guest.net:
        addresses = nic.ipConfig.ipAddress

        print(macAddress)
        for adr in addresses:
                print(adr.ipAddress)
                print(adr.prefixLength)
```

**Comment by redmine-cosi** [comment]
Well,
thanks :)

**Comment by szajac01** [comment]
Hi @kumahesh @tatref 
 given solution is not always ok.
I got some examples : The vm has multiples nics, with several ips.
vm.guest.net contains all nics, but just the first one has name and an ipAddress,
the other one are None

`for nic in vm.guest.net:
                        logger.debug(f"[{nic.connected},{nic.network},{nic.deviceConfigId}]")`

returns
[True,myNetworkName,4000]
[True,None,-1]
[True,None,-1]
[True,None,-1]
[True,None,-1]
[True,None,-1]

can you explain that ?
Vm has several nics, all connected and several ip addresses
first item can show only one ip in nic.ipConfig.ipAddress

**Comment by tatref** [comment]
Did you try my code? It should list every IP for every NIC

**Comment by szajac01** [comment]
Yes It is...

**Comment by tatref** [comment]
What OS are you running?

Can you provide the output  of `ip l` and `ip a`?

**Comment by szajac01** [comment]
I do not have access on the vm which is à firewall appliance
