### ISSUE TITLE
Anyone have a sample script to simply create a new folder in datacenter?

### ISSUE THREAD

**Issue by 3pr0mpt** [vmware/pyvmomi-community-samples#222]
Hello,

I'm facing a strange issue. Maybe I'm doing it wrong, but I'm trying to create a folder into a DC if the folder is not found in a first place:

```
    vm_folder = "shuttle"
    dc = content.rootFolder.childEntity[0]
    test_folder = get_obj(content, [vim.Folder], vm_folder)
    if test_folder is None:
        print "here:", test_folder
        vim.FileManager.MakeDirectory(name=vm_folder, datacenter=datacenter_name, createParentDirectories=True)

```

I don't understand why I'm having the following error:

```
  File "/usr/local/lib/python2.7/dist-packages/pyVmomi/VmomiSupport.py", line 560, in __call__
    return self.f(*args, **kwargs)
TypeError: _InvokeMethod() takes at least 2 arguments (1 given)
```

As per the [documentation](https://github.com/vmware/pyvmomi/blob/e26718fef6d9dbc8a4da1761b75d9da58bbc0daa/docs/vim/FileManager.rst) I'm providing 3 arguments (one mandatory and two optional), but the python error tells me I'm only providing 1.
I've been looking around, and there is no example of how use this feature.

Many thanks in advance for your help.

**Comment by chinmayb** [comment]
i'll soon upload an example to create folders under a desired datacenter.

**Comment by RenoRainz** [comment]
Hi,

I have a issue too with this function, it seems there is a problem with parsing argument.
I have the following code : 
```python
  ..         
  print type(datacenter)
  file_manager.MakeDirectory("[datastore1]/myvm/", datacenter)
  ...
```

Here the error and ouput : 

```
<class 'pyVmomi.VmomiSupport.vim.Datacenter'>

File "myapp/vmware/vim.py", line 109, in manage_volumes
    file_manager.MakeDirectory("[datastore1]/myvm/", datacenter)
  File "/myapp/.venv/fabenv/lib/python2.7/site-packages/pyVmomi/VmomiSupport.py", line 560, in __call__
    return self.f(*args, **kwargs)
  File "/myapp/.venv/fabenv/lib/python2.7/site-packages/pyVmomi/VmomiSupport.py", line 374, in _InvokeMethod
    map(CheckField, info.params, args)
  File "/myapp/.venv/fabenv/lib/python2.7/site-packages/pyVmomi/VmomiSupport.py", line 949, in CheckField
    % (info.name, info.type.__name__, valType.__name__))
TypeError: For "name" expected type str, but got vim.Datacenter

Fatal error: One or more hosts failed while executing task 'process_run_vmware_item'

Underlying exception:
    For "name" expected type str, but got vim.Datacenter

Aborting.
1 failure(s) out of 0.
```

Do you have any ideas ?

**Comment by 3pr0mpt** [comment]
Thanks to @chinmayb  a new pull have been done on github (https://github.com/vmware/pyvmomi-community-samples/pull/223).  This pull is perfect for creating physical folders. The problem is I need to create logical folders. 
From @chinmayb example, it enables physical folders as shown bellow:
![physical folders](http://imagizer.imageshack.us/a/img910/9958/A2ruB5.png)


The challenge is to create logical folders:
![logical folders](http://imagizer.imageshack.us/a/img903/8461/i7EBU0.png)

I believe, the way to achieve that is using vim.FileManager.MakeDirectory function. 

Kind regards.

**Comment by chinmayb** [comment]
@3pr0mpt :  As per that doc, 
"This managed object type provides a way to manage and manipulate files and folders on datastores" if you use "vim.FileManager", the folders will be created on to the datastore,
something like this 

content.fileManager.MakeDirectory("[datastore1]/foldername", dc_obj, createParentDirectories=True)

**Comment by chinmayb** [comment]
@3pr0mpt you want VM folders, Will update my patch.
