### ISSUE TITLE
Add a new NIC to VM is getting "Invalid operation on device '0'" error

### ISSUE THREAD

**Issue by jkhine** [vmware/pyvmomi-community-samples#226]
Using most of syntax from - https://github.com/vmware/pyvmomi-community-samples/blob/master/samples/add_disk_to_vm.py

``` python
spec = vim.vm.ConfigSpec()
nic_changes = []

nic_spec = vim.vm.device.VirtualDeviceSpec()
nic_spec.fileOperation = "create"
nic_spec.operation = vim.vm.device.VirtualDeviceSpec.Operation.add


nic_spec.device = vim.vm.device.VirtualE1000()
nic_spec.device.key = 4009

nic_spec.device.deviceInfo = vim.Description()
nic_spec.device.deviceInfo.label = 'Network adapter 10'
nic_spec.device.deviceInfo.summary = 'Internal-Net1'

nic_spec.device.backing = vim.vm.device.VirtualEthernetCard.NetworkBackingInfo()
nic_spec.device.backing.useAutoDetect = False
nic_spec.device.backing.network = get_obj(content, [vim.Network], 'Internal-Net1')
nic_spec.device.backing.deviceName = 'Internal-Net1'

nic_spec.device.connectable = vim.vm.device.VirtualDevice.ConnectInfo()
nic_spec.device.connectable.startConnected = true
nic_spec.device.connectable.startConnected = True
nic_spec.device.connectable.allowGuestControl = True
nic_spec.device.connectable.connected = False
nic_spec.device.connectable.status = 'untried'

nic_spec.device.unitNumber = 16
nic_spec.device.controllerKey = 100
nic_spec.device.wakeOnLanEnabled = True
nic_spec.device.addressType = 'assigned'


nic_changes.append(nic_spec)

spec.deviceChange = nic_changes
e = vm.ReconfigVM_Task(spec=spec)

print e.info
```

---

Output from e.info

```
(vim.TaskInfo) {
   dynamicType = <unset>,
   dynamicProperty = (vmodl.DynamicProperty) [],
   key = 'haTask-87-vim.VirtualMachine.reconfigure-2394681',
   task = 'vim.Task:haTask-87-vim.VirtualMachine.reconfigure-2394681',
   description = <unset>,
   name = vim.VirtualMachine.Reconfigure,
   descriptionId = 'VirtualMachine.reconfigure',
   entity = 'vim.VirtualMachine:87',
   entityName = 'Leaf18',
   locked = (vim.ManagedEntity) [],
   state = 'error',
   cancelled = false,
   cancelable = false,
   error = (vim.fault.InvalidDeviceOperation) {
      dynamicType = <unset>,
      dynamicProperty = (vmodl.DynamicProperty) [],
      msg = "Invalid operation for device '0'.",
      faultCause = <unset>,
      faultMessage = (vmodl.LocalizableMessage) [],
      property = u'virtualDevice.backing',
      deviceIndex = 0,
      badOp = <unset>,
      badFileOp = 'destroy'
   },
   result = <unset>,
   progress = <unset>,
   reason = (vim.TaskReasonUser) {
      dynamicType = <unset>,
      dynamicProperty = (vmodl.DynamicProperty) [],
      userName = 'root'
   },
   queueTime = 2015-12-04T02:43:53.379751Z,
   startTime = 2015-12-04T02:43:53.38042Z,
   completeTime = 2015-12-04T02:43:53.406321Z,
   eventChainId = 2394681,
   changeTag = <unset>,
   parentTaskKey = <unset>,
   rootTaskKey = <unset>
}
```

**Comment by jm66** [comment]
@jkhine did you solve it? Try not using device ```deviceInfo.label```, ```device.key```, ```device.unitNumber``` and ```device.controllerKey```

**Comment by defionscode** [comment]
I'm hitting this issue too

**Comment by defionscode** [comment]
I did omit the use of `deviceInfo.label`, `device.key` too and nada

**Comment by defionscode** [comment]
Ok figured it out, i had to omit `nic_spec.fileOperation = "create"`

and it worked

**Comment by bisanidhruv** [comment]
I am having the same problem. Already tried all the above fix, none work for me.

bellow is my code 
add_nic function

```
def add_nic(vm, si):
    spec = vim.vm.ConfigSpec()
    nic_changes = []

    nic_spec = vim.vm.device.VirtualDeviceSpec()
#    nic_spec.fileOperation = "create"
    nic_spec.operation = vim.vm.device.VirtualDeviceSpec.Operation.add

    nic_spec.device = vim.vm.device.VirtualE1000()
#    nic_spec.device.key = 4009

    nic_spec.device.deviceInfo = vim.Description()
#    nic_spec.device.deviceInfo.label = 'Network adapter 10'
    nic_spec.device.deviceInfo.summary = 'Internal-Net1'

    nic_spec.device.backing = vim.vm.device.VirtualEthernetCard.NetworkBackingInf$
    nic_spec.device.backing.useAutoDetect = False
    content = si.RetrieveContent()
    nic_spec.device.backing.network = get_obj(content, [vim.Network], 'Internal-N$
    nic_spec.device.backing.deviceName = 'Internal-Net1'

    nic_spec.device.connectable = vim.vm.device.VirtualDevice.ConnectInfo()
    nic_spec.device.connectable.startConnected = True
    nic_spec.device.connectable.startConnected = True
    nic_spec.device.connectable.allowGuestControl = True
    nic_spec.device.connectable.connected = False
    nic_spec.device.connectable.status = 'untried'
#    nic_spec.device.unitNumber = 16
#    nic_spec.device.controllerKey = 100
    nic_spec.device.wakeOnLanEnabled = True
    nic_spec.device.addressType = 'assigned'


    nic_changes.append(nic_spec)

    spec.deviceChange = nic_changes
    e = vm.ReconfigVM_Task(spec=spec)
    time.sleep(2)
    print e.info
    print "NIC CARD ADDED"
```
e.info
```
(vim.TaskInfo) {
   dynamicType = <unset>,
   dynamicProperty = (vmodl.DynamicProperty) [],
   key = 'haTask-52-vim.VirtualMachine.reconfigure-4941',
   task = 'vim.Task:haTask-52-vim.VirtualMachine.reconfigure-4941',
   description = <unset>,
   name = vim.VirtualMachine.Reconfigure,
   descriptionId = 'VirtualMachine.reconfigure',
   entity = 'vim.VirtualMachine:52',
   entityName = 'debian_test',
   locked = (vim.ManagedEntity) [],
   state = 'error',
   cancelled = false,
   cancelable = false,
   error = (vim.fault.InvalidDeviceSpec) {
      dynamicType = <unset>,
      dynamicProperty = (vmodl.DynamicProperty) [],
      msg = "Invalid configuration for device '0'.",
      faultCause = <unset>,
      faultMessage = (vmodl.LocalizableMessage) [],
      property = u'macAddress',
      deviceIndex = 0
   },
   result = <unset>,
   progress = <unset>,
   reason = (vim.TaskReasonUser) {
      dynamicType = <unset>,
      dynamicProperty = (vmodl.DynamicProperty) [],
      userName = 'root'
   },
   queueTime = 2016-05-12T15:26:10.380285Z,
   startTime = 2016-05-12T15:26:10.381482Z,
   completeTime = 2016-05-12T15:26:10.461607Z,
   eventChainId = 4941,
   changeTag = <unset>,
   parentTaskKey = <unset>,
   rootTaskKey = <unset>,
   activationId = <unset>
}
```

**Comment by vito** [comment]
please stop pinging random people. I have nothing to do with this project.

**Comment by zhongshun89** [comment]
@bisanidhruv 
 def listVmwareData(conn, dataTypeList):
    """
    根据dataTypeList的类型查找相应的对象列表
    """
    content = conn.RetrieveContent()
    container = content.rootFolder
    viewType = dataTypeList
    recursive = True
    containerView = content.viewManager.CreateContainerView(
        container, viewType, recursive)
    infoList = containerView.view
    return infoList

    def create(self, **valueDict):
        errorMsg = None
        spec = vim.vm.ConfigSpec()
        nic_changes = []
        nic_spec = vim.vm.device.VirtualDeviceSpec()
        #nic_spec.fileOperation = "create"
        nic_spec.operation = vim.vm.device.VirtualDeviceSpec.Operation.add
        nic_spec.device = vim.vm.device.VirtualE1000()
        # nic_spec.device.deviceInfo = vim.Description()
        # nic_spec.device.deviceInfo.label = 'Network adapter 10'
        # nic_spec.device.deviceInfo.summary = 'Internal-Net1'
        nic_spec.device.backing = vim.vm.device.VirtualEthernetCard.NetworkBackingInfo()
        nic_spec.device.backing.useAutoDetect = False
        portGroupList = listVmwareData(self.vmConnect, [vim.Network])
        nic_spec.device.backing.network = portGroupList[0]
        nic_spec.device.backing.network.name = portGroupList[0].name
        nic_spec.device.connectable = vim.vm.device.VirtualDevice.ConnectInfo()
        nic_spec.device.connectable.startConnected = True
        nic_spec.device.connectable.allowGuestControl = True
        nic_spec.device.connectable.connected = False
        nic_spec.device.connectable.status = 'untried'
        nic_spec.device.wakeOnLanEnabled = True
        nic_spec.device.addressType = 'assigned'
        nic_changes.append(nic_spec)
        spec.deviceChange = nic_changes
        createTask = self.vm.ReconfigVM_Task(spec=spec)
        tasks.wait_for_tasks(self.vmConnect, [createTask])
        if createTask.info.state == 'error':
            errorMsg = "创建网卡失败:" + createTask.info.error.msg
        return errorMsg

**Comment by zhongshun89** [comment]
@bisanidhruv 

`def listVmwareData(conn, dataTypeList):
    """
    根据dataTypeList的类型查找相应的对象列表
    """
    content = conn.RetrieveContent()
    container = content.rootFolder
    viewType = dataTypeList
    recursive = True
    containerView = content.viewManager.CreateContainerView(
        container, viewType, recursive)
    infoList = containerView.view
    return infoList`

`    def create(self):
        errorMsg = None
        spec = vim.vm.ConfigSpec()
        nic_changes = []
        nic_spec = vim.vm.device.VirtualDeviceSpec()
        #nic_spec.fileOperation = "create"
        nic_spec.operation = vim.vm.device.VirtualDeviceSpec.Operation.add
        nic_spec.device = vim.vm.device.VirtualE1000()
        # nic_spec.device.deviceInfo = vim.Description()
        # nic_spec.device.deviceInfo.label = 'Network adapter 10'
        # nic_spec.device.deviceInfo.summary = 'Internal-Net1'
        nic_spec.device.backing = vim.vm.device.VirtualEthernetCard.NetworkBackingInfo()
        nic_spec.device.backing.useAutoDetect = False
        portGroupList = listVmwareData(self.vmConnect, [vim.Network])
        nic_spec.device.backing.network = portGroupList[0]
        nic_spec.device.backing.network.name = portGroupList[0].name
        nic_spec.device.connectable = vim.vm.device.VirtualDevice.ConnectInfo()
        nic_spec.device.connectable.startConnected = True
        nic_spec.device.connectable.allowGuestControl = True
        nic_spec.device.connectable.connected = False
        nic_spec.device.connectable.status = 'untried'
        nic_spec.device.wakeOnLanEnabled = True
        nic_spec.device.addressType = 'assigned'
        nic_changes.append(nic_spec)
        spec.deviceChange = nic_changes
        createTask = self.vm.ReconfigVM_Task(spec=spec)
        tasks.wait_for_tasks(self.vmConnect, [createTask])
        if createTask.info.state == 'error':
            errorMsg = "创建网卡失败:" + createTask.info.error.msg
        return errorMsg
`

**Comment by zhongshun89** [comment]
@bisanidhruv 
def listVmwareData(conn, dataTypeList):
    """
    根据dataTypeList的类型查找相应的对象列表
    """
    content = conn.RetrieveContent()
    container = content.rootFolder
    viewType = dataTypeList
    recursive = True
    containerView = content.viewManager.CreateContainerView(
        container, viewType, recursive)
    infoList = containerView.view
    return infoList

def create():
        errorMsg = None
        spec = vim.vm.ConfigSpec()
        nic_changes = []
        nic_spec = vim.vm.device.VirtualDeviceSpec()
        #nic_spec.fileOperation = "create"
        nic_spec.operation = vim.vm.device.VirtualDeviceSpec.Operation.add
        nic_spec.device = vim.vm.device.VirtualE1000()
        # nic_spec.device.deviceInfo = vim.Description()
        # nic_spec.device.deviceInfo.label = 'Network adapter 10'
        # nic_spec.device.deviceInfo.summary = 'Internal-Net1'
        nic_spec.device.backing = vim.vm.device.VirtualEthernetCard.NetworkBackingInfo()
        nic_spec.device.backing.useAutoDetect = False
        portGroupList = listVmwareData(self.vmConnect, [vim.Network])
        nic_spec.device.backing.network = portGroupList[0]
        nic_spec.device.backing.network.name = portGroupList[0].name
        nic_spec.device.connectable = vim.vm.device.VirtualDevice.ConnectInfo()
        nic_spec.device.connectable.startConnected = True
        nic_spec.device.connectable.allowGuestControl = True
        nic_spec.device.connectable.connected = False
        nic_spec.device.connectable.status = 'untried'
        nic_spec.device.wakeOnLanEnabled = True
        nic_spec.device.addressType = 'assigned'
        nic_changes.append(nic_spec)
        spec.deviceChange = nic_changes
        createTask = self.vm.ReconfigVM_Task(spec=spec)
        tasks.wait_for_tasks(self.vmConnect, [createTask])
        if createTask.info.state == 'error':
            errorMsg = "创建网卡失败:" + createTask.info.error.msg
        return errorMsg

**Comment by Hyperazzi** [comment]
Does anyone have a solution for this problem? I am trying to add an already created Vswitch named "VM Network" to my VM. As in if I went in Vcenter VM->Add New Hardware->Network Adapter. However I get the same error as the user above:

```

def addNetwork(vm, server, switch_name):
    print switch_name
    spec = vim.vm.ConfigSpec()

    # add Switch here
    dev_changes = []
    switch_spec                = vim.vm.device.VirtualDeviceSpec()
    switch_spec.fileOperation  = "create"
    switch_spec.operation      = vim.vm.device.VirtualDeviceSpec.Operation.add
    switch_spec.device         = vim.vm.device.VirtualVmxnet3()
    
    switch_spec.device.backing = vim.vm.device.VirtualEthernetCard.NetworkBackingInfo()
    
    switch_spec.device.backing.useAutoDetect = False
    switch_spec.device.backing.network = switch_name
    
    switch_spec.device.connectable = vim.vm.device.VirtualDevice.ConnectInfo()
    switch_spec.device.connectable.startConnected = True
    switch_spec.device.connectable.connected = True

    dev_changes.append(switch_spec)
        
    spec.deviceChange = dev_changes
    output = vm.ReconfigVM_Task(spec=spec)
    
    print output.info

 if __name__ == '__main__':
     args = getArgs()
    
    print args
    # connect this thing
    server = SmartConnect( host = args.host,
                           user = args.user,
                           pwd  = args.password,
                           port = args.port )
    # disconnect this thing
    atexit.register(Disconnect, server)
    
    vm = None
    content = server.RetrieveContent()
    esxi_host = get_obj(content, [vim.HostSystem], "esxi06")
    
    
    vm = get_obj(content, [vim.VirtualMachine], args.vm_name)
    
    network = None
    network = get_obj(content, [vim.Network], "VM Network")
    print network
    
    if vm and network:
        addNetwork(vm, server, network)
        print "Works!"
        exit(0)
    else:
        print "VM or Network not found"
        exit(1)

```

**Comment by prziborowski** [comment]
@Hyperazzi did you try removing:
```    switch_spec.fileOperation  = "create"```
as defionscode mentioned?

**Comment by Hyperazzi** [comment]
I had did that previously and ran into the same issue. I tried it again now and the network adapter got created on the VM, however the Network field in the adapter shows up as blank with (DATA NOT AVAILABLE) being displayed right next to it. Also cannot remove this adapter.

**Comment by prziborowski** [comment]
It looks like one more thing was missing
```    switch_spec.device.backing.network.deviceName = switch_name.name ```

You can likely remove the other one with the API:
```
from pyVim.task import WaitForTask
...

devices = filter(lambda x: isinstance(x.backing, vim.vm.device.VirtualEthernetCard.LegacyNetworkBackingInfo), vm.config.hardware.device)
for device in devices:
   spec.deviceChange.append(vim.vm.device.VirtualDeviceSpec(device=device, operation='remove'))
WaitForTask(vm.Reconfigure(spec))
```

**Comment by Hyperazzi** [comment]
Unfortunately the code
`switch_spec.device.backing.network.deviceName = switch_name.name`

Throws this exception:
```

Traceback (most recent call last):
  File "/root/workspace/addDiskAndNetwork/add_network.py", line 100, in <module>
    addNetwork(vm, server, network)
  File "/root/workspace/addDiskAndNetwork/add_network.py", line 63, in addNetwork
    switch_spec.device.backing.network.deviceName = switch_name.name
  File "/usr/local/lib64/python2.6/site-packages/pyVmomi/VmomiSupport.py", line 454, in __setattr__
    raise Exception("Managed object attributes are read-only")
Exception: Managed object attributes are read-only
```

**Comment by prziborowski** [comment]
Sorry again. I was experimenting and I guess I typed rather than copy/pasted the result:
switch_spec.device.backing.deviceName = switch_network.name

**Comment by Hyperazzi** [comment]
Yep that fixed it. Thanks!
