### ISSUE TITLE
New Sample: browse datastore and delete particular folder

### ISSUE THREAD

**Issue by amarsbhosale** [vmware/pyvmomi-community-samples#230]
Requirements: Create folder manually into ESX datastore lets say with name "xyz". Delete newly created folder "xyz" using pyvmomi APIs

**Comment by chinmayb** [comment]
use the below snippet

`content.fileManager.MakeDirectory("[datastore1]/foldername", dc_obj, createParentDirectories=True)`

**Comment by RobertClove** [comment]
How to delete it?

**Comment by dav1x** [comment]
@RobertClove you should be able to call the obj with the method .Destroy()

**Comment by prziborowski** [comment]
@RobertClove please refer to the API docs for [FileManager](http://pubs.vmware.com/vsphere-65/index.jsp#com.vmware.wssdk.apiref.doc/vim.FileManager.html)

```
DeleteDatastoreFile_Task(deleteFile)
name	The name of the file or folder, either a URL or a datastore path referring to the file or folder to be deleted. 
datacenter to a Datacenter, If name is a datastore path, the datacenter for that datastore path. Not needed when invoked directly on ESX. If not specified on a call to VirtualCenter, name must be a URL. 
```

from pyVim.task import WaitForTask
WaitForTask(content.fileManager.DeleteFile("[datastore1]/foldername", dc_obj))
