### ISSUE TITLE
Problems setting ovf options

### ISSUE THREAD

**Issue by yostie** [vmware/pyvmomi-community-samples#232]
I am attempting to reuse some of the code in the deploy_ovf sample in order to deploy an OVF that looks for the user to choose non-standard options.  I'm having an issue with the import specs.  From the OVF descriptor, I believe it is looking for a deployment option (there are 4 options to choose from in the OVF).  I am just unsure how I tell the script which option I want.  My best guess is that I need to specify this by setting the a Key/value pair in propertyMapping within CreateImportSpecParams.  If I am correct, I'm not sure sure what to use for the key.  If this was the snippet from the ovf file, would it be looking for a key/value pair of say Configuration : Option1 ?

```xml
  <DeploymentOptionSection>
    <Info>List of deployment options for app</Info>
    <Configuration ovf:id="Option1">
      <Label>Option 1 label</Label>
      <Description>
Option 1 description
      </Description>
    </Configuration>
    <Configuration ovf:id="Option2">
      <Label>Option 2 label</Label>
      <Description>
Option 2 description
      </Description>
    </Configuration>
  </DeploymentOptionSection>
```

I think I would need to create a KeyValue object with vim and then pass it as a propertyMapping.  Please let me know if I am on the right track here.  Also, if anyone has any example code of how I might do this, it would save me time.  Thanks!

**Comment by yostie** [comment]
I figured out most of my issues, but am still having a problem.  I have to specify a networkMapping and all the examples out there use standard vSwitches but I have Nexus 1000V which is a DVS.  I created a networkMapping

**Comment by yostie** [comment]
I figured out the issue.  When I was creating the netmap to pass the NIC name and the Network object, it was expecting "eth0" as the name of the NIC and not something custom that I was selecting.

**Comment by howardjones** [comment]
What was the correct method? I am doing the same thing and "CreateImportSpecParams vim.KeyValue pyvmomi" produces very few google results...

**Comment by ed02468** [comment]
Hi @howardjones, were you able to find info on this? I am currently having same problem, trying to specify a propertyMapping for the createImportSpecParams. It is unclear what keys I can provide and what the syntax of it is...
Thanks! Ed

**Comment by peturgq** [comment]
I'm stuck here as well, docs are not clear and there are no examples on how to use vim.KeyValue nor is there any for propertyMapping.

@yostie sharing some examples of how you made it work would be awesome.

**Comment by prziborowski** [comment]
The possible keys for properties vary dependent on the OVF. You can look the descriptor under ovf/VirtualSystem/Property children.
Also you can pass the OVF contents to OvfManager.[ParseDescriptor](https://code.vmware.com/apis/196/vsphere#/doc/vim.OvfManager.html#parseDescriptor)(ovfDescriptor, pdp) and the result's property array will have the key you can use (as well as if it is user-configurable).
Documentation on [KeyValue](https://code.vmware.com/apis/196/vsphere#/doc/vim.KeyValue.html) is not too complicated. Just a key field and value field, where the key is a string, and the value could be just about anything (but for properties, you should look at the parseDescriptor result's property array type value).
```
properties = [
   vim.KeyValue(key='guestinfo.cis.appliance.net.mode', value='static'),
   vim.KeyValue(key='guestinfo.cis.appliance.net.addr, value='192.168.0.5')
]
```
would be a small example of populating an array of properties.

**Comment by rajapraveen1021** [comment]
I'm stuck with the same problem... The ImportSpec parameter is <unset>. Any one who has some inputs?????


(vim.OvfManager.CreateImportSpecResult) {
   dynamicType = <unset>,
   dynamicProperty = (vmodl.DynamicProperty) [],
   importSpec = <unset>,
   fileItem = (vim.OvfManager.FileItem) [],
   warning = (vmodl.MethodFault) [],
   error = (vmodl.MethodFault) [
      (vim.fault.OvfNoHostNic) {
         dynamicType = <unset>,
         dynamicProperty = (vmodl.DynamicProperty) [],
         msg = 'Host did not have any virtual network defined.',
         faultCause = <unset>,
         faultMessage = (vmodl.LocalizableMessage) [],
         lineNumber = <unset>

**Comment by yostie** [comment]
Here is an example of what I did.  My assumption is that you have connected to vCenter and have a service instance object called 'si'.  First you have to pull in the OVF descriptor file from wherever you are storing it (code not shown).  Lets call it 'ovfd'.  You need to create the NetworkMapping object which I am calling 'netmap' before creating any of the ImportSpec stuff.

    # 'name' is a string specified in the OVF descriptor file.  You need to look here for what it wants.
    netmap = [vim.OvfManager.NetworkMapping(name='eth0', network='My_VMware_Portgroup')]
    manager = si.content.ovfManager

    # 'opt' is a string of an option that is listed in the OVF descriptor.  Look there for what it wants if anything.
    isp = vim.OvfManager.CreateImportSpecParams(locale='en-US', deploymentOption=opt, entityName='MY_VM', networkMapping=netmap, ipAllocationPolicy='fixedPolicy', ipProtocol='IPv4', diskProvisioning='thick')

    # 'respool' is a ResourcePool Object (code not shown)
    # 'ds' is a DataStore object (code not shown)
    ispec = manager.CreateImportSpec(ovfd, respool, ds, isp)

    # 'folder' is a Folder object (code not shown)
    # 'host' is a HostSystem object (code not shown)
    lease = respool.ImportVApp(ispec.importSpec, folder, host)

Obviously you may need to alter some of the options above to fit your environment.

Hope this helps!

**Comment by pranky89** [comment]
I struggled a lot with ovfdeploy as i wanted to pass special parameters for it and then i found this issue. Special thanks to @prziborowski for giving the hint on how to find out the information and i am going to use this post to actually make it noobs friendly.

Let's suppose you have an OVF file, then the first thing that you have to do is to get all the key-values from the OVF descriptor:

```
    ovf_handle = OvfHandler(args.ova_path)
    ovfManager = si.content.ovfManager

    p = ovfManager.ParseDescriptor(ovf_handle.get_descriptor(), vim.OvfManager.ParseDescriptorParams(locale='en-US'))
    print p
```

This code should dump all the key-value pairs from your OVF descriptor that you can use to pass the special arguments to deploy OVA. It might look like this:

```
   property = (vim.vApp.PropertyInfo) [
      (vim.vApp.PropertyInfo) {
         dynamicType = <unset>,
         dynamicProperty = (vmodl.DynamicProperty) [],
         **key = 0,**
         classId = 'vami',
         instanceId = 'vProxy',
         id = 'DNS',
         category = 'Networking Properties',
         label = 'DNS',
         type = 'string',
         typeReference = '',
         userConfigurable = true,
         defaultValue = '',
         value = <unset>,
         description = 'Specify up to three domain name servers for this VM, separated by commas. '
      },
      (vim.vApp.PropertyInfo) {
         dynamicType = <unset>,
         dynamicProperty = (vmodl.DynamicProperty) [],
         **key = 1,**
         classId = 'vami',
         instanceId = 'vProxy',
         id = 'fqdn',
         category = 'Properties of VM Network',
         label = 'FQDN [e.g. hostname.domain]',
         type = 'string',
         typeReference = '',
         userConfigurable = true,
         defaultValue = '',
         value = <unset>,
         description = 'Specify the fully qualified domain name for this VM, on this network.'
      },
      (vim.vApp.PropertyInfo) {
         dynamicType = <unset>,
         dynamicProperty = (vmodl.DynamicProperty) [],
         **key = 2,**
         classId = 'vami',
         instanceId = 'vProxy',
         id = 'ip0',
         category = 'Properties of VM Network',
         label = 'IP Address',
         type = 'string',
         typeReference = '',
         userConfigurable = true,
         defaultValue = '',
         value = <unset>,
         description = 'Specify the IP address for this VM. '
      },
```

If you want to setup all of the above three parameters, then, keep the key_id's handy and do the following:

```
    properties = [vim.KeyValue(key='0', value='10.10.10.122'), vim.KeyValue(key='1', value='peter.ms.com'), vim.KeyValue(key='2', value='10.10.10.10'), vim.KeyValue(key='3', value='255.255.255.255')]	
    cisp = vim.OvfManager.CreateImportSpecParams(entityName='vProxy_Thing', networkMapping= netmap, ipAllocationPolicy='fixedPolicy', ipProtocol='IPv4', diskProvisioning='thick', propertyMapping=properties)		
	
    cisr = ovfManager.CreateImportSpec(ovf_handle.get_descriptor(),
                                       rp, ds, cisp)
```

Notice how am i using the properties variable to pass the key-values pair and each key id has an associated value attached to it.

Then we need to simply pass the properties to propertiesmapping of CISP which will eventually be passed to createimportspec.

If you get hold of this example, it might just be working on your OVF key-values to identify what all you need to pass.

Hope this helps,

Pankaj

**Comment by pranky89** [comment]
Hi @prziborowski can you help here pls?

This is my OVFdescriptor :

   property = (vim.vApp.PropertyInfo) [
      (vim.vApp.PropertyInfo) {
         dynamicType = <unset>,
         dynamicProperty = (vmodl.DynamicProperty) [],
         key = 0,
         classId = 'vami',
         instanceId = 'xVM',
         id = 'DNS',
         category = 'Networking Properties',
         label = 'DNS',
         type = 'string',
         typeReference = '',
         userConfigurable = true,
         defaultValue = '',
         value = <unset>,
         description = 'Specify up to three domain name servers for this VM, separated by commas. '
      },
      (vim.vApp.PropertyInfo) {
         dynamicType = <unset>,
         dynamicProperty = (vmodl.DynamicProperty) [],
         key = 1,
         classId = 'vami',
         instanceId = 'xVM',
         id = 'fqdn',
         category = 'Properties of VM Network',
         label = 'FQDN [e.g. hostname.domain]',
         type = 'string',
         typeReference = '',
         userConfigurable = true,
         defaultValue = '',
         value = <unset>,
         description = 'Specify the fully qualified domain name for this VM, on this network.'
      },
      (vim.vApp.PropertyInfo) {
         dynamicType = <unset>,
         dynamicProperty = (vmodl.DynamicProperty) [],
         key = 2,
         classId = 'vami',
         instanceId = 'xVM',
         id = 'ip0',
         category = 'Properties of VM Network',
         label = 'IP Address',
         type = 'string',
         typeReference = '',
         userConfigurable = true,
         defaultValue = '',
         value = <unset>,
         description = 'Specify the IP address for this VM. '
      },

And i am trying to deploy the OVA and want to pass these parameters(all 3) with value but seems like it doesn't work.

This is what i have tried so far :

```
    properties = [
        vim.KeyValue(key='guestinfo.cis.appliance.net.mode', value='static'),
        vim.KeyValue(key='guestinfo.cis.appliance.net.addr', value='192.168.0.5')
    ]	
```

and

`properties = [vim.KeyValue(key='DNS', value='10.10.17.122'), vim.KeyValue(key='fqdn', value='papa.ms.lab'), vim.KeyValue(key='ip0', value='10.10.10.10'), vim.KeyValue(key='netmask0', value='255.255.255.255')]`

and

`    properties = [vim.KeyValue(key='0', value='10.10.17.122'), vim.KeyValue(key='1', value='papa.ms.lab'), vim.KeyValue(key='2', value='10.10.10.10'), vim.KeyValue(key='3', value='255.255.255.255')]`

seems like none of the above are working for me. How should i pass these values to CISP? 

`    cisp = vim.OvfManager.CreateImportSpecParams(entityName='Thing', networkMapping= netmap, ipAllocationPolicy='fixedPolicy', ipProtocol='IPv4', diskProvisioning='thick', propertyMapping=properties)`

**Comment by pranky89** [comment]
FOUND IT !!!! 

I struggled a lot with ovfdeploy as i wanted to pass special parameters for it and then i found this issue. 
Special thanks to @prziborowski for giving the hint on how to find out the information and i am going to use this post to actually make it noobs friendly.

Let's suppose you have an OVF file, then the first thing that you have to do is to get all the key-value pairs from the OVF descriptor:

There are two ways to do this :

Type 1 : You use the ovfdescriptor and then build out your key-value pairs
Type 2 : You deploy the ova manually and then open the vApp properties for it to know the key names and values accepted by it(string, int etc.)

Type 1:
----------
Use the below code to dump the ovfdescriptor

```
    ovf_handle = OvfHandler(args.ova_path)
    ovfManager = si.content.ovfManager

    p = ovfManager.ParseDescriptor(ovf_handle.get_descriptor(), vim.OvfManager.ParseDescriptorParams(locale='en-US'))
    print p
```

This code should dump all the key-value pairs from your OVF descriptor that you can use to pass the special arguments to deploy OVA. It might look like this:

```
   property = (vim.vApp.PropertyInfo) [
      (vim.vApp.PropertyInfo) {
         dynamicType = <unset>,
         dynamicProperty = (vmodl.DynamicProperty) [],
         **key = 0,**
         classId = 'vami',
         instanceId = 'vmg',
         id = 'DNS',
         category = 'Networking Properties',
         label = 'DNS',
         type = 'string',
         typeReference = '',
         userConfigurable = true,
         defaultValue = '',
         value = <unset>,
         description = 'Specify up to three domain name servers for this VM, separated by commas. '
      },
      (vim.vApp.PropertyInfo) {
         dynamicType = <unset>,
         dynamicProperty = (vmodl.DynamicProperty) [],
         **key = 1,**
         classId = 'vami',
         instanceId = 'vmg',
         id = 'fqdn',
         category = 'Properties of VM Network',
         label = 'FQDN [e.g. hostname.domain]',
         type = 'string',
         typeReference = '',
         userConfigurable = true,
         defaultValue = '',
         value = <unset>,
         description = 'Specify the fully qualified domain name for this VM, on this network.'
      },
      (vim.vApp.PropertyInfo) {
         dynamicType = <unset>,
         dynamicProperty = (vmodl.DynamicProperty) [],
         **key = 2,**
         classId = 'vami',
         instanceId = 'vmg',
         id = 'ip0',
         category = 'Properties of VM Network',
         label = 'IP Address',
         type = 'string',
         typeReference = '',
         userConfigurable = true,
         defaultValue = '',
         value = <unset>,
         description = 'Specify the IP address for this VM. '
      },
```

If you want to setup all of the above three parameters, then, keep the following items handy 
1) id
2) instanceId
3) ClassId

Note : Forget about the key parameter, it's useless.

Your actual key becomes : classid.id.instanceId (eg: vami.DNS.vmg)

Type 2:
--------------
1) Deploy the ova manually in vCenter
2) Open the ova properties and navigate to vapp options
3) Expand the Authoring and then expand properties -> This should list all the keys that you can use 

Now, once you have the key and values defined, you can proceed with the following:


```
        properties = [
	#Core_network_information_NIC#1
    vim.KeyValue(key='vami.fqdn.vmg', value='ice.ms.lab'), 	
    vim.KeyValue(key='vami.ip0.vmg', value='10.60.37.144'),	
    vim.KeyValue(key='vami.DNS.vmg', value='10.10.10.100'), 	
    ]
    cisp = vim.OvfManager.CreateImportSpecParams(entityName='The_Thing', networkMapping= netmap, ipAllocationPolicy='fixedPolicy', ipProtocol='IPv4', diskProvisioning='thick', propertyMapping=properties)		
	
    cisr = ovfManager.CreateImportSpec(ovf_handle.get_descriptor(),
                                       rp, ds, cisp)
```

Notice how I'm using the properties array to pass the key-values pair and each key id has an associated value attached to it.

Then we need to simply pass the properties to propertiesmapping of CISP which will eventually be passed to createimportspec.

If you get hold of this example, you should be able to figure out how to set these properties.

And off course, for those of you who wonder, this is how you get the netmap:

```
    if args.network:
        network = get_obj(content, [vim.Network], args.network)		
        netmap = [vim.OvfManager.NetworkMapping(name='eth0', network=network)]		
    else:
        network = get_obj(content, [vim.Network], 'VM Network')	  		
        netmap = [vim.OvfManager.NetworkMapping(name='eth0', network=network)]	
```

Note : Some of the information documented might be specific to my environment and might not work in yours. Don't blame me :)

Hope this generously helps someone like me in desperate need. Have fun.

Pankaj

**Comment by haozheng95** [comment]
Hi @pranky89 
I ran into problems with properties when deploying VCF. But please take a look at the result I got when I read the ova. instanceId and ClassId are ' ', in which case what should I do?

`(vim.vApp.PropertyInfo) {
         dynamicType = <unset>,
         dynamicProperty = (vmodl.DynamicProperty) [],
         key = 4,
         classId = '',
         instanceId = '',
         id = 'guestinfo.hostname',
         category = 'Application',
         label = 'Hostname',
         type = 'string',
         typeReference = '',
         userConfigurable = true,
         defaultValue = '',
         value = <unset>,
         description = 'Enter a hostname for this virtual appliance.'
      },
      (vim.vApp.PropertyInfo) {
         dynamicType = <unset>,
         dynamicProperty = (vmodl.DynamicProperty) [],
         key = 5,
         classId = '',
         instanceId = '',
         id = 'guestinfo.ip0',
         category = 'Application',
         label = 'Network 1 IP Address',
         type = 'string',
         typeReference = '',
         userConfigurable = true,
         defaultValue = '',
         value = <unset>,
         description = 'Enter an IP Address for the interface of this virtual appliance.'
      },
      (vim.vApp.PropertyInfo) {
         dynamicType = <unset>,
         dynamicProperty = (vmodl.DynamicProperty) [],
         key = 6,
         classId = '',
         instanceId = '',
         id = 'guestinfo.netmask0',
         category = 'Application',
         label = 'Network 1 Subnet Mask',
         type = 'string',
         typeReference = '',
         userConfigurable = true,
         defaultValue = '',
         value = <unset>,
         description = 'Enter a subnet mask for the interface of this virtual appliance. Example: 255.255.255.0'
      },`

**Comment by jayadev-m-s** [comment]
@haozheng95 , you have found any solution to your problem, when the instanceId and ClassId are empty ?
