### ISSUE TITLE
Customize an existing VM example

### ISSUE THREAD

**Issue by bigmyx** [vmware/pyvmomi-community-samples#245]
Hi,
Can you please show how to customize an existing VM?
For instance, if I have `vim.vm` object `vm`
and I want to modify `vm.config.hardware.numCPU` (which is now == 2),
I wan to set it to `8`.
Thanks!

**Comment by NaveenBellary** [comment]
This might help you

https://gist.github.com/snobear/8788977#file-clone-py-L179

**Comment by jm66** [comment]
```
spec = vim.vm.ConfigSpec()
spec.numCPUs = 8
task = vm_obj.ReconfigVM_Task(spec=spec)
tasks.wait_for_tasks(si, [task])
```
