### ISSUE TITLE
get host uuid

### ISSUE THREAD

**Issue by wangsuyi640** [vmware/pyvmomi-community-samples#246]
the host uuid get by pyvmomi api is:
In [54]: esxi_host.hardware.systemInfo.uuid
Out[54]: '16d67ccc-d67c-11e3-84ff-8edada343434'

while the command "esxcli system uuid get" output is:
566a465d-4498-62c0-51a2-3440b5c5cd68

They are not name, why?

**Comment by prziborowski** [comment]
The uuid in systemInfo is the hardware uuid rather than the system.
It should match up with "esxcli hardware platform get"
(I'm not sure at the moment where to gather the value of esxcli system uuid get with pyvmomi api)

**Comment by Preacher066** [comment]
The value of esxcli system uuid can be get using:

"esxcli system uuid get"
