### ISSUE TITLE
Getting Vm by name

### ISSUE THREAD

**Issue by matan12333** [vmware/pyvmomi-community-samples#266]
Is there a simple way to get a vm in to a variable like in PySphere?
Something like vm=server.get_vm_by_name("_vmname_")?
If not, what is the simpelest way to do so?

**Comment by chiisaihayashi** [comment]
you can get the similar function by doing like follow.

```
def get_obj(content, vimtype, name):
    obj = None
    container = content.viewManager.CreateContainerView(
        content.rootFolder, vimtype, True)
    for c in container.view:
        if name:
            if c.name == name:
                obj = c
                break
        else:
            obj = c
            break

    return obj


vm = get_obj(content, [vim.VirtualMachine], "vmname")
```

Reference: [vim.VirtualMachine](https://github.com/vmware/pyvmomi/blob/master/docs/vim/VirtualMachine.rst)

**Comment by prziborowski** [comment]
If you know the datacenter it is in, the easiest way would be to use [SearchIndex's](http://pubs.vmware.com/vsphere-60/index.jsp#com.vmware.wssdk.apiref.doc/vim.SearchIndex.html) FindChild.

si.content.searchIndex.FindChild(dc.vmFolder, "vmname")
And it will either return the VirtualMachine or None. I'm sure there are limitations such as not search under sub folders, so if your vCenter is hierarchical is that way, viewManager's CreateContainerView might be more accurate (although I think each comparison of VM's name will make roundtrips to vCenter and take more time).

**Comment by antekone** [comment]
Yes, it makes roundtrip for each comparison, if the datacenter contains hundreds of VMs, then locating a VB by name using this method takes ages.
