### ISSUE TITLE
New Sample:Getting the Vm name for the given IP Address in python script using pyvmomi.

### ISSUE THREAD

**Issue by Suryadhulipudi** [vmware/pyvmomi-community-samples#267]
Hi Team,

Can someone help me,how to get the vm name for the given ip address in python script.
I am using pyvmomi python package.

Thanks in Advance.

**Comment by prziborowski** [comment]
Sorry, I lost track of this request.
You should be able to leverage SearchIndex for this.
```
si = SmartConnect(...)
ipAddress = '192.0.0.1' # put in the IP you are interested in
searchIndex = si.RetrieveContent().searchIndex
vms = searchIndex.FindAllByIp(ip=ipAddress, vmSearch=True)
if len(vms) == 0:
   print "No VMs with IP: %s" % ipAddress
else:
   for vm in vms:
      print vm.name
```

**Comment by Suryadhulipudi** [comment]
@prziborowski ....Thanks for the help...I will check and let you know.

**Comment by Suryadhulipudi** [comment]
Thank you @prziborowski It's working fine...

**Comment by arturor19** [comment]
@prziborowski Thanks a lot that solved my issue !!

**Comment by pgbidkar** [comment]
@sureshsundriyal , Closing the issue, as per your last update.

Thanks
