### ISSUE TITLE
Getting configuration information from an OVF

### ISSUE THREAD

**Issue by TheGrav3mind** [vmware/pyvmomi-community-samples#268]
Hi guys!

So I am doing some work deploying OVF's and I would like to build an expected result of the deployment (in terms of set reservations) from the OVF, and then compare those values to the result of polling vsphere for the reservations that actually exist on the VM after the OVF is deployed.

My first solution to this problem was to build an xml parser and pull out the values from the OVF but this has proven to be prohibitivley time consuming (for me). I figured that some combination of spec params and pdp can give me the reservations for a specified configuration type. Has anyone done this or know how to do this? I am really new to pyvimomi.

Thanks everyone!
Chris

**Comment by jm66** [comment]
Take a look at ```vim.OvfManager.ParseDescriptorParams``` and ```si.content.ovfManager.ParseDescriptor```. I've parsed the OVF to get configured network adapters for example.
