### ISSUE TITLE
How to check if an ESXi host is managed by a vCenter ?

### ISSUE THREAD

**Issue by steph-ben** [vmware/pyvmomi-community-samples#270]
I'm trying to check if an ESXi host is managed by a vCenter or not.

I looked into VMWare API Documentation http://pubs.vmware.com/vi3/sdk/ReferenceGuide/vim.HostSystem.html but I didn't find any clue.
If anyone know about that tips ...

**Comment by asonar** [comment]
host_obj.summary.managementServerIp .. will give you vCenter IP/hostname details if its managed by vCenter server.

**Comment by steph-ben** [comment]
That's great, thanks a lot.
How did you find this variable ?? Don't see it in the doc.

**Comment by prziborowski** [comment]
Perhaps the vi3 docs didn't have that value. It is listed in the 6.0 ones:
http://pubs.vmware.com/vsphere-60/index.jsp?topic=%2Fcom.vmware.wssdk.apiref.doc%2Fvim.host.Summary.html
