### ISSUE TITLE
How to get esxi host in a cluster?

### ISSUE THREAD

**Issue by yangyangyang001** [vmware/pyvmomi-community-samples#274]
I can get cluster in a datacenter with datacenter.hostFolder.childEntity. but i cann‘t get esxi host info in a cluster, anyone can help me?

**Comment by asonar** [comment]
Can you try this... this should give you mor of all the hosts from the particular datacenter.

    allhosts=[]
    for entity in datacenter.hostFolder.childEntity:
      for host in entity.host:
        allhosts.append(host)
    print allhosts

Is this what you are looking for?

**Comment by yangyangyang001** [comment]
@asonar  Thanks for your answer.  I solve it in this way:
        dc_view = content.viewManager.CreateContainerView(content.rootFolder,
                                                            [vim.Datacenter],
                                                            True)
        for datacenter in dc_view.view:
            for data in datacenter.hostFolder.childEntity:
                if isinstance(data,vim.ClusterComputeResource):
                   print data.name

**Comment by sathvikm** [comment]
Hi,
Here is the script to list all clusters in a Data Center. If a Cluster name is provided to the script. It will list the hosts in the cluster.

    #!/usr/bin/env python
    """
    List Of Hosts in a Cluster
    """
    from pyVmomi import vim
    from pyVim.connect import SmartConnect, Disconnect
    import atexit
    import argparse
    import getpass
    import ssl
    import requests

    def get_args():
        """ Get arguments from CLI """
        parser = argparse.ArgumentParser(
            description='Arguments for talking to vCenter')

        parser.add_argument('-s', '--host',
                            required=True,
                            action='store',
                            help='vSpehre service to connect to')

        parser.add_argument('-o', '--port',
                            type=int,
                            default=443,
                            action='store',
                            help='Port to connect on')

        parser.add_argument('-u', '--user',
                            required=True,
                            action='store',
                            help='Username to use')

        parser.add_argument('-p', '--password',
                            required=False,
                            action='store',
                            help='Password to use')

        parser.add_argument('--cluster-name',
                            required=False,
                            action='store',
                            default=None,
                            help='Name of the cluster you wish to list the hosts')

        args = parser.parse_args()

        if not args.password:
            args.password = getpass.getpass(
                prompt='Enter password')

        return args



    def get_obj(content, vimtype, name = None):
        return [item for item in content.viewManager.CreateContainerView(
            content.rootFolder, [vimtype], recursive=True).view]


    def main():
        args = get_args()
        # Disabling urllib3 ssl warnings
        requests.packages.urllib3.disable_warnings()

        # Disabling SSL certificate verification
        context = ssl.SSLContext(ssl.PROTOCOL_TLSv1)
        context.verify_mode = ssl.CERT_NONE

        # connect this thing
        si = SmartConnect(
            host=args.host,
            user=args.user,
            pwd=args.password,
            port=args.port,
            sslContext=context)

        # disconnect this thing
        atexit.register(Disconnect, si)

        content = si.RetrieveContent()
        for cluster_obj in get_obj(content, vim.ComputeResource,
                args.cluster_name):
            if args.cluster_name:
                if cluster_obj.name == args.cluster_name:
                    for host in cluster_obj.host:
                        print host.name
            else:
                print cluster_obj.name


    # start this thing
    if __name__ == "__main__":
        main()

**Comment by dasrab** [comment]
how to run the above script

**Comment by dasrab** [comment]
how to get the all license name from datacenter

**Comment by tarcisiomiranda** [comment]
The same script for python3 and ignore ssl:

```
#!/usr/bin/env python
"""
List Of Hosts in a Cluster
"""
from pyVim import connect
from pyVmomi import vim
import sys
import atexit
import argparse
import getpass
import ssl
import requests

def get_args():
    """ Get arguments from CLI """
    parser = argparse.ArgumentParser(
        description='Arguments for talking to vCenter')

    parser.add_argument('-s', '--host',
                        required=True,
                        action='store',
                        help='vSpehre service to connect to')

    parser.add_argument('-o', '--port',
                        type=int,
                        default=443,
                        action='store',
                        help='Port to connect on')

    parser.add_argument('-u', '--user',
                        required=True,
                        action='store',
                        help='Username to use')

    parser.add_argument('-p', '--password',
                        required=False,
                        action='store',
                        help='Password to use')

    parser.add_argument('--cluster-name',
                        required=False,
                        action='store',
                        default=None,
                        help='Name of the cluster you wish to list the hosts')

    args = parser.parse_args()

    if not args.password:
        args.password = getpass.getpass(
            prompt='Enter password')

    return args



def get_obj(content, vimtype, name = None):
    return [item for item in content.viewManager.CreateContainerView(
        content.rootFolder, [vimtype], recursive=True).view]


def main():
    args = get_args()
    # connect this thing
    si = connect.SmartConnectNoSSL(
        host=args.host,
        user=args.user,
        pwd=args.password,
        port=args.port)

    # disconnect this thing
    atexit.register(connect.Disconnect, si)

    content = si.RetrieveContent()
    for cluster_obj in get_obj(content, vim.ComputeResource,
            args.cluster_name):
        if args.cluster_name:
            if cluster_obj.name == args.cluster_name:
                for host in cluster_obj.host:
                    print(host.name)
        else:
            print(cluster_obj.name)


# start this thing
if __name__ == "__main__":
    main()
```
