### ISSUE TITLE
Get physical disk info on an esxi host？

### ISSUE THREAD

**Issue by yangyangyang001** [vmware/pyvmomi-community-samples#275]
I want to find unused disk on an esxi，but I cann‘t’ get physical disk info. anyone can help ？

**Comment by chengpeng21186** [comment]
I also want to find physical disk info, anyone can help?

**Comment by chengpeng21186** [comment]
I slove this problem(from physical host name get informations):


def print_esxi_host_info(esxi_host, si):

    atexit.register(connect.Disconnect, si)
    content = si.RetrieveContent()
    container = content.rootFolder
    viewType = [vim.HostSystem]
    recursive = True
    containerView = content.viewManager.CreateContainerView(container, viewType, recursive)

    esxi_hosts = containerView.view
    containerView.Destroy()

    datastores = {}
    for esxi_host1 in esxi_hosts:
        if esxi_host1.name == esxi_host:
            #print 'esxi_host: ', esxi_host1.name
            #print esxi_host1.configManager
            #sys.exit(0)
            # datastore information
            storage_system = esxi_host1.configManager.storageSystem
            host_file_sys_vol_mount_info = storage_system.fileSystemVolumeInfo.mountInfo
            for host_mount_info in host_file_sys_vol_mount_info:
                #print host_mount_info
                if host_mount_info.volume.type == "VMFS" or host_mount_info.volume.type == "NFS":
                    #print host_mount_info
                    print 'Datastore name:', host_mount_info.volume.name
                    print 'Datastore capacity:', sizeof_fmt(host_mount_info.volume.capacity)
            # memory information
            memory_size = sizeof_fmt(esxi_host1.summary.hardware.memorySize)
            print 'Memory_size: ', memory_size
            # cpu information (This is logic cpu numbers)
            cpu_numbers = esxi_host1.summary.hardware.numCpuThreads
            print 'Cpu_numbers: ', cpu_numbers
