### ISSUE TITLE
Getting VSAN diskgroup information and disks per diskgroup information

### ISSUE THREAD

**Issue by vspvijay** [vmware/pyvmomi-community-samples#278]
Hi All,

Need to get diskgroup information from a VMWare VSAN host and also disk per diskgroup in that VSAN host?

Will be great help if someone can point to the class object which would help.

Thanks !

**Comment by asonar** [comment]
**disks=host_mor.configManager.vsanSystem.QueryDisksForVsan()**  ==> will give you list all disks in the host. 
**host_mor.configManager.vsanSystem.AddDisks(disk=disk_list)** ===> configure diskgroup.
**host_mor.config.vsanHostConfig.storageInfo.diskMapping** ==> get the info about existing disk group from the host.

**Comment by vspvijay** [comment]
Thank you for quick reply, asonar. This is what I was looking for. 

But, can you please give me little information on the host_mor object ? 

Is it different from this object, vim.vsan.host.ConfigInfo.StorageInfo ?

Thanks !

**Comment by asonar** [comment]
host_mor <- managed object reference for accessing the particular host in vCenter. Once you have this object, then you can perform all supported operation on that host.

You can use,
1. search_index api to find out the respective host_mor
2. create the required view and get all the host_mors from the datacenter 
3. Or iterate over datacenters/clusters and then get the host_mor

You can find the sample code in community_samples git repo for finding the exact object in vCenter.

**Comment by vspvijay** [comment]
Got your point, asonar. After connecting to the vCenter server,
search_index.FindByIp(None,VSAN_Host_Address,False) API call should help to get the host_mor. Will get back with the outcome. Thanks for the detailed description.

Quick question : Can't we take the disk group information after connecting to a ESXi host directly instead from vCenter? This is because, many a times my single host VSAN setup may not be managed by a vCenter Server. In that case, Will be blocked in this method. 

Thanks again !

**Comment by asonar** [comment]
You dont need vCenter. Above api's will work on vCenter/ESXi as far as you are providing right host_mor object.

**Comment by vspvijay** [comment]
Asonar,

Worked flawlessly. 

Used the below code,

search_index = si.content.searchIndex
host_mor = search_index.FindByIp(None,VSAN_HOST_IP_ADDRESS,False)
disks=host_mor.configManager.vsanSystem.QueryDisksForVsan()
disk_group =  host_mor.config.vsanHostConfig.storageInfo.diskMapping

Extracted disk information and the diskgroup information as my ESXi setup had VSAN cluster running. 

Thank you for your patience explaining every single step & detail. 

Cheers !

**Comment by vspvijay** [comment]
As my purpose got resolved, I would like to close this ticket with all due respect to the asonar & community.

Best Wises !
