### ISSUE TITLE
Modifying virtual machine custom attributes values using pyvmomi

### ISSUE THREAD

**Issue by arvindchandra** [vmware/pyvmomi-community-samples#284]
There is a thread which talks about creating virtual machine custom attributes https://communities.vmware.com/thread/474322?start=0&tstart=0.

I want to set/get the value of virtual machine custom attribute using pyvmomi.

For example:
We created custom attribute
Name : owner
Type : Virtual Machine

For virtual machine “myvm” I would like to

Set the Value to “Bob”
Get the Value
Update the Value to “Mike”
using pyvmomi

**Comment by Gerardwx** [comment]
See https://github.com/vmware/pyvmomi-community-samples/blob/master/samples/add_vm_extra_config_tags.py

**Comment by arvindchandra** [comment]
Actually we need follow these steps to get the value

f = si.content.customFieldsManager.field
for k, v in [(x.name, v.value) for x in f for v in vm.customValue if x.key == v.key]:
   print "Name: %s\nValue: %s" % (k, v)

**Comment by jovrum** [comment]
The above post illustrates how to read all custom fields and their values associated with a VM. To *write* a value for a custom field, one can use [vim.VirtualMachine.setCustomValue](https://vdc-download.vmware.com/vmwb-repository/dcr-public/6b586ed2-655c-49d9-9029-bc416323cb22/fa0b429a-a695-4c11-b7d2-2cbc284049dc/doc/vim.ExtensibleManagedObject.html#setCustomValue).
