### ISSUE TITLE
Install pyVmomi

### ISSUE THREAD

**Issue by jramacha** [vmware/pyvmomi-community-samples#294]
Hi, I am trying to install pyVmomi on a linux machine. I downloaded it from https://pypi.python.org/pypi/pyvmomi
 I downloaded and extracted the tar file. But when I run 
 python setup.py install
It fails

Traceback (most recent call last):
  File "setup.py", line 16, in <module>
    from setuptools import setup
ImportError: No module named setuptools

Thanks and appreciate.

**Comment by asonar** [comment]
Try : pip install setuptools and then continue installation.

**Comment by jramacha** [comment]
Thanks
