### ISSUE TITLE
list_datastore_info.py - Not discovering any datastores

### ISSUE THREAD

**Issue by naphta** [vmware/pyvmomi-community-samples#295]
Just get a list of hosts with empty dicts as below:

`
{
    "172.16.40.14": {},
    "172.16.40.28": {},
    "172.16.40.12": {},
    "172.16.40.10": {},
    "172.16.40.11": {},
    "172.16.40.24": {}
}
`

Any ideas?

**Comment by DanielDraganov** [comment]
This is 6+ year old and I guess it's outdated.
