### ISSUE TITLE
error while using upload_file_to_vm.py

### ISSUE THREAD

**Issue by jwed** [vmware/pyvmomi-community-samples#308]
Hi all,

I'm facing an error when I use upload_file_to_vm.py it's give me the following error:

Traceback (most recent call last):
File "upload_file_to_vm.py", line 126, in 
main()
File "upload_file_to_vm.py", line 92, in main
tools_status = vm.guest.toolsStatus
AttributeError: 'NoneType' object has no attribute 'guest'

and I checked in vSphere Client the status of the vmtool and it's status was:

VMware Tools: Running (Current).

so what is the problem and is any body used this sample before ??

Thank you

**Comment by asonar** [comment]
Looks like it didnt found vm... so in above case it appears to be None... just check your host and make sure you have same VM which you are using in above code.

**Comment by jwed** [comment]
thank you asonar for your response 

But I did some samples on the same VM and it work fine with me except this script show me the error.
Have you been tried this script before ..?!

**Comment by mindheist** [comment]
@jwed - Not sure if you are still looking for a solution for this problem. @asonar is right , we get that traceback only when the uuid is wrong and "None" is returned after searching for the VM.  This is fixed in pull request #444 .
