### ISSUE TITLE
execute_program_in_vm.py in windows VM

### ISSUE THREAD

**Issue by jwed** [vmware/pyvmomi-community-samples#310]
hello

I used this sample execute_program_in_vm.py on Windows VM and it's give me the following output 

`Program executed, PID is 2772`

but on the other side there is nothing happen, because I'm wating to execute my python file but my python file didn't show anything.

what is the problem and is this sample running on WIndows Vm ??

Thank you

**Comment by x1nas** [comment]
Program usually runs in background.
You can add _interactiveSession=True_ in _creds_:

```
creds = vim.vm.guest.NamePasswordAuthentication(
            username=args.vm_user,
            password=args.vm_pwd,
            interactiveSession=True
        )
```
But another problem - this program will run without admin rights.
And I don't know how to run a program as an administrator.

**Comment by SergeyZ11** [comment]
It doesn't work for me:
1) The result of such experiment:
`Caught vmodl fault : Failed to authenticate with the guest operating system using the supplied credentials.`
2) Looks like NamePasswordAuthentication() method does not support this key: [https://github.com/vmware/pyvmomi/blob/master/docs/vim/vm/guest/NamePasswordAuthentication.rst](url)

**Comment by x1nas** [comment]
It works in my environment.
interactiveSession inherited from GuestAuthentication - [link](https://pubs.vmware.com/vsphere-51/index.jsp?topic=%2Fcom.vmware.wssdk.apiref.doc%2Fvim.vm.guest.NamePasswordAuthentication.html)
[GuestAuthentication.rst](https://github.com/vmware/pyvmomi/blob/master/docs/vim/vm/guest/GuestAuthentication.rst)

**Comment by SergeyZ11** [comment]
You're right, works now.
But I met another problem. Despite I set interactiveSession=True, calc.exe starts in the 0-session instead of the current user session. Tested on .bat file - it was executed.

**Comment by vaidehi8goliwar** [comment]
if i include '\' in username , example admin\user, it is passing creds as username=admin\\user' which will give the same error, "Failed to authenticate with the guest operating system using the supplied credentials." can anyone help, how to pass only single slash.

**Comment by vaidehi8goliwar** [comment]
or any other ways to take credential from vm and pass it to authenticate creds.
