### ISSUE TITLE
Is there any way to create/upload files to the virtual machine?

### ISSUE THREAD

**Issue by phycool** [vmware/pyvmomi-community-samples#314]
Hi there

Is there any way to send files or run the command from the inside of the virtual machine? Requesting a sample code if possible.

Thanks a lot!
Anthony

**Comment by lamw** [comment]
Yes, this can all be done through the **Guest Operations** API. Have a look at this blog article here http://www.virtuallyghetto.com/2011/07/automating-new-integrated-vixguest.html which includes a working sample in Perl exercising the APIs which you can adapt to pyvmomi

**Comment by phycool** [comment]
@lamw 

Thank you so much for the reply.
