### ISSUE TITLE
Memory reservation setting

### ISSUE THREAD

**Issue by petericebear** [vmware/pyvmomi-community-samples#315]
Hi,

Does anyone know how to set the memory reservation setting?
Setting the memory and number of CPU's is found and working.

Greetings,
Peter

**Comment by lamw** [comment]
For memory reservation, you need to set the **[memoryAllocation](http://pubs.vmware.com/vsphere-65/index.jsp?topic=%2Fcom.vmware.wssdk.apiref.doc%2Fvim.ResourceAllocationInfo.html)** in your VM configSpec

**Comment by petericebear** [comment]
Does it need to be at the same level as the hardware setting of the memory?
Do you have an example?

**Comment by lamw** [comment]
Yes, its at the same level. Please refer to VM Config Spec for more details http://pubs.vmware.com/vsphere-65/index.jsp?topic=%2Fcom.vmware.wssdk.apiref.doc%2Fvim.vm.ConfigSpec.html
