### ISSUE TITLE
Looks like list_datastore_cluster.py does not work

### ISSUE THREAD

**Issue by kwoot** [vmware/pyvmomi-community-samples#321]
No errors, no output. Tested on vmware 5.5.

**Comment by prziborowski** [comment]
I don't have vCenter 5.5 handy to test with, but it is working fine for me with vCenter 6.5 and a ESXi 6.0 host.
Do you have any "datastore clusters" (in the API known as storage pod) in the vCenter to list?
I'll agree that it would be nice for it to report some error if it didn't find any datastore clusters.

**Comment by kwoot** [comment]
I see my error now. I have Clusters, I have Datastores, but I have 0 Datastore Clusters. My bad. Sorry.
