### ISSUE TITLE
Unable to connect to host with supplied info.

### ISSUE THREAD

**Issue by Shengjian** [vmware/pyvmomi-community-samples#327]
I want to delete a VM, and use command: python destroy_vm.py --host 10.192.70.77 --user root --port 443 --password ca$hc0w
But it returns Unable to connect to host with supplied info.
I can login the host by using the username and the password.

**Comment by prziborowski** [comment]
If you are running the command like that, then your password needs to be escaped or use single-quotes around it.
The dollar-sign will be interpreted as a variable.
