### ISSUE TITLE
How to create a datastore using a physical disk?

### ISSUE THREAD

**Issue by ruiruige** [vmware/pyvmomi-community-samples#329]
I have 30 disks in my machine.
I can add a single datastore from a single disk from the client.

I searched an example:

            dp = "/vmfs/devices/disks/naa.5000cca250e1519c"
            hostdssystem = esx_host.configManager.datastoreSystem
            dssystem = vim.host.DatastoreSystem
            vmfs_ds_options = dssystem.QueryVmfsDatastoreCreateOptions(
                                                       hostdssystem, dp, 5)
            if dsname is not None:
                vmfs_ds_options[0].spec.vmfs.volumeName = dsname

            new_ds = dssystem.CreateVmfsDatastore(hostdssystem,
                                                  vmfs_ds_options[0].spec)

However , I can not get the disk's UUID , so I can not run this example successfully,

So I think there may be 2 solutions for me:
1. find another way to `create a datastore using a physical disk`
2. use some functions to get many uuids of the disks , and the uuids must be from the unused disks.
I mean the uuid I get should not be the one which is related to an existing datastore

Who can help me , I really searched a lot but not found

![Uploading image.png…]()

**Comment by prziborowski** [comment]
Let me know if I've understood the piece you are missing.
It sounds like you just want help finding which disks are available to create a new VMFS with, so you can pass that to QueryVmfsDatastoreCreateOptions?

If so, you just need to call dssystem.QueryAvailableDisksForVmfs()
http://pubs.vmware.com/vsphere-65/index.jsp#com.vmware.wssdk.apiref.doc/vim.host.DatastoreSystem.html
```
QueryAvailableDisksForVmfs(queryAvailableDisksForVmfs)

Return Value
TYPE	DESCRIPTION
HostScsiDisk[]	An array of data objects describing SCSI disks.
```

So an example would be:
```
dssystem = esx_host.configManager.datastoreSystem
scsiDisks = dssystem.QueryAvailableDisksForVmfs()
dp = scsiDisks[0].devicePath # taking the first available disk for this example
vmfs_ds_options = dssystem.QueryVmfsDatastoreCreateOptions(devicePath=dp)
if dsname is not None:
    vmfs_ds_options[0].spec.vmfs.volumeName = dsname
new_ds = dssystem.CreateVmfsDatastore(spec=vmfs_ds_options[0].spec)
```

**Comment by ruiruige** [comment]
First of all , you are really smart , because you can clearly understand my meaning even my english is very poor.  

Second , I know there is a function `QueryVmfsDatastoreCreateOptions` , but it need an argument called `dp`,  this is what you said " I need help finding which disks are available to create a new VMFS with"

Now , you teach me an function called `QueryAvailableDisksForVmfs`  , this really helps .  
I tested your code just now, it succeed .  

Thanks a lot for your nice help . and I hope it will help others
