### ISSUE TITLE
Create new storage policy

### ISSUE THREAD

**Issue by smartyrahul** [vmware/pyvmomi-community-samples#330]
Wanted to know, if there is a way to create a new storage policy and then setting it to a datastore.

I wanted to do this for my vsan datastore. so that all vms which are created on vsan datastore should have that property.

**Comment by shyamachilles** [comment]
I too am looking for this. Any updates here ?

**Comment by shyamachilles** [comment]
@lamw , pls help

**Comment by lamw** [comment]
Support for [VM Storage Policies APIs](https://vdc-repo.vmware.com/vmwb-repository/dcr-public/7244190e-fa48-4c68-a600-69450c8722ef/0307f414-4e49-4c31-b8b4-43dc157797e9/doc/right-pane.html) was added to pyvmomi awhile back. Take a look at these samples ([here](https://github.com/vmware/pyvmomi-community-samples/blob/master/samples/list_vm_storage_policy.py) and [here](https://github.com/vmware/pyvmomi-community-samples/blob/master/samples/update_vm_storage_policy.py)) to give you an idea of how to use the API.

At high level, you'll want to use **[PbmCreate()](https://vdc-repo.vmware.com/vmwb-repository/dcr-public/7244190e-fa48-4c68-a600-69450c8722ef/0307f414-4e49-4c31-b8b4-43dc157797e9/doc/pbm.profile.ProfileManager.html#create)** to create a new Policy and for assigning the default VM Storage Policy to VSAN Datastore, you would use [**PbmAssignDefaultRequirementProfile()**](https://vdc-repo.vmware.com/vmwb-repository/dcr-public/7244190e-fa48-4c68-a600-69450c8722ef/0307f414-4e49-4c31-b8b4-43dc157797e9/doc/pbm.profile.ProfileManager.html#assignDefaultRequirementProfile)

**Comment by shyamachilles** [comment]
Thanks @lamw . Can we also PbmAssignDefaultRequirementProfile() for setting the default storage policy to a VVOL datastore as well.

**Comment by lamw** [comment]
Yes, that sounds like the right method. API Docs should have what you need :)
