### ISSUE TITLE
HostSystem instanceUuid is unset in vcenter? how can i Identify a HostSystem in vcenter?

### ISSUE THREAD

**Issue by lightjiao** [vmware/pyvmomi-community-samples#335]
```
(vim.AboutInfo) {
   dynamicType = <unset>,
   dynamicProperty = (vmodl.DynamicProperty) [],
   name = 'VMware ESXi',
   fullName = 'VMware ESXi 6.5.0 build-4564106',
   vendor = 'VMware, Inc.',
   version = '6.5.0',
   build = '4564106',
   localeVersion = 'INTL',
   localeBuild = '000',
   osType = 'vmnix-x86',
   productLineId = 'embeddedEsx',
   apiType = 'HostAgent',
   apiVersion = '6.5',
   instanceUuid = <unset>,
   licenseProductName = 'VMware ESX Server',
   licenseProductVersion = '6.0'
}
```
the HostSystem(esxi) about info ,the instanceUuid is unset, but i want to identify the host, how can i do.
what about the  hardware.systemInfo.uuid?  but i think it's not safe……

* my English is not very well, Thankyou

**Comment by prziborowski** [comment]
the about.instanceUuid is only populated for vCenter Server
[hardware.systemInfo](http://pubs.vmware.com/vsphere-65/index.jsp#com.vmware.wssdk.apiref.doc/vim.host.SystemInfo.html).uuid is going to be a BIOS identifier. I don't expect this to change or be duplicated (maybe unless you clone ESXi as a VM without changing the identifier).

You could also see if there are entries in hardware.systemInfo.otherIdentifyingInfo to identify that host.
I guess a question for you would be how would you like to identify a host? You could use other physical hardware information (like NIC's mac address) to identify a host if you expect its IP address or hostname will be changing.
