### ISSUE TITLE
How to list all folder in every datastore

### ISSUE THREAD

**Issue by rauzan92** [vmware/pyvmomi-community-samples#343]
Hi, I had a problem here, I want to list all folder in every my datastore and now I can listing my datastore but I don't know how to listing all folder in every datastore. Thanks

**Comment by prziborowski** [comment]
I'm not sure if there is a way to list all the folders in all the datastores in one call, but you can list all the folders in 1 datastore and loop for all the datastores.
You'd have to use the DatastoreBrowser which each datastore has.

```
from pyVim.task import WaitForTask

def print_results(searchResults):
   for result in searchResults:
      print results.folderPath
      for fileInfo in result.file:
         print "%s/%s" % (result.folderPath, fileInfo.path)

spec = vim.host.DatastoreBrowser.SearchSpec(query=[vim.host.DatastoreBrowser
.FolderQuery()])
for dc in si.content.rootFolder.childEntity:
   for ds in dc.datastore:
      task = ds.browser.SearchSubFolders("[%s]" % ds.name, spec)
      WaitForTask(task)
      print_results(task.info.result)
```

Just a minor note that the above can have some duplicate entries if you have nested folders. If that is a problem you could probably add it to a set and use the info after the datastore is processed.

**Comment by rauzan92** [comment]
That's work for me thanks man...

**Comment by magykjames** [comment]
Two issues:
1 - The variable name on line 3 of the print_results function above is incorrect. It should be "result" and not "results".
2 - If you issue this against a VSAN datastore, the task never finishes. It just gets stuck on "running" indefinitely.

**Comment by kofec** [comment]
Hi,
I have a few question regarding this topic:
How to find out what method are supported by "vim.host.DatastoreBrowser"
e.g SearchSpec() or Query()

How to add to .SearchSpec() - FileQueryFlags - 
https://vdc-repo.vmware.com/vmwb-repository/dcr-public/fe08899f-1eec-4d8d-b3bc-a6664c168c2c/7fdf97a1-4c0d-4be0-9d43-2ceebbc174d9/doc/vim.host.DatastoreBrowser.FileInfo.Details.html

I would like to have file size

Now I have w.g:
```
[storage01] aaa-001-vir//aaa-001-vir-0c486356.hlog
(vim.host.DatastoreBrowser.FileInfo) {
   dynamicType = <unset>,
   dynamicProperty = (vmodl.DynamicProperty) [],
   path = 'aaa-001-vir.vmx~',
   friendlyName = <unset>,
   fileSize = <unset>,
   modification = <unset>,
   owner = <unset>
```
Now I have:
`spec = vim.host.DatastoreBrowser.SearchSpec(query=[vim.host.DatastoreBrowser.Query()], details = [])`

**Comment by kofec** [comment]
Hi I found the solution here:
https://github.com/vmware/pyvmomi/issues/635
but still don't know how I should find that I should use:
vim.host.DatastoreBrowser.FileInfo.Details()

**Comment by prziborowski** [comment]
I think it would be (assuming spec is your vim.host.DatastoreBrowser.SearchSpec)
```
spec.details = vim.host.DatastoreBrowser.FileInfo.Details(
   fileOwner=True, fileSize=True, fileType=True, modification=True)
```
If that is what you want returned for specific details of the files.
I haven't tried it before, so let me know if that works.

**Comment by bonkeydcow** [comment]
The fileSize value returned for most files 100% accurate to the ui. However, vmdk files seem to not make sense. The UI shows my vmdk size as 42,062,848 KB, but FileInfo.fileSize = 640. Other files in the folder such as vmsd, vmx, or log files match exactly. Additionally, the list of files is not 1-1, the vmdk files have a file with the normal name and -flat version where the FileInfo.fileSize = the total size of the vmdk. Is there a way to get the accurate size on disk of the vmdk file?

**Comment by prziborowski** [comment]
I hope someone that has played around with this more can provide a more definitive answer.
Are the disks coming back as vim.host.DatastoreBrowser.VmDiskInfo type, or plain file vim.host.DatastoreBrowser.FileInfo?
If it is the former, then that is going to combine the metadata vmdk and -flat vmdk as one unit of information. If it is the latter it is returning it as if they are just files. The metadata file being small while -flat should list the actual consumption.

If I run the search with `spec.query = None`, then I get the results as vim.host.DatastoreBrowser.VmDiskInfo, which is likely how the UI shows it (at least that is what I see from ESXi host client). If I run with `spec.query = [vim.host.DatastoreBrowser.Query()]` as a previous commenter mentioned then I just see a file list.

**Comment by bonkeydcow** [comment]
Thanks for the response. I am using the code found in this item 

`            # spec = vim.host.DatastoreBrowser.SearchSpec(query=None)
            spec = vim.host.DatastoreBrowser.SearchSpec(query=[vim.host.DatastoreBrowser.Query()])
            spec.details = vim.host.DatastoreBrowser.FileInfo.Details(fileSize=True)
            # spec.query = None
`
If I run with the FolderQuery:
(vim.host.DatastoreBrowser.FolderInfo) {
   dynamicType = <unset>,
   dynamicProperty = (vmodl.DynamicProperty) [],
   path = 'FK_Jumphost',
   friendlyName = <unset>,
   fileSize = 3220,
   modification = <unset>,
   owner = <unset>
}
With Query:
(vim.host.DatastoreBrowser.FileInfo) {
   dynamicType = <unset>,
   dynamicProperty = (vmodl.DynamicProperty) [],
   path = 'FK_Jumphost-flat.vmdk',
   friendlyName = <unset>,
   fileSize = 107374182400,
   modification = <unset>,
   owner = <unset>
}
(vim.host.DatastoreBrowser.FileInfo) {
   dynamicType = <unset>,
   dynamicProperty = (vmodl.DynamicProperty) [],
   path = 'FK_Jumphost.vmdk',
   friendlyName = <unset>,
   fileSize = 641,
   modification = <unset>,
   owner = <unset>
}

UI: FK_Jumphost.vmdk  42,133,504 KB Virtual Disk
