### ISSUE TITLE
How do I get a virtual machine belonging to which host?

### ISSUE THREAD

**Issue by zhangjianpinghik** [vmware/pyvmomi-community-samples#344]

**Comment by prziborowski** [comment]
If you have a virtual machine object and want to know the host it is registered to, the property is in runtime.host:
e.g. ```print vm.runtime.host``` will print the id (you can print vm.runtime.host.name to get the name)

If you have a host system object and want to know the VMs running on it, you can get that from the vm property.
e.g. 
```
for vm in host.vm:
   print vm.name
```
will print all the names of the VMs on that host.

Is this what you are asking? If not, can you clarify further?

**Comment by zhangjianpinghik** [comment]
@prziborowski 
it works, thanks!
