### ISSUE TITLE
a error occured when i run the samples：“generate_html5_console.py”

### ISSUE THREAD

**Issue by zhangjianpinghik** [vmware/pyvmomi-community-samples#345]
vc_cert = ssl.get_server_certificate((self.host, int(self.port)))
  File "/usr/lib/python2.7/ssl.py", line 548, in get_server_certificate
    s.connect(addr)
  File "/usr/lib/python2.7/ssl.py", line 433, in connect
    self._real_connect(addr, False)
  File "/usr/lib/python2.7/ssl.py", line 423, in _real_connect
    self.do_handshake()
  File "/usr/lib/python2.7/ssl.py", line 405, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [Errno 8] _ssl.c:510: EOF occurred in violation of protocol

**Comment by tianhao64** [comment]
@zhangjianpinghik It looks like an error related to TLS 1.2. What's your openssl version? TLS 1.2 is only supported with openssl 1.0.1: https://docs.python.org/2/library/ssl.html

**Comment by zhangjianpinghik** [comment]
@tianhao64
the version of openssl installed in my ubuntu(14.04) server is OpenSSL 1.0.1f.

**Comment by zhangjianpinghik** [comment]
@tianhao64
i have resolved the SSLError, and generate the url like this:
http://10.45.58.18:7331/console/?vmId=vm-3058&vmName=win7_64_cn_ie8_dev_3&host=vCenter-Sever&sessionTicket=cst-VCT-521683ae-ed12-9a92-d252-a21f59885fa9--tp-35-8B-A4-53-EE-4D-F1-89-C1-03-26-91-C4-CF-78-15-57-CA-8B-3F&thumbprint=35:8B:A4:53:EE:4D:F1:89:C1:03:26:91:C4:CF:78:15:57:CA:8B:3F
 but when i opend the  url  in browser,  a message is appear：”The console has been disconnected. Close this window and re-launch the console to reconnect.”
i had tried more time， but  can not connected the vm succesfully!

**Comment by tianhao64** [comment]
Can you check if this KB helps?: https://kb.vmware.com/selfservice/microsites/search.do?language=en_US&cmd=displayKC&externalId=2116542

**Comment by DanielDraganov** [comment]
There is no response from the reporter and quite some time has passed. I'm closing this issue.
