### ISSUE TITLE
Basic question: Does anyone know how to disable SuppressShellWarning via pyvmomi?

### ISSUE THREAD

**Issue by donkerm** [vmware/pyvmomi-community-samples#346]
Hi all,

Does anyone know how to set values in UserVars using Pyvmomi?
Like UserVars.SuppressShellWarning.
I’m trying to suppress the Shell Warning via Pyvmomi and set the other values in UserVars.
I can retrieve the value by retrieving for example:
host.configManager.advancedOption.setting[876].value
This gives me the value 0 but I can’t set it to 1.
Does somebody know how to set the value?

I've found some samples online such as: http://mighty-virtualization.blogspot.de/2012_10_01_archive.html?m=0

But I don't know how to translate this into working code with Pyvmomi
Please help

Regards

**Comment by alanjcastonguay** [comment]
`host.configManager.advancedOption.UpdateOptions()` should do what you want; see https://github.com/vmware/pyvmomi/blob/master/docs/vim/option/OptionManager.rst

**Comment by donkerm** [comment]
Hi alanjcastonguay,

Thank you for your answer.
I found this answer also, but I don't know how to update the setting.
In a loop I can retrieve the values of SSH process and If the warning is suppressed

for host in (CLUSTER.host):
    HOST=host.name
    SERVICE=host.configManager.serviceSystem.serviceInfo.service[2].label
    RUNNING=host.configManager.serviceSystem.serviceInfo.service[2].running
    SUPRESSED=host.configManager.advancedOption.setting[876].value
    print(HOST,SERVICE,RUNNING, SUPRESSED)
connect.Disconnect(si)

Output:
server01 SSH FALSE 0 
server02 SSH FALSE 0 

But I can't get this suppressed to 1.

Regards

**Comment by donkerm** [comment]
I still have problems using Pyvmomi to disable the warning.

I found a solution via PHP:
var myVcOptionValue = new VcOptionValue() ;
myVcOptionValue.key="NFS.MaxVolumes";
myVcOptionValue.value_LongValue="256";
aoValues.push(myVcOptionValue);
oTargetHost.configManager.advancedOption.updateOptions(aoValues);  
 
Powershell:
Apparently the ‘value’ property needs to be declared as an int64 type.  By default, Powershell assumes the value to be a ‘string’ type.  Below is what will work:
$changedValue = New-Object VMware.Vim.OptionValue[] (1)
$changedValue[0] = New-Object VMware.Vim.OptionValue
$changedValue[0].key = "UserVars.CIMoemProviderEnabled"
[int64]$changedValue[0].value = 1
$_this = Get-View -Id 'OptionManager-EsxHostAdvSettings-00000'
$_this.UpdateOptions($changedValue)
 
I tried to make a dictionairy but this doesn’t work either.
 
shell = {}
shell['key'] = 'UserVars.SuppressShellWarning'
shell['value'] = 0
 
host.configManager.advancedOption.UpdateOptions(shell)

Does somebody have an idea to change the values using Python3/pyvmomi.

Regards..

**Comment by prziborowski** [comment]
I'll just point out yet another doc for [OptionManager](http://pubs.vmware.com/vsphere-65/index.jsp#com.vmware.wssdk.apiref.doc/vim.option.OptionManager.html).
It takes in a list of [OptionValue](http://pubs.vmware.com/vsphere-65/index.jsp?topic=%2Fcom.vmware.wssdk.apiref.doc%2Fvim.option.OptionValue.html) for the changed value.

So you could be able to do something like:
```
advOpt = host.configManager.advancedOption
opt = advOpt.QueryOptions('UserVars.SuppressShellWarning')
opt[0].value = 1L
advOpt.UpdateOptions(opt)
```

**Comment by donkerm** [comment]
Hi prziborowski, 

Thank you for helping me in the correct direction.
I tried this and still run into problems.

When I do run my command like this:

for host in (CLUSTER.host):
    advOpt = host.configManager.advancedOption
    opt = advOpt.QueryOptions('UserVars.SuppressShellWarning')
    print(opt[0])

I get the output:

(vim.option.OptionValue) {
   dynamicType = <unset>,
   dynamicProperty = (vmodl.DynamicProperty) [],
   key = 'UserVars.SuppressShellWarning',
   value = 0
}

When I do this:

for host in (CLUSTER.host):
    advOpt = host.configManager.advancedOption
    opt = advOpt.QueryOptions('UserVars.SuppressShellWarning')
    print(opt[0].value)

I get this back: 0

So Logically I want to do this as advised:

for host in (CLUSTER.host):
    advOpt = host.configManager.advancedOption
    opt = advOpt.QueryOptions('UserVars.SuppressShellWarning')
    opt[0].value = 1L
    advOpt.UpdateOptions(opt)

1L is invalid syntax

(Python 2 had separate types for int and long. The int datatype was limited by sys.maxint, which varied by platform but was usually 232-1. Python 3 has just one integer type, which behaves mostly like the old long type from Python 2. )

1 gives:
pyVmomi.VmomiSupport.InvalidArgument: (vmodl.fault.InvalidArgument) {
   dynamicType = <unset>,
   dynamicProperty = (vmodl.DynamicProperty) [],
   msg = 'A specified parameter was not correct. \n',
   faultCause = <unset>,
   faultMessage = (vmodl.LocalizableMessage) [],
   invalidProperty = <unset>
}

when I run:

for host in (CLUSTER.host):
    advOpt = host.configManager.advancedOption
    opt = advOpt.QueryOptions('UserVars.SuppressShellWarning')
    opt[0].value = 1
    print(opt)

(vim.option.OptionValue) [
   (vim.option.OptionValue) {
      dynamicType = <unset>,
      dynamicProperty = (vmodl.DynamicProperty) [],
      key = 'UserVars.SuppressShellWarning',
      value = 1
   }
]
So It looks ok but I can't do the advOpt.UpdateOptions(opt)

Regards

**Comment by prziborowski** [comment]
Sorry for my ignorance about the difference in handling between python 2 and 3 here.
I wonder if there is a way that pyVmomi can handle this better (@tianhao64)?

```
from pyVmomi import VmomiSupport
...
opt[0].value = VmomiSupport.vmodlTypes['long'](1)
...
advOpt.UpdateOptions(opt)
```

This seems to work for me when I try it on python3.

**Comment by tianhao64** [comment]
pyvmomi create the custom long type for python 3: https://github.com/vmware/pyvmomi/blob/master/pyVmomi/VmomiSupport.py#L1326
This type will be used to serialize/deserialize Long type in soap requests. 
@donkerm Can you try the code recommended by @prziborowski and see if it works for you?

**Comment by donkerm** [comment]
First of all...
I want to thank you guys for helping me.
The suggestion of  @prziborowski works!
The working code is:

for host in (CLUSTER.host):

    advOpt = host.configManager.advancedOption
    opt = advOpt.QueryOptions('UserVars.SuppressShellWarning')
    opt[0].value = VmomiSupport.vmodlTypes['long'](0)
    advOpt.UpdateOptions(opt)

Thank you for explaining that what I didn’t understand.
@tianhao64 Thank you for the information why I couldn't provision this.

**Comment by venkatanathen** [comment]
Hi Guys, 
I'm not sure if this is correct forum..Please assist..
I'm trying to deploy PaloAlto FW in an VMware using vmware_deploy_ovf.py using ansible
I'm getting the following error

TASK [Deploy the PaloAlto machine] ****************************************************************************************************
task path: /home/venkat/td-ansible-pa-vmware/deploy.yml:9
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: venkat
<127.0.0.1> EXEC /bin/sh -c 'echo ~venkat && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/venkat/.ansible/tmp/ansible-tmp-1538756713.23-235019968256463 `" && echo ansible-tmp-1538756713.23-235019968256463="` echo /home/venkat/.ansible/tmp/ansible-tmp-1538756713.23-235019968256463 `" ) && sleep 0'
Using module file /usr/lib/python2.7/site-packages/ansible/modules/cloud/vmware/vmware_deploy_ovf.py
<127.0.0.1> PUT /home/venkat/.ansible/tmp/ansible-local-24291tMajPD/tmp1qTxdI TO /home/venkat/.ansible/tmp/ansible-tmp-1538756713.23-235019968256463/AnsiballZ_vmware_deploy_ovf.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /home/venkat/.ansible/tmp/ansible-tmp-1538756713.23-235019968256463/ /home/venkat/.ansible/tmp/ansible-tmp-1538756713.23-235019968256463/AnsiballZ_vmware_deploy_ovf.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '/bin/python2.7 /home/venkat/.ansible/tmp/ansible-tmp-1538756713.23-235019968256463/AnsiballZ_vmware_deploy_ovf.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c 'rm -f -r /home/venkat/.ansible/tmp/ansible-tmp-1538756713.23-235019968256463/ > /dev/null 2>&1 && sleep 0'
fatal: [localhost]: FAILED! => {
    "changed": false,
    "module_stderr": "/usr/lib/python2.7/site-packages/requests/__init__.py:91: RequestsDependencyWarning: urllib3 (1.23) or chardet (2.2.1) doesn't match a supported version!\n  RequestsDependencyWarning)\nTraceback (most recent call last):\n  
File \"/home/venkat/.ansible/tmp/ansible-tmp-1538756713.23-235019968256463/AnsiballZ_vmware_deploy_ovf.py\", line 113, in <module>\n    _ansiballz_main()\n  
File \"/home/venkat/.ansible/tmp/ansible-tmp-1538756713.23-235019968256463/AnsiballZ_vmware_deploy_ovf.py\", line 105, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  
File \"/home/venkat/.ansible/tmp/ansible-tmp-1538756713.23-235019968256463/AnsiballZ_vmware_deploy_ovf.py\", line 48, in invoke_module\n    imp.load_module('__main__', mod, module, MOD_DESC)\n  
File \"/tmp/ansible_vmware_deploy_ovf_payload_Pc2bzI/__main__.py\", line 587, in <module>\n  
File \"/tmp/ansible_vmware_deploy_ovf_payload_Pc2bzI/__main__.py\", line 579, in main\n  
File \"/tmp/ansible_vmware_deploy_ovf_payload_Pc2bzI/__main__.py\", line 410, in upload\n  File \"/tmp/ansible_vmware_deploy_ovf_payload_Pc2bzI/__main__.py\", line 352, in get_lease\n  
File \"/usr/lib64/python2.7/site-packages/pyVmomi/VmomiSupport.py\", line 580, in <lambda>\n    self.f(*(self.args + (obj,) + args), **kwargs)\n  
File \"/usr/lib64/python2.7/site-packages/pyVmomi/VmomiSupport.py\", line 386, in _InvokeMethod\n    return self._stub.InvokeMethod(self, info, args)\n  
File \"/usr/lib64/python2.7/site-packages/pyVmomi/SoapAdapter.py\", line 1366, in InvokeMethod\n    raise obj # pylint: disable-msg=E0702\npyVmomi.VmomiSupport.NoPermission: (vim.fault.NoPermission) {\n   dynamicType = <unset>,\n   dynamicProperty = (vmodl.DynamicProperty) [],\n   msg = 'Permission to perform this operation was denied.',\n   faultCause = <unset>,\n   faultMessage = (vmodl.LocalizableMessage) [],\n   object = 'vim.ClusterComputeResource:domain-c88',\n   privilegeId = 'VApp.Import'\n}\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}
        to retry, use: --limit @/home/venkat/td-ansible-pa-vmware/deploy.retry
Any help is appreciated

Thanks,
VK

**Comment by prziborowski** [comment]
@venkatanathen I think your issue is unrelated to this one and would warrant its own entry.
That said, seems like "vim.fault.NoPermission" (Permission to perform this operation was denied) is a relevant part of the error. Does the user you are using have permissions to run ImportVapp against that cluster?

**Comment by venkatanathen** [comment]
Great help. 
Let me first check that.
Thanks,VK
    On Friday, October 5, 2018, 1:08:59 PM EDT, prziborowski <notifications@github.com> wrote:  
 
 
@venkatanathen I think your issue is unrelated to this one and would warrant its own entry.
That said, seems like "vim.fault.NoPermission" (Permission to perform this operation was denied) is a relevant part of the error. Does the user you are using have permissions to run ImportVapp against that cluster?

**Comment by venkatanathen** [comment]
Now, I'm getting the below error
   },    "msg": "Failure validating OVF import spec: The provided network mapping between OVF networks and the system network is not supported by any host."
Any idea..why
Thanks,VK
    On Friday, October 5, 2018, 1:08:59 PM EDT, prziborowski <notifications@github.com> wrote:  
 
 
@venkatanathen I think your issue is unrelated to this one and would warrant its own entry.
That said, seems like "vim.fault.NoPermission" (Permission to perform this operation was denied) is a relevant part of the error. Does the user you are using have permissions to run ImportVapp against that cluster?
