### ISSUE TITLE
How to remove HDD from virtual machine and delete files from disk with pyvmomi?

### ISSUE THREAD

**Issue by golendukhin** [vmware/pyvmomi-community-samples#352]
I tried code from delete_disk_from_vm.py, but got an error:
Cannot remove virtual disk from the virtual machine because it or one of its parent disks is part of a snapshot of the virtual machine.
How to avoid it?

**Comment by prziborowski** [comment]
Well, the error means that you can't remove the disk without first deleting the snapshot that is also referring to the disk.
The software doesn't seem to handle disks being detached after a snapshot includes the disk.
(avoid the error would mean deleting the snapshot. I'm not sure if that helps you though).

**Comment by golendukhin** [comment]
@prziborowski but vpshere client has this feature. I can remove disk without snapshot deletion and such errors.
![screenshot_24](https://cloud.githubusercontent.com/assets/16097794/25016398/76c5107c-2088-11e7-9b68-071a14ed66a7.png)

**Comment by prziborowski** [comment]
There are a couple differences between the UI and the sample.
If you are deleting the disk and not just detaching, it will work.
In the UI where you are selecting "and delete files from disk", it will work, but if you select just "Remove from virtual machine" then I'd expect you get the same error.

With the following diff, I'm able to have the sample work as well:
```
--- a/samples/delete_disk_from_vm.py
+++ b/samples/delete_disk_from_vm.py
@@ -44,6 +44,8 @@ def delete_virtual_disk(si, vm_obj, disk_number):
     virtual_hdd_spec = vim.vm.device.VirtualDeviceSpec()
     virtual_hdd_spec.operation = \
         vim.vm.device.VirtualDeviceSpec.Operation.remove
+    virtual_hdd_spec.fileOperation = \
+        vim.vm.device.VirtualDeviceSpec.FileOperation.destroy
     virtual_hdd_spec.device = virtual_hdd_device

     spec = vim.vm.ConfigSpec()
@@ -123,10 +125,10 @@ def main():

     if vm_obj:
         if not args.yes:
-            cli.prompt_y_n_question("Are you sure you want "
-                                    "to delete HDD "
-                                    "{}?".format(args.unitnumber),
-                                    default='no')
+            prompt_y_n_question("Are you sure you want "
+                                "to delete HDD "
+                                "{}?".format(args.unitnumber),
+                                default='no')
         delete_virtual_disk(si, vm_obj, args.unitnumber)
         print ('VM HDD "{}" successfully deleted.'.format(args.unitnumber))
     else:
```

**Comment by golendukhin** [comment]
@prziborowski thanks a lot!
