### ISSUE TITLE
Power on vm  task is not raising Exception

### ISSUE THREAD

**Issue by uganjha** [vmware/pyvmomi-community-samples#353]
Hi
To power on VM here is my code 

        serverVomi=connect.SmartConnect(host=ip,user='root',pwd=password)
        viewtype=[vim.VirtualMachine]
        content = serverVomi.RetrieveContent()
        container = content.rootFolder
        recursive = True
        containerView = content.viewManager.CreateContainerView(container, viewtype, recursive)
        children = containerView.view
        for child in children:
                logger.console("Powering on %s" %child)
                try:
                        child.PowerOnVM_Task()
                except vim.fault.InvalidState,e:
                        print "Fault %s" %e
                        logger.console("Failed to power on vm %s " %e)
                except vim.fault.InvalidPowerState,e:
                        print "Fault %s" %e
                        logger.console("Failed to power on vm %s" %e)
                except vmodl.fault.NotEnoughLicenses:
                        print "Fault %s" %e
                        logger.console("**WARN** Not Enough License **WARN** %s" %e)

Even though vm is already powered on this is not raising any exception.

Actually i want to catch Exception if License is not available but its not raising any Exception.
In vSphere Task manager i can see ERROR message but not in my code.

**Comment by asonar** [comment]
task=child.PowerOnVM_Task()

task.info() will give you more info about this particular task. If it fails with any error, you will see the same error in task.info as well.

**Comment by prziborowski** [comment]
asonar's answer is correct, but if you want to use exceptions like that, you should use pyVim.task.WaitForTask function

```
from pyVim.task import WaitForTask
...
try:
   WaitForTask(child.PowerOnVM_Task())
...
```

And then the rest of your code should work as-is.

**Comment by uganjha** [comment]
Thanks @prziborowski  .It works :)
