### ISSUE TITLE
How to list VMs info from a Specific Datacenter?

### ISSUE THREAD

**Issue by MartinCanovas** [vmware/pyvmomi-community-samples#355]
Hello,

The pyvmomi-community-samples/samples/vminfo_quick.py script is great, but it lists all the VMs in all datacenters.

If I want to add another argument for 'Datacenter' in order to filter only the VMs from a specific datacenter, how would I modify the script to accommodate that?

Thanks,
Martin

**Comment by prziborowski** [comment]
This part of the code:
```
view = pchelper.get_container_view(service_instance,
                                   obj_type=[vim.VirtualMachine])
```
by default (based on that function) will start from the rootFolder, so it includes everything.

If you can get the datacenter objection, you can pass that in as a third parameter:
```
view = pchelper.get_container_view(service_instance,
                                   obj_type=[vim.VirtualMachine], container=dc)
```

If you need to get the datacenter object and don't use datacenter folders, then you can search by name:
```
dc = None
for datacenter in service_instance.rootFolder.childEntity:
   if datacenter.name == datacenter_name:
      dc = datacenter
      break
if dc is None:
   raise Exception("Failed to find datacenter with name: %s" % datacenter_name)
```
(other sample files have more examples of adding in arguments to parse so you can pass in the datacenter name).

**Comment by MartinCanovas** [comment]
Our folder structure is something like this:

    -host
       -AM (folder)
             -NY (folder)
                       Datacenter-1
             -MIA (folder)
                       Datacenter-2
        -AP (folder)
              -SH (folder)
                      Datacenter-3

When I use:
for datacenter in service_instance.content.rootFolder.childEntity:

I'm only getting folders 'AM' and 'AP'. What I need is to get 'Datacenter-1', otherwise the for loop will list more VMs than I need.

How do I go down 2 levels to reach 'Datacenter-1'?

**Comment by prziborowski** [comment]
I was afraid you'd say something like that 😄 
You can do something similar to the filtering of VM, with datacenters.
```
dcView = pchelper.get_container_view(service_instance, obj_type=[vim.Datacenter])
for datacenter in dcView.view:
   if datacenter.name == datacenter_name:
      dc = datacenter
      break
dcView.Destroy() # clean up the allocation of the view
```

**Comment by MartinCanovas** [comment]
Yes! :smiley:
Thank you sir!
