### ISSUE TITLE
Getting IP Address and Notes from VMs?

### ISSUE THREAD

**Issue by MartinCanovas** [vmware/pyvmomi-community-samples#357]
Hello,

I'm running the  pyvmomi-community-samples/samples/vminfo_quick.py script, and I wonder if it's possible to add IP address and Notes in Annotations fields for each VM?

**Comment by prziborowski** [comment]
It is definitely possible:
```
vm_properties = ["name", "config.annotation", "config.uuid",
                 "config.hardware.numCPU",
                 "config.hardware.memoryMB", "guest.guestState",
                 "config.guestFullName", "config.guestId", "guest.ipAddress",
                 "config.version"]
```
...
```
for vm in vm_data:
    print("-" * 70)
    print("Name:                    {0}".format(vm["name"]))
    print("Annotation:              {0}".format(vm["config.annotation"]))
    print("BIOS UUID:               {0}".format(vm["config.uuid"]))
    print("CPUs:                    {0}".format(vm["config.hardware.numCPU"]))
    print("MemoryMB:                {0}".format(
        vm["config.hardware.memoryMB"]))
    print("Guest PowerState:        {0}".format(vm["guest.guestState"]))
    print("Guest Full Name:         {0}".format(vm["config.guestFullName"]))
    print("Guest IP Address:        {0}".format(
        "" if 'guest.ipAddress' not in vm else vm["guest.ipAddress"]))
    print("Guest Container Type:    {0}".format(vm["config.guestId"]))
    print("Container Version:       {0}".format(vm["config.version"]))
```

**Comment by MartinCanovas** [comment]
"It is definitely possible" is a good answer. :smiley:

I think the Annotation is a little trick. I ran the script with your suggestion, and it was working until it hit the first VM without annotation, then I got a traceback pointing to the line that prints "config.annotation".

I tried to add similar logic you used for the IP address in case 'annotation' is empty, but it didn't work.

**Comment by prziborowski** [comment]
From my experimenting, even though annotation is optional, it seems to always be set.
The only thing I can imagine happening (which would be true if the similar code to guest.ipAddress doesn't work) is the annotation has non-ascii characters.

Is the error you are getting a KeyError or something else?

If it is: ```UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-9: ordinal not in range(128)``` then you could make the string unicode:
```
    print(u"Annotation:              {0}".format(vm["config.annotation"]))
```
(which might have to be done for other values like 'name' if you have unicode in your name, etc)

**Comment by MartinCanovas** [comment]
I was first getting a KeyError for 2 VMs. Their notes were empty. I manually edited those, and another VM was giving the UnicodeEncodeError which was resolved by your solution.

Thanks again! This is great stuff.
