### ISSUE TITLE
timeout in deploy ova link or file path

### ISSUE THREAD

**Issue by harrydixo** [vmware/pyvmomi-community-samples#368]
Hello,

I have an issue on deploy a  ova and after five minute in vmware events its stoped and error opertation timed out.

How to increase the timed out?

How do it?

Thank you.

**Comment by CharmingYang0** [comment]
@YasinSanjari 
As [official document](https://pubs.vmware.com/vsphere-6-5/index.jsp) stated for **HttpNfcLeaseProgress** (see below), it must be invoked periodically to avoid lease timeout.

_Sets the disk up/download progress, and renews this lease. A lease will time out automatically after a while. If the client wishes to continue using it, for example if it is not done accessing the disks, this method must be called periodically._

```
from threading import Timer

def check_progress( )
    progress = get_progress( )
    lease.HttpNfcLeaseProgress(prog)

# Check progress each 5 seconds
Timer(5, check_progress).start( )
```
