### ISSUE TITLE
deploy_ova.py  support for python3.

### ISSUE THREAD

**Issue by talvezu** [vmware/pyvmomi-community-samples#375]
deploy_ova.py is working perfectly for me in python 2.7 but fails with
TypeError: a bytes-like object is required, not 'str' error in the line 206
self.tarfile = tarfile.open(fileobj=self.handle)

suggestions  for solving this are very welcome,
Thanks in advance to whoever respond.

**Comment by prziborowski** [comment]
Thank you for reporting this. I guess I didn't test with python3 (or at least not after doing refactoring).
Let me see if it is a trivial thing to fix.

**Comment by prziborowski** [comment]
There were a few differences I had to work through to have it behave properly for python3 (so I didn't test it at all before).
https://github.com/prziborowski/pyvmomi-community-samples/blob/master/samples/deploy_ova.py

**Comment by talvezu** [comment]
Thanks for your immediate response (:
Though python3 export the following error:
Hit an error in upload: Content-Length should be specified for iterable data of type <class 'tarfile.ExFileObject'> <ExFileObject name=None>

**Comment by prziborowski** [comment]
OK, I posted one more change.
If that doesn't resolve it, then I will probably need more details about your environment, such as the python version (e.g. 3.4) and OS (win/lin/mac) and maybe version of that.

**Comment by talvezu** [comment]
Thanks, works perfectly.
