### ISSUE TITLE
VM deployment from template : rename disks

### ISSUE THREAD

**Issue by Retenodus** [vmware/pyvmomi-community-samples#377]
Hello,

I'd like to be able to rename the disks filenames when I deploy a VM from a template. I guess that the right parameter to modify is backing.fileName (when I add a disk on a VM, that's what I change and it works) but I don't know how to modify it at vm creation.

I tried two approches:
* A relocate spec task
* A config spec task

Here, disks_platform_name is a list of strings which are the names I want to give to my disks.

```
...
        # Renaming disks
        list_template_disks = []

        for dev in template.config.hardware.device:
            if isinstance(dev, vim.vm.device.VirtualDisk):
                list_template_disks.append(dev)

        if len(list_template_disks) != len(disks_platform_name):
            print("Error with the disk naming")
            return {"task": constants.ERROR}


        list_locators = []
        for index, disk in enumerate(list_template_disks):
            locator = vim.vm.RelocateSpec.DiskLocator()
            locator.diskId = int(disk.key)
            locator.datastore = datastore
            locator.diskBackingInfo = disk.backing
            locator.diskBackingInfo.fileName = disks_platform_name[index]
            list_locators.append(locator)
        relospec.disk = list_locators
...
```
```
...
        # Renaming disks
        list_template_disks = []

        for dev in template.config.hardware.device:
            if isinstance(dev, vim.vm.device.VirtualDisk):
                list_template_disks.append(dev)

        if len(list_template_disks) != len(disks_platform_name):
            print("Error with the disk naming")
            return {"task": constants.ERROR}

        list_virtualdisk_spec = []

        for index, disk in enumerate(list_template_disks):
            disk_spec = vim.vm.device.VirtualDeviceSpec()
            disk_spec.fileOperation = "replace"
            disk_spec.operation = vim.vm.device.VirtualDeviceSpec.Operation.edit
            disk_spec.device = disk
            disk_spec.device.backing = vim.vm.device.VirtualDisk.FlatVer2BackingInfo()
            disk_spec.device.backing.fileName = disks_platform_name[index]
            list_virtualdisk_spec.append(disk_spec)

        relospec.deviceChange = list_virtualdisk_spec
...
```

In both cases, I get no error from VMWare, it's just that disks are not renamed. Did I miss something ? Is there a recommended way to specify the disks name at VM deployment ?

Thank you,
Regards,
Grégoire

**Comment by prziborowski** [comment]
Hi Grégoire,
Currently I don't think there is a way to rename the disks (neither through the relocateSpec, nor the configSpec).
Can I ask you what use-case you have for wanting to rename the disks from what they get named after deploying?

**Comment by Retenodus** [comment]
Hello,

I developped a vCenter controller and I use the name (whether it's VM name for VMs, disk name for disks, ...) as id for synchronization between the controller and vCenter. I'd like my controller to be the "source of truth" and make it decide alone of the name of each objects.

Should I use another parameter for that, like a settable id or something ?

Thank you,
Regards,
Grégoire

**Comment by prziborowski** [comment]
I'm not sure of a direct replacement for the filename in the context of tracking the files.
In vSphere 6.5, there is a vDiskid, but I haven't checked how exactly it works.

There is uuid property that you can set for disks, but if you have a disk chain, they will all have the same uuid.
There is a contentId, but you can't set it, and it changes whenever the disk content changes, so it wouldn't be something your controller could manage.

---
On the topic of VM, you should use config.instanceId as VM names can easily be duplicated, so it could become harder to track which is which.

**Comment by Retenodus** [comment]
Unfortunately, I am still using vSphere 6.0.
What do you mean a disk chain ? Several disks on the same VM ?

Thank you,
Regards,
Grégoire

**Comment by prziborowski** [comment]
Disk chain meaning the disk as the same object, most likely due to snapshots of the VM.
So you might have:
[datastore] samplevm/samplevm.vmdk
[datastore] samplevm/samplevm-000001.vmdk (parent is samplevm.vmdk)
[datastore] samplevm/samplevm-000002.vmdk (parent is samplevm-000001.vmdk)

All 3 disks are the same object, just with different contents (the children only containing newly written data from parent), so 'uuid' will be the same, but you might want to track the files separately.

**Comment by Retenodus** [comment]
Hello,

Well, chain disks won't be an issue for now, it's not a big deal if uuid are the same.

However, I don't find how to set the uuid at the vm deployment from template. Should it be in the backing attribute of a RelocateSpec or in ConfigSpec.deviceChanges ?

Regards,
Grégoire

**Comment by prziborowski** [comment]
It should go into the backing attribute of ConfigSpec.deviceChange.
[Slight disclaimer is that CloneSpec.config is deprecated with the recommendation to do a reconfigure operation after the clone, but at the moment it should work]
