### ISSUE TITLE
How can I fetch single vm by giving folder name

### ISSUE THREAD

**Issue by murarisumit** [vmware/pyvmomi-community-samples#379]
Is there any way to fetch vm's from give folder, instead of pulling all vm's in dc and then matching against the name ?

**Comment by prziborowski** [comment]
If you know the VM folder and can navigate to that, then you can use [SearchIndex](http://pubs.vmware.com/vsphere-65/index.jsp#com.vmware.wssdk.apiref.doc/vim.SearchIndex.html).FindChild(vmFolder, name)

SearchIndex is available from the [ServiceInstanceContent](http://pubs.vmware.com/vsphere-65/index.jsp#com.vmware.wssdk.apiref.doc/vim.ServiceInstanceContent.html).

A simple example would be:
```
vmName = 'test-vm'
dc = si.content.rootFolder.childEntity[0] # first datacenter
searchIndex = si.content.searchIndex
vm = searchIndex.FindChild(dc.vmFolder, vmName)
if vm is None:
   raise Exception("VM %s not found" % vmName)
```

**Comment by murarisumit** [comment]
Thanks @prziborowski  for answer, it helped me. 
I used searchIndex.FindByInventoryPath to find object at specific paths.
