### ISSUE TITLE
Way to create property collector from mor value

### ISSUE THREAD

**Issue by ekta-dakwala** [vmware/pyvmomi-community-samples#396]
Hi All,

I am creating property collector using method "CreatePropertyCollector()" for the first time.
I do create filter on property collector using "CreateFilter" method to fetch properties of specified object.
And i am getting proper data of inventory in my first run.
So at the end i store mor value of my property collector in cache file.
`mor = str(self.PropertyCollector._moId)`

Now after some interval, my script get executed again using same session.
This time i want to use mor value from my cache file and recreate property collector with that mor value. 
As this time i wanted to fetch only updates with next collection version using "WaitForUpdatesEx" method. So i have to use same property collector.

I can not directly assign mor value as _moId here, as its readonly property.

So is there any way to recreate same property collector using mor value?

Please help.

Thanks.

**Comment by prziborowski** [comment]
You can try to recreate the property collector as such:
from pyVmomi import vim
si = connect.SmartConnect(...)
...
pc = vim.PropertyCollector(mor, stub=si._stub)
