### ISSUE TITLE
How to enable nested Hypervisor using pyvmoni?

### ISSUE THREAD

**Issue by ruiruige** [vmware/pyvmomi-community-samples#397]
I want to select the last one, which is pointed by a red arrow.

Of course I can set it by clicking the checkbox, but I must use code to finish this job , because I have 1000+ vm to be set.

![image](https://user-images.githubusercontent.com/8370100/29010689-ac8a35f2-7b5f-11e7-88f3-1a70d93880f2.png)

Does anybody know how to do this?

**Comment by prziborowski** [comment]
I can't read what that option implies, so I am just taking a guess.
There are some CPU related flag in [vim.vm.FlagInfo](https://code.vmware.com/apis/196/vsphere#https%3A%2F%2Fvdc-repo.vmware.com%2Fvmwb-repository%2Fdcr-public%2F6b586ed2-655c-49d9-9029-bc416323cb22%2Ffa0b429a-a695-4c11-b7d2-2cbc284049dc%2Fdoc%2Fvim.vm.FlagInfo.html)#virtualExecUsage/virtualMmuUsage.
```
from pyVmomi import vim
from pyVim.task import WaitForTask
...
config = vim.vm.ConfigSpec()
config.flags = vim.vm.FlagInfo()
config.flags.virtualExecUsage = vim.vm.FlagInfo.VirtualExecUsage.hvOn
config.flags.virtualMmuUsage = vim.vm.FlagInfo.VirtualMmuUsage.on
WaitForTask(vm.Reconfigure(config)) # vm is the virtual machine object you want to reconfigure.
```

**Comment by ruiruige** [comment]
@prziborowski  thanks, I will try later.
The option is "to use inter VT-x/AMD-V  to do order sets virtualization and use Intel EPT/AMD RVI to do MMU virtualization"

**Comment by ruiruige** [comment]
settings are set successfully，thanks

**Comment by prziborowski** [comment]
Reading the subject of this issue makes me think what you want is:
```
from pyVmomi import vim
from pyVim.task import WaitForTask
...
config = vim.vm.ConfigSpec()
config.nestedHVEnabled = True
WaitForTask(vm.Reconfigure(config)) # vm is the virtual machine object you want to reconfigure.
```
But I guess you should try it on one VM and make sure it is doing what you expect for the guest OS. Then try on the rest.

**Comment by talvezu** [comment]
Thanks,
That help me too.
