### ISSUE TITLE
Is it possible to create(or clone) a VM from a specific snapshot of another VM?

### ISSUE THREAD

**Issue by rmdcoding** [vmware/pyvmomi-community-samples#401]
I want to create/clone a VM using a specific snapshot from another VM. I am able to create/clone from another VM and it uses the current snapshot of the template VM I am using. Is there anyway to choose which snapshot I want to use from the template?

**Comment by prziborowski** [comment]
There is a 'snapshot' property in the [vim.vm.CloneSpec()](https://code.vmware.com/apis/196/vsphere#https%3A%2F%2Fvdc-repo.vmware.com%2Fvmwb-repository%2Fdcr-public%2F6b586ed2-655c-49d9-9029-bc416323cb22%2Ffa0b429a-a695-4c11-b7d2-2cbc284049dc%2Fdoc%2Fvim.vm.CloneSpec.html) that is what you want pass in during the clone call.
You can navigate the snapshot try starting from the virtualmachine object's rootSnapshot ([Snapshot](https://code.vmware.com/apis/196/vsphere#https%3A%2F%2Fvdc-repo.vmware.com%2Fvmwb-repository%2Fdcr-public%2F6b586ed2-655c-49d9-9029-bc416323cb22%2Ffa0b429a-a695-4c11-b7d2-2cbc284049dc%2Fdoc%2Fvim.vm.Snapshot.html)[]) or snapshot([SnapshotInfo](https://code.vmware.com/apis/196/vsphere#https%3A%2F%2Fvdc-repo.vmware.com%2Fvmwb-repository%2Fdcr-public%2F6b586ed2-655c-49d9-9029-bc416323cb22%2Ffa0b429a-a695-4c11-b7d2-2cbc284049dc%2Fdoc%2Fvim.vm.SnapshotInfo.html)) parameter.

**Comment by rmdcoding** [comment]
Thanks, I will give that a shot.

**Comment by rmdcoding** [comment]
Tried it, tested it and it works now. Thanks again @prziborowski
