### ISSUE TITLE
How to put host into maintenence Mode 

### ISSUE THREAD

**Issue by mtawafig** [vmware/pyvmomi-community-samples#402]

**Comment by swamycnn** [comment]
If you create vm object, you can Power Down, pause, reset, Power on a vm.
Can you elaborate on maintenance Mode, you are mentioning about.
Are specific about some guest OS ?

**Comment by prziborowski** [comment]
With the [HostSystem](https://code.vmware.com/apis/196/vsphere#/doc/vim.HostSystem.html) object call the [enterMaintenanceMode](https://code.vmware.com/apis/196/vsphere#/doc/vim.HostSystem.html#enterMaintenanceMode) task and provide a timeout (in case DRS can not evacuate the VMs in that time, or in a non-DRS cluster/standalone host, the user does not manually migrate or power them off).
