### ISSUE TITLE
[help]how to get the vm IPdaaress belong to which net interface?

### ISSUE THREAD

**Issue by zhangjianpinghik** [vmware/pyvmomi-community-samples#404]

**Comment by prziborowski** [comment]
Can you clarify further the net interface you are looking for?
With the VirtualMachine object, the guest.net[].network property gives you the net interface, and guest.net[].ipConfig.ipAddress[].ipAddress is the ip address for that network.

([] is to imply it is an array to iterate. ipAddress would include the ipv4 and ipv6 addresses as separate entries).
