### ISSUE TITLE
getvmsbycluster.py error

### ISSUE THREAD

**Issue by fer040and** [vmware/pyvmomi-community-samples#407]
Hy, I have the following error running this script, only happen in one VCenter of our infraestructure:

$ python ./pyvmomi-community-samples-master/samples/getvmsbycluster.py -s pavcenterlm01.da.inf.sta -u <USER> -p <PASS>
Traceback (most recent call last):
  File "./pyvmomi-community-samples-master/samples/getvmsbycluster.py", line 152, in <module>
    main()
  File "./pyvmomi-community-samples-master/samples/getvmsbycluster.py", line 142, in main
    vm2dict(dc.name, cluster.name, hostname, vm, summary)
  File "./pyvmomi-community-samples-master/samples/getvmsbycluster.py", line 83, in vm2dict
    data[dc][cluster][host][vmname]['folder'] = vm.parent.name
AttributeError: 'NoneType' object has no attribute 'name'

Could you please help me or give me any workaround to solve this issue.
Thank you very much.
Fernando

**Comment by fer040and** [comment]
Hello, any suggestion about this issue?
Best regards

**Comment by prziborowski** [comment]
The error seems to imply that there is a VM on some host whose 'parent' property is returning None.
You may have to instrument the script to determine what VM this is, and what state it might be in such that it has no parent.

If I could take a guess, it is because the VM is inside a vApp.
You could try making the following code change:
```
-    data[dc][cluster][host][vmname]['folder'] = vm.parent.name
+    if vm.parent is not None:
+        data[dc][cluster][host][vmname]['folder'] = vm.parent.name
+    elif vm.parentVApp is not None:
+        data[dc][cluster][host][vmname]['folder'] = vm.parentVApp.name
```

**Comment by fer040and** [comment]
Excelent!, now the script ran and finish without errors.

Then, how I can check what VM have the problem?

Thank yoy very much!

Fernando

2017-08-28 10:55 GMT+02:00 prziborowski <notifications@github.com>:

**Comment by prziborowski** [comment]
You could add a print or something in the 'elif' condition.
Or you could alter what it stored for reporting such as:
```       data[dc][cluster][host][vmname]['folder'] = "vApp: " + vm.parentVApp.name```

**Comment by fer040and** [comment]
Ok, I was already trying a similar workaround and I found two VM without
folder.
Thanks a lot!

2017-08-28 11:59 GMT+02:00 prziborowski <notifications@github.com>:
