### ISSUE TITLE
How can I save the login session as a file in pyvmomi?

### ISSUE THREAD

**Issue by JioHooney** [vmware/pyvmomi-community-samples#412]
The problem I am having is that when I issue a command to the virtual machine, Always try to connect to vSphere is likely to cause a traffic load. So I try to save an existing session to a file and reuse it. What should I do?

**Comment by prziborowski** [comment]
https://github.com/vmware/pyvmomi/issues/537 had a similar issue.
If you persist the cookie and version of the connection to a file, you should be able to re-create a SoapStubAdapter based on that (assuming the cookie hasn't expired by the time you wish to use it).

**Comment by JioHooney** [comment]
@prziborowski 

Wow!
Thanks to you, the problem is solved.
👍
