### ISSUE TITLE
Set CDROM back to client device on existing VM

### ISSUE THREAD

**Issue by bmiller34** [vmware/pyvmomi-community-samples#413]
I am having an issue setting an existing cdrom with an ISO mounted back to client device. vSphere shows a reconfiguration attempt but it errors with invalid configuration for device '0'.  Is there a way to set an existing drive back to client device so that there is no longer an ISO mounted?

**Comment by prziborowski** [comment]
When I look at an existing VM of mine that is set to use a client device (I reconfigured from the UI),
it looks something like
```
device = vim.vm.device.VirtualCdrom()
device.backing = vim.vm.device.VirtualCdrom.RemoteAtapiBackingInfo(deviceName='', useAutoDetect=False)
device.connectable = vim.vm.device.VirtualDevice.ConnectInfo(startConnected=True, connected=False, allowGuestControl=True)
```
You could try doing a reconfigure with the above (setting the key as appropriate in your case) and seeing if that works.

**Comment by bmiller34** [comment]
device.backing = vim.vm.device.VirtualCdrom.RemoteAtapiBackingInfo(deviceName='', useAutoDetect=False)
    dev_changes = []
    dev_changes.append(device)
    spec = vim.vm.ConfigSpec()
    spec.deviceChange = dev_changes
    task = vm_obj.ReconfigVM_Task(spec=spec)
Thank you for the help!  Should I be using something other than deviceChange?  I keep receiving the below error.

    TypeError: For "deviceChange" expected type vim.vm.device.VirtualDeviceSpec, but got vim.vm.device.VirtualCdrom

**Comment by prziborowski** [comment]
Yes, you need to use a DeviceSpec, which includes the device as well as what change to do with the device (add/edit/remove).
```
device.backing = vim.vm.device.VirtualCdrom.RemoteAtapiBackingInfo(deviceName='', useAutoDetect=False)
dev_spec = vim.vm.device.VirtualDeviceSpec(device=device, operation='edit')
dev_changes = [dev_spec]
spec = vim.vm.ConfigSpec()
spec.deviceChange = dev_changes
task = vm_obj.ReconfigVM_Task(spec=spec)
```

**Comment by bmiller34** [comment]
THANK YOU!!!! That is the piece I was missing.
