### ISSUE TITLE
Checking to see if hot swap is enabled on cpu/mem

### ISSUE THREAD

**Issue by bmiller34** [vmware/pyvmomi-community-samples#423]
I am having trouble locating any info that shows whether or not 'Enable CPU Hot Add' and/or 'Memory Hot Plug' are enabled.  I have tried this (and variations) without success:
```
  spec = vim.vm.ConfigSpec()
  if (spec.cpuHotAddEnabled == True):
    print ("enabled")
```
I have also searched through vm.config.hardware and although I am able to see numCPU, memoryMB, etc, I do not see anything about hot swap.  Any help would be appreciated.

**Comment by prziborowski** [comment]
If you already have a VM with hot-swap enabled (possibly enabled in the UI, or previous API call), then you can check it with the config info:
```
if vm.config.cpuHotAddEnabled: # assuming 'vm' is an existing VM
   print "Enabled on %s" % vm.name
```

You can view some of the other samples that show how to get a ContainerView of VMs as that might be the easiest way to gather the VMs.

If you want to try enabling cpu hot-add on a VM, then you'll have to reconfigure it (and the guestOS has to be one that supports it).
```
from pyVim.task import WaitForTask
from pyVmomi import vim
...
spec = vim.vm.ConfigSpec(cpuHotAddEnabled=True)
WaitForTask(vm.Reconfigure(spec))
```
I'm pretty sure the VM has to be in a powered off state to make this change. And then after it is powered on, you should be able to set the numCPUs to a higher number
```
spec = vim.vm.ConfigSpec(numCPUs=vm.config.hardware.numCPU+1)
WaitForTask(vm.Reconfigure(spec))
```

**Comment by bmiller34** [comment]
Thank you for the quick help @prziborowski.  I tried some very similar syntax but missed it.  I read in another issue that changing cores per socket is not possible while the VM is powered on.  Do you know of any workaround for that?

**Comment by prziborowski** [comment]
I don't think there is a way to change cores per socket while the VM is powered on.
I'd think that is more of a technical problem with the underlying OS not supporting reconfiguring a 1-core socket into 2-core, etc while it is running.

**Comment by bmiller34** [comment]
Ok.  Thank you again for the help.
