### ISSUE TITLE
deviceName for USB Flash

### ISSUE THREAD

**Issue by x1nas** [vmware/pyvmomi-community-samples#425]
I try to connect USB Flash to VM with pyVmomi.

This code works fine:
```
spec = vim.vm.ConfigSpec()
spec.deviceChange = []
d = vim.vm.device.VirtualDeviceSpec()
d.operation = vim.vm.device.VirtualDeviceSpec.Operation.add
d.device = vim.vm.device.VirtualUSB()
d.device.deviceInfo = vim.Description()
d.device.backing = \
    vim.vm.device.VirtualUSB.USBBackingInfo()
d.device.backing.deviceName = 'path:0/2/0/1'
spec.deviceChange.append(d)
t = [vm.ReconfigVM_Task(spec=spec)]
```
My question is how can I get deviceName ('path:x/x/x/x') for another USB Flash?

**Comment by x1nas** [comment]
Found a workaround without path:
```
d.device.backing.deviceName = 'vid:8644 pid:800b'
```

**Comment by zhangjianpinghik** [comment]
@x1nas are you resoved you issues? i konwn the use QueryConfigTarget ? but i do not how to use it

**Comment by x1nas** [comment]
@zhangjianpinghik Don't know how to find "path" with API - I connected USB Flash manually and got information from GUI.
With pid&vid for deviceName two or three wrong devices will be connected.

**Comment by zhangjianpinghik** [comment]
@x1nas  i resolved it ,frist, you need to get a ComputerResouce instance,the do like this to get all usb devices in the host:
computer_resource.environmentBrowser.QueryConfigTarget(host).usb

**Comment by x1nas** [comment]
@zhangjianpinghik, thanks a lot!
On my single esxi host with single USB it will be something like this:

```
content = si.RetrieveContent()
container = content.viewManager.CreateContainerView(
    content.rootFolder, [vim.HostSystem], True)
host = container.view[0]
container = content.viewManager.CreateContainerView(
    content.rootFolder, [vim.ComputeResource], True)
cr = container.view[0]
print cr.environmentBrowser.QueryConfigTarget(host).usb[0].physicalPath
```

**Comment by zhangjianpinghik** [comment]
@x1nas  do you revoled how to add softdog to vm by redirect i/o using pyvimomi?

**Comment by x1nas** [comment]
> how to add softdog to vm by redirect i/o

What do you mean?
