### ISSUE TITLE
Error in list_vm_storage_policy.py

### ISSUE THREAD

**Issue by ajaytho** [vmware/pyvmomi-community-samples#432]
I executed some of scripts and works perfect but I am not able to execute this script. It errors out. I am looking for a way to find storage path policy for each disk of VM. Suppose VM has 3 disk from 3 different datastore then I want to find the storage path policy corresponding to each vmdk

`C:\vmware-pyvmomi\samples>list_vm_storage_policy.py -s myesxihostip -u root -p ******
Traceback (most recent call last):
  File "C:\vmware-pyvmomi\samples\list_vm_storage_policy.py", line 123, in <module>
    main()
  File "C:\vmware-pyvmomi\samples\list_vm_storage_policy.py", line 97, in main
    pbmSi, pbmContent = GetPbmConnection(si._stub)
  File "C:\vmware-pyvmomi\samples\list_vm_storage_policy.py", line 43, in GetPbmConnection
    pbmContent = pbmSi.RetrieveContent()
  File "C:\Python27\lib\site-packages\pyVmomi\VmomiSupport.py", line 580, in <lambda>
    self.f(*(self.args + (obj,) + args), **kwargs)
  File "C:\Python27\lib\site-packages\pyVmomi\VmomiSupport.py", line 386, in _InvokeMethod
    return self._stub.InvokeMethod(self, info, args)
  File "C:\Python27\lib\site-packages\pyVmomi\SoapAdapter.py", line 1369, in InvokeMethod
    raise http_client.HTTPException("{0} {1}".format(resp.status, resp.reason))
httplib.HTTPException: 400 Bad Request`

**Comment by prziborowski** [comment]
I believe you need to connect to the vCenter Server rather than your ESXi host.
It uses that IP address to connect to the SPBM API endpoint, which only exists on vCenter server.

**Comment by ajaytho** [comment]
If this needs vCenter then can this script be tweaked to work on esxi to find storage path policy ? OR is there any other script available for this task ?
Thanks for help.

**Comment by prziborowski** [comment]
I'm not very knowledgable about storage policies and what exactly is available at the ESXi level.
But from what I can see from the [DefinedProfileSpec](https://code.vmware.com/apis/196/vsphere#/doc/vim.vm.DefinedProfileSpec.html),
```
Neither the association nor the policy data is persisted in Virtual Machine configuration. 
This data is managed by the an extension of Virtual Center (Storage Policy Based Management).
```
This seems to imply it isn't available at that level.

**Comment by ajaytho** [comment]
I am looking for MultipathPolicy like "Fixed"/ "Round Robin" etc for each vmdk-->datastore-->disk-->MultipathPolicy

**Comment by ajaytho** [comment]
Basically I am looking to convert following power shell code to python
`
$dslist = Get-VM "testvm" |Get-HardDisk|select name, filename
forEach ( $ds in $dslist ) {
    $harddiskname = $ds.name
    $harddisk_ds = ($ds.filename -split "]")[0].substring(1)
    $objDataStore = get-datastore -name $harddisk_ds
    $objDataStoreView = Get-View -id $objDataStore.id
    $naa = $objDataStoreView.info.vmfs.Extent.DiskName
    $storagePolicyObj = Get-VMhost "myesxhost" |Get-ScsiLun -LunType disk -canonicalName $naa
    $storagePolicy = $storagePolicyObj.MultipathPolicy
    
    echo ("{0,-45} {1,-55}" -f "$harddiskname", $storagePolicy)
}
`

**Comment by prziborowski** [comment]
I don't know if I can give a 1 to 1 conversion of that, but seems like:
```
vm = get_obj(si.content, [vim.VirtualMachine], "testvm") # lots of samples have get_obj function
for dev in vm.config.hardware.device:
   if not isinstance(dev, vim.vm.device.VirtualDisk) or not isinstance(dev.backing, vim.vm.device.VirtualFileBacking):
      continue # If it isn't a file backing, then it likely isn't on a datastore we can reference
   ds = dev.backing.datastore
   naa = ds.info.vmfs.extend.diskName
   host = vm.runtime.host
   storageDeviceInfo = host.configManager.storageSystem.storageDeviceInfo
   luns = storageDeviceInfo.multipathInfo.lun
   policies = [x.policy for x in luns if x.lun.lunType == "disk" and x.lun.canonicalName == naa]
   for policy in policies:
      print("Disk %s, policy %s" % (dev.backing.fileName, policy)
```

I haven't tested this, but it should link the pieces between the VM and the host's scsi disks.

**Comment by ajaytho** [comment]
Thanks for code sample/help. 
Following line does not work
` policies = [x.policy for x in luns if x.lun.lunType == "disk" and x.lun.canonicalName == naa]`
AttributeError: 'Link' object has no attribute 'lunType'
Is there any other way to find if the luntype is "disk" and be part of this code?

**Comment by ajaytho** [comment]
Also there is no x.lun.canonicalName
sample print of luns = storageDeviceInfo.multipathInfo.lun
        print(luns)
`(vim.host.MultipathInfo.LogicalUnit) [
   (vim.host.MultipathInfo.LogicalUnit) {
      dynamicType = <unset>,
      dynamicProperty = (vmodl.DynamicProperty) [],
      key = 'key-vim.host.MultipathInfo.LogicalUnit-0000000000766d686261313a303a30',
      id = '0000000000766d686261313a303a30',
      lun = u'key-vim.host.ScsiDisk-0000000000766d686261313a303a30',
      path = (vim.host.MultipathInfo.Path) [
         (vim.host.MultipathInfo.Path) {
            dynamicType = <unset>,
            dynamicProperty = (vmodl.DynamicProperty) [],
            key = 'key-vim.host.MultipathInfo.Path-vmhba1:C0:T0:L0',
            name = 'vmhba1:C0:T0:L0',
            pathState = 'active',
            state = 'active',
            isWorkingPath = true,
            adapter = u'key-vim.host.ParallelScsiHba-vmhba1',
            lun = u'key-vim.host.MultipathInfo.LogicalUnit-0000000000766d686261313a303a30',
            transport = (vim.host.ParallelScsiTargetTransport) {
               dynamicType = <unset>,
               dynamicProperty = (vmodl.DynamicProperty) []
            }
         }
      ],
      policy = (vim.host.MultipathInfo.LogicalUnitPolicy) {
         dynamicType = <unset>,
         dynamicProperty = (vmodl.DynamicProperty) [],
         policy = 'VMW_PSP_RR'
      },
      storageArrayTypePolicy = (vim.host.MultipathInfo.LogicalUnitStorageArrayTypePolicy) {
         dynamicType = <unset>,
         dynamicProperty = (vmodl.DynamicProperty) [],
         policy = 'VMW_SATP_LOCAL'
      }
   },
   (vim.host.MultipathInfo.LogicalUnit) {
      dynamicType = <unset>,
      dynamicProperty = (vmodl.DynamicProperty) [],
      key = 'key-vim.host.MultipathInfo.LogicalUnit-0005000000766d68626133323a303a30',
      id = '0005000000766d68626133323a303a30',
      lun = u'key-vim.host.ScsiLun-0005000000766d68626133323a303a30',
      path = (vim.host.MultipathInfo.Path) [
         (vim.host.MultipathInfo.Path) {
            dynamicType = <unset>,
            dynamicProperty = (vmodl.DynamicProperty) [],
            key = 'key-vim.host.MultipathInfo.Path-vmhba32:C0:T0:L0',
            name = 'vmhba32:C0:T0:L0',
            pathState = 'active',
            state = 'active',
            isWorkingPath = true,
            adapter = u'key-vim.host.BlockHba-vmhba32',
            lun = u'key-vim.host.MultipathInfo.LogicalUnit-0005000000766d68626133323a303a30',
            transport = (vim.host.BlockAdapterTargetTransport) {
               dynamicType = <unset>,
               dynamicProperty = (vmodl.DynamicProperty) []
            }
         }
      ],
      policy = (vim.host.MultipathInfo.FixedLogicalUnitPolicy) {
         dynamicType = <unset>,
         dynamicProperty = (vmodl.DynamicProperty) [],
         policy = 'VMW_PSP_FIXED',
         prefer = 'vmhba32:C0:T0:L0'
      },
      storageArrayTypePolicy = (vim.host.MultipathInfo.LogicalUnitStorageArrayTypePolicy) {
         dynamicType = <unset>,
         dynamicProperty = (vmodl.DynamicProperty) [],
         policy = 'VMW_SATP_LOCAL'
      }
   }
]`

**Comment by prziborowski** [comment]
Sorry, I did not realize that the multipath lun array was a link type, meaning just a bunch of keys that need to be associated from the scsiLun data.
I've updated my example above and did some trivial testing as I noticed a few issues with it besides the 'Link' object part.

The composition line was getting unwieldy, so I broke that into a couple helper functions to call.
