### ISSUE TITLE
Moving a VM inside a vApp

### ISSUE THREAD

**Issue by cyrbi** [vmware/pyvmomi-community-samples#436]
Hello,

Is there an example of moving a VM inside of a vApp ? I'm trying to do it but I absolutely don't know how to do it and I don't see any example on the web.

(sorry for the newby post but I feel so lost about it)

**Comment by prziborowski** [comment]
a vApp ([VirtualApp](https://code.vmware.com/apis/196/vsphere#/doc/vim.VirtualApp.html)) extends a ResourcePool object.
One of the methods of a ResourcePool is [moveInto](https://code.vmware.com/apis/196/vsphere#/doc/vim.ResourcePool.html#moveInto).
"Moves a set of resource pools, vApps or virtual machines into this pool. The pools, vApps and virtual machines must be part of the cluster or standalone host that contains this pool."

So if you have your vapp object, and vm object, then you should be able to do:
`vapp.MoveInto([vm])`

**Comment by cyrbi** [comment]
Thank you for the information !

So I've made a script thanks to this information. It can be seen here.

https://github.com/cyrbi/python_examples/blob/master/move_vm_to_vapp.py
