### ISSUE TITLE
does pyvmomi require root access ??

### ISSUE THREAD

**Issue by amoghmahesh** [vmware/pyvmomi-community-samples#438]
this program executed with root and it password. but it does not execute when I give the username as argument.

May I know why?

ThankYou

**Comment by mindheist** [comment]
Hi @amoghmahesh - which one of the sample scripts did you run ? Can you paste the python traceback and the CLI command you executed ?

**Comment by amoghmahesh** [comment]
my password had " ! ".. 
so i had to back slash it.. now its working 
thank you
