### ISSUE TITLE
Collect performance data of ESXi host and virtual machine

### ISSUE THREAD

**Issue by hongshaowei** [vmware/pyvmomi-community-samples#447]
Can anyone give some hint for collect performance data like cpu and memory?
I checked the esxi_perf_sample.py, but i don't understand what the output is....
I thought it would be something like "CPU Usage" or "Memory Usage"?

**Comment by Andy4081** [comment]
Please check out this link - https://virtualwires.wordpress.com/2016/07/25/using-pyvmomi-to-collect-esxi-info/ 
I ran it in my lab and it works fine!
Good luck!
