### ISSUE TITLE
Adding VirtualSerialPort to existing VM

### ISSUE THREAD

**Issue by bmiller34** [vmware/pyvmomi-community-samples#449]
I am having trouble adding a serial port to an existing VM.  The code below seems to work since the port shows up in vm.config.hardware.device.  The issue occurs when I start the VM up and the connectable status shows 'unrecoverableError'.   I have tried several values for backing.serviceURI mostly from (https://www.vmware.com/support/developer/converter-sdk/conv50_apireference/vim.vm.device.VirtualSerialPort.URIBackingInfo.html) without success.

code:

```
def add_port(vm):
  spec = vim.vm.ConfigSpec()
  spec.deviceChange = []
  serial_spec = vim.vm.device.VirtualDeviceSpec()
  serial_spec.operation = 'add'
  serial_port = vim.vm.device.VirtualSerialPort()
  serial_port.yieldOnPoll = True
  backing = serial_port.URIBackingInfo()
  backing.serviceURI = 'tcp://5000'
  backing.direction = 'server'
  serial_port.backing = backing
  serial_spec.device = serial_port
  spec.deviceChange.append(serial_spec)
  vm.ReconfigVM_Task(spec=spec)
```
Then the device shows up in devices looking fine until the VM is booted.

After starting:
```
   connectable = (vim.vm.device.VirtualDevice.ConnectInfo) {
      dynamicType = <unset>,
      dynamicProperty = (vmodl.DynamicProperty) [],
      startConnected = true,
      allowGuestControl = true,
      connected = false,
      status = 'unrecoverableError'
```

Any help would be appreciated.  Thank you.

**Comment by prziborowski** [comment]
Try adding a : before the port number.
E.g.:
```backing.serviceURI = 'tcp://:5000'```
I think that is needed to distinguish from `host "5000"` to mean `port "5000" with no host restriction`

**Comment by bmiller34** [comment]
That was it!
```
   connectable = (vim.vm.device.VirtualDevice.ConnectInfo) {
      dynamicType = <unset>,
      dynamicProperty = (vmodl.DynamicProperty) [],
      startConnected = true,
      allowGuestControl = true,
      connected = true,
      status = 'ok'
   }
```
Thank you for your prompt replies and knowledge.  I have also tried with telnet://:127.0.0.1:5000 and although the status is ok, lsof -i does not show anything on port 5000.  Does telnet need to be reconfigured?

**Comment by prziborowski** [comment]
I've never tried telnet before and honestly I've never tried specifying a host/IP.
Do you have `telnet://:127.0.0.1:5000` and not `telnet://127.0.0.1:5000`?
Also does `telnet://:5000` work?

**Comment by bmiller34** [comment]
I was just using telnet because it seemed like an easy way to test the connection out.  I had this and it did not work:
```
serviceURI = 'telnet://:127.0.0.1:5000'
```
I also tried this with the same results:
```
serviceURI = 'telnet://:5000'
```
After a little more digging (https://kb.vmware.com/s/article/2004954) it almost looks like I need to do something like this:
```
serviceURI = 'telnet://:ESXIHostIP:5000'
```
Use the esx host that the VM is on.  I couldn't get that to work either but should have access to the firewall soon so I can rule that out as a problem.

Thank you again for all of your help.  If you have any other ideas please let me know.

**Comment by prziborowski** [comment]
Opening up the firewall will definitely be necessary.
I believe "VM serial port connected over network" is the rule (which opens a lot of ports ☹️ ).
I've been able to use 'tcp://:5000' in the past and telnet to the ESX host at that port and have it work (after opening the firewall).

**Comment by rmdcoding** [comment]
Has there been any update to this yet? About to try something similar but wanted to know if there are any other issues I should look out for.

**Comment by rmdcoding** [comment]
Update: I was able to get a serial connection working. I did have to modify the firewall settings to allow Virtual Serial Ports over Network. As for the ``` serviceURI``` It will need to be like this: 
``` serviceURI = 'telnet://ESXIHostIP:5000' ```

You will also have to make sure that the kernel is using the serial ports. (i.e on the pre-boot console line ``` console=ttyS0,1152000```)
