### ISSUE TITLE
Dick Capacity Info is not always true

### ISSUE THREAD

**Issue by mabazyar** [vmware/pyvmomi-community-samples#454]
Consider the situation, we have used the following method to retrieve the disk information from the remote vCenter:

diskInfo = summary.vm.guest.disk

It returns a list of dicts contains, as part of the information, the disk capacity, whereas it considerably is different from what we see in vCenter.

Take, for example, upon the vCenter the disk capacity is 80GB, although the method returns 72GB.

**Comment by mabazyar** [comment]
Any thoughts? guys?

**Comment by prziborowski** [comment]
That data will be what is reported by the guest (via vmware-tools).
It also appears to be reporting the partitions and not the raw disk, so some space will be lost in file system overhead (although that appears to be 9%, which is higher than I'd expect).

**Comment by mabazyar** [comment]
Thanks @prziborowski . How can I retrieve the raw disk though?

**Comment by prziborowski** [comment]
You'd want to iterate through vm.config.hardware.device looking at the VirtualDisk type and capacityInBytes property.
e.g.:
```
for dev in vm.config.hardware.device:
   if isinstance(dev, vim.vm.device.VirtualDisk):
      print("%s %d" % (dev.deviceInfo.label , dev.capacityInBytes))
```

**Comment by mabazyar** [comment]
Thanks for the instant reply.
I will just give it a try and let you know the output.

**Comment by mabazyar** [comment]
It works like a dream. Really appreciate that @prziborowski .
Have merely made a tiny amendment to the code to get rid of None type stuff on dev.capacityInBytes, like so:
```
for dev in vm.config.hardware.device:
     if isinstance(dev, vim.vm.device.VirtualDisk):
        rawDisk = int(0 if dev.capacityInBytes is None else dev.capacityInBytes)
        print("%s %d" % (dev.deviceInfo.label , rawDisk))
```
