### ISSUE TITLE
Possible to modify vram size?

### ISSUE THREAD

**Issue by kouellette** [vmware/pyvmomi-community-samples#459]
I have a vm in virtualbox that has a vram size of 32MB. When converting to vmware with deploy_ova.py the vram value is ignored in the ovf and the vm is defaulted to 4MB. Is there a way to set this value while deploying or is there a script I can use to modify this value after it has been deployed?

Thanks!

**Comment by prziborowski** [comment]
You could modify the deploy_ova.py script to set the memory size before it creates the VM.

Something like:
```
@@ -45,6 +46,8 @@ def setup_args():
     parser.add_argument('-ds', '--datastore',
                         help='Name of datastore to use. '
                              'Defaults to largest free space in datacenter.')
+    parser.add_argument('-m', '--memory',
+                        help='Override memory in MB to set for VM.)
     return cli.prompt_for_password(parser.parse_args())
```

```
@@ -94,6 +97,9 @@ def main():
             print("%s" % error)
         return 1

+    if args.memory and isinstance(cisr.importSpec, vim.vm.VmImportSpec):
+       cisr.importSpec.configSpec.memoryMB = args.memory
+
     ovf_handle.set_spec(cisr)

     lease = rp.ImportVApp(cisr.importSpec, dc.vmFolder)
```
I haven't tested this, but that is basically the idea to set the ConfigSpec value after it is generated from the OVF descriptor but before creating the VM.

**Comment by kouellette** [comment]
Thanks for the reply. That does work to modify RAM however I am looking to modify Video RAM.

**Comment by prziborowski** [comment]
Sorry, when I read vRAM I think virtual RAM.
That is a bit more complicated change and I'm not sure if I can write it out without any typos :grin:.
```
    if args.memory and isinstance(cisr.importSpec, vim.vm.VmImportSpec):
        for devSpec in cisr.importSpec.configSpec.deviceChange:
            if isinstance(devSpec.device, vim.vm.device.VirtualVideoCard):
                devSpec.device.videoRamSizeInKB = args.memory * 1024
                break
        else:
            devSpec = vim.vm.device.VirtualDeviceSpec(operation="add")
            devSpec.device = vim.vm.device.VirtualVideoCard(videoRamSizeInKB=args.memory * 1024)
            devSpec.device.unitNumber = -1
            devSpec.device.connectable = vim.vm.device.VirtualDevice.ConnectInfo(startConnected=True, allowGuestControl=False, connected=True)
            cisr.importSpec.configSpec.deviceChange.append(devSpec)
```

**Comment by kouellette** [comment]
No problem, I should have been more clear. Only had to make a couple tweaks but she works! Thanks for the help I really appreciate it!
