### ISSUE TITLE
How to get MangedEntity objects for hosts inside cluster using pyVmomi ?

### ISSUE THREAD

**Issue by vThinkBeyondVM** [vmware/pyvmomi-community-samples#463]
Hi Experts,

 I would like to call "AddMonitoredEntities()" method (which is exposed by http://pubs.vmware.com/vsphere-6-5/index.jsp?topic=%2Fcom.vmware.wssdk.apiref.doc%2Fvim.HealthUpdateManager.html)

This method accepts hosts from clusters as monitoredEntites. I am able to get "ManagedObject" for hosts but could not figure out yet how to convert or get hosts "managedEntity" instead?

 I was able to do using Java SDK though. I will try further using pyVmomi. 
Any help/guideline/snippet on this would be useful.

**Comment by prziborowski** [comment]
When you can try to do in the case you have a list that is explicitly 1 type, e.g.
```
>>> objs
(ManagedObject) []
```
is using the <typename>.Array() function to convert it.
Using the above object
```
>>> vim.ManagedEntity.Array(objs)
(vim.ManagedEntity) []
```
Obviously you'd have a non-empty list, but it should work.
