### ISSUE TITLE
Issues Installing the required Python Packages

### ISSUE THREAD

**Issue by climbtech** [vmware/pyvmomi-community-samples#469]
I am trying to setup the python environment (on a linux host), and am getting close.  Trying to figure how to get past this error, after running: 

python3 ../samples/vsphere/vcenter/setup/main.py -h

(I forced it to python3 after getting several pyVim messages pointing specifically to python 2.7 directories, which got it down to a single module import error, below)

Traceback (most recent call last):
  File "samples/vsphere/vcenter/setup/main.py", line 26, in <module>
    from samples.vsphere.common import sample_util
ImportError: No module named 'samples'

--------------
...any ideas?

Thanks in advance

**Comment by pgbidkar** [comment]
I think this question is related to git repo https://github.com/vmware/vsphere-automation-sdk-python.git 
Please follow steps mentioned here https://github.com/vmware/vsphere-automation-sdk-python#installing-the-required-python-packages

Looking @ error, it looks like you have not set export PYTHONPATH=${PWD}:$PYTHONPATH

**Comment by climbtech** [comment]
I have the path exported.  Still getting similar messages:
Traceback (most recent call last):
  File "samples/vsphere/vcenter/setup/main.py", line 26, in <module>
    from samples.vsphere.common import sample_util
  File "/autosrc/alt/vasp/samples/vsphere/common/sample_util.py", line 18, in <module>
    from vmware.vapi.bindings.struct import PrettyPrinter
ImportError: No module named 'vmware'

Yes, I am using that git repo, and following the steps in that article.

Thanks

**Comment by pgbidkar** [comment]
is pip install step successful 
pip install --upgrade --force-reinstall -r requirements.txt --extra-index-url <file:///abs_path/to/sdk/lib/>

**Comment by climbtech** [comment]
It is not.  I had to do manual pip/wheel installs of these packages:
vapi-client-bindings
vmc-client-bindings
vapi-vmc-client

The manual wheel installs completed successfully for those packages, directly from the libraries downloaded from the git repo (in ./lib)...but for some reason it wouldn't add them automatically.

**Comment by climbtech** [comment]
Also, as a test, I tried installing this on my mac w/ Python 2.7 (vs the linux box that I actually prefer to have it on running, Python 3.5), and received the same issue.

**Comment by climbtech** [comment]
when I run pip install --upgrade --force-reinstall -r requirements.txt --extra-index-url /alt/vasp/lib/, here is my full output:

$:/alt/vasp# pip install --upgrade --force-reinstall -r requirements.txt --extra-index-url /alt/vasp/lib
Ignoring suds-jurko: markers 'python_version >= "3.0"' don't match your environment
Collecting pyVmomi>=6.5 (from -r requirements.txt (line 1))
  Url '/alt/vasp/lib/pyvmomi/' is ignored. It is either a non-existing path or lacks a specific scheme.
Collecting suds (from -r requirements.txt (line 2))
  Url '/alt/vasp/lib/suds/' is ignored. It is either a non-existing path or lacks a specific scheme.
Collecting tabulate (from -r requirements.txt (line 4))
  Url '/alt/vasp/lib/tabulate/' is ignored. It is either a non-existing path or lacks a specific scheme.
  Using cached tabulate-0.8.2.tar.gz
**Collecting vapi-client-bindings==1.0.0 (from -r requirements.txt (line 5))
  Could not find a version that satisfies the requirement vapi-client-bindings==1.0.0 (from -r requirements.txt (line 5)) (from versions: 2.5.0)
No matching distribution found for vapi-client-bindings==1.0.0 (from -r requirements.txt (line 5))**

**Comment by pgbidkar** [comment]
I suspect location specified for --extra-index-url /alt/vasp/lib/ is not correct.
Please try with 
pip install --upgrade --force-reinstall -r requirements.txt --extra-index-url file:///alt/vasp/lib/

**Comment by climbtech** [comment]
That def took care of the install errors.  Let me see how the rest goes.  Thanks for your help, (and sorry for my misreading the path info)!

**Comment by climbtech** [comment]
had to fix a message for an nfs variable, but looks like the script ran successfully.  Thanks!
