### ISSUE TITLE
How to extract cdp information from hypervisor

### ISSUE THREAD

**Issue by olex777** [vmware/pyvmomi-community-samples#480]
Hi all, if somewhere could help me. I just began to work with pyVmomi so sorry for maybe fool questions. So I tried to use such a part of vim., https://github.com/vmware/pyvmomi/blob/master/docs/vim/host/PhysicalNic/CdpInfo.rst 
But when I tryied to create ViewType for access to the thread, in such a way

        # Create a view
         viewType_hyper = [vim.host]
 
        recursive = True  # whether we should look into it recursively
       

        # Loop through all obhects to return name and VMware tools version
        containerView_hyper = content.viewManager.CreateContainerView(
            container, viewType_hyper, recursive)
        children_hyper=(containerView_hyper.view)
        print (children_hyper)

I got an error -> containerView = content.viewManager.CreateContainerView(
(Pdb)
> /etc/network/scripts/sdk_test.py(66)main()
-> container, viewType, recursive)
(Pdb)
> /etc/network/scripts/sdk_test.py(67)main()
-> containerView_hyper = content.viewManager.CreateContainerView(
(Pdb)
> /etc/network/scripts/sdk_test.py(68)main()
-> container, viewType_hyper, recursive)
(Pdb)
TypeError: TypeErro...Module',)

or TypeError: For "type" expected type type, but got LazyModule

Something like 

viewType_hyper = [vim.HostSystem] works fine but I don't know how from this root to access to thread needed for me. What is I doing wrong? I just got all needed info about cluster and it structure, about virtual machine but I also need cdp neighbours of hypervisors. Please, I need help )

**Comment by prziborowski** [comment]
It is a bit confusing at first I agree.
vim.host is just a namespace, so you can't create a view on that. You can only create view on objects that are managed (such a vim.HostSystem, vim.VirtualMachine, vim.Folder, etc).

With a list of vim.HostSystem that you get from the CreateContainerView, you can iterate that and query about the network info.
```
for host in children_hyper:
   networkSystem = host.configManager.networkSystem
   if networkSystem is None:
      continue
   if not networkSystem.capabilities. supportsNetworkHints:
      continue
   for hint in networkSystem.QueryNetworkHint():
      print("Host %s, device %s, cdp info %s, lldp info %s" %
            (host.name, hint.device, hint.connectedSwitchPort,
             hint.lldpInfo))
```

**Comment by olex777** [comment]
Thanks a lot! It works!!!

2018-04-24 20:05 GMT+03:00 prziborowski <notifications@github.com>:
