### ISSUE TITLE
Extract dns information from sdk

### ISSUE THREAD

**Issue by olex777** [vmware/pyvmomi-community-samples#482]
Who can help in the iisue:
https://github.com/vmware/pyvmomi/blob/master/docs/vim/host/DnsConfig.rst  what is the way of access to this thread? When I tried use as "host" either name of vm or eXSI nothing good happen. So it looks like a hint, but how I could use this hint? I will be thankfull for reply.

**Comment by sathvikm** [comment]
Hi olex777,

Below is the script to extract the dns information of a esxi hosts using SDK. 

`

    #!/usr/bin/env python
    import ssl
    import requests
    from pyVim.connect import SmartConnect, Disconnect
    from pyVmomi import vim
    import atexit
    import sys
    import argparse

    # Disabling urllib3 ssl warnings
    requests.packages.urllib3.disable_warnings()
    # Disabling SSL certificate verification
    context = ssl.SSLContext(ssl.PROTOCOL_TLSv1)
    context.verify_mode = ssl.CERT_NONE

    def get_args():
        parser = argparse.ArgumentParser(
            description='Arguments for talking to vCenter')

        parser.add_argument('-s', '--host',
                            required=True,
                            action='store',
                            help='vSpehre service to connect to')

        parser.add_argument('-o', '--port',
                            type=int,
                            default=443,
                            action='store',
                            help='Port to connect on')

        parser.add_argument('-u', '--user',
                            required=True,
                            action='store',
                            help='User name to use')

        parser.add_argument('-p', '--password',
                            required=True,
                            action='store',
                            help='Password to use')

        args = parser.parse_args()
        return args


    def main():
        args = get_args()
        serviceInstance = SmartConnect(host=args.host,
                                       user=args.user,
                                       pwd=args.password,
                                       port=443,
                                       sslContext=context)
        atexit.register(Disconnect, serviceInstance)
        content = serviceInstance.RetrieveContent()
        host_view = content.viewManager.CreateContainerView(
            content.rootFolder,
            [vim.HostSystem],
            True
        )
        hosts = [host for host in host_view.view]
        for host in hosts:
            dns_config = host.configManager.networkSystem.dnsConfig
            host_name = dns_config.host_name
            dns_ip = dns_config.address
            print "Host: ", host_name
            print "DNS-1:", dns_ip[0]
            print "DNS-2:", dns_ip[1]
        return 0


    if __name__ == "__main__":
        sys.exit(main())

`
Thanks,
Sathvik M

**Comment by olex777** [comment]
Thanks a lot!

Чт, 17 трав. 2018 9:44 дп користувач Sathvik M <notifications@github.com>
пише:

**Comment by olex777** [comment]
I tried it, all is ok for esXi but if there any way to get this thread for vms?
