### ISSUE TITLE
Clone VM without resource pool

### ISSUE THREAD

**Issue by ivopavlik** [vmware/pyvmomi-community-samples#485]
Hello,

I'm new to vSphere Python SDK and I'd like to clone VMs without specifying resource pool. However, it seems to be obligatory despite of vCenter UI cloning (https://github.com/vmware/pyvmomi/blob/575ab56eb56f32f53c98f40b9b496c6219c161da/docs/vim/vm/CloneSpec.rst - location attribute).
I'd like to specify host only, which is marked as optional.
Is it possible?

Thanks.

**Comment by prziborowski** [comment]
The pool part of [RelocateSpec](https://code.vmware.com/apis/358/vsphere#/doc/vim.vm.RelocateSpec.html) shows:
```
The resource pool to which this virtual machine should be attached.
For a relocate or clone operation to a virtual machine, if the argument is not supplied, the current resource pool of virtual machine is used.
For a clone operation from a template to a virtual machine, this argument is required.
If the virtual machine is relocated to a different vCenter service, both the destination host and resource pool have to be specified and cannot be unset.
If the virtual machine is relocated to a different datacenter within the vCenter service, the resource pool has to be specified and cannot be unset.
```

So it seems like unless the current VM is in a cluster, if you specify a host, then the resource pool would default to the source VM's host, which wouldn't be compatible.
