### ISSUE TITLE
vim.HostSystem object has no attribute 'RebootHost'

### ISSUE THREAD

**Issue by rmdcoding** [vmware/pyvmomi-community-samples#487]
Trying to reboot a host using 'RebootHost' method and when I try to run it I get the following error:
```
  File "./reboot_esxi.py", line 161, in main
    if (WaitForTask(host.RebootHost(False))):
AttributeError: 'vim.HostSystem' object has no attribute 'RebootHost'
```

I made sure that the host allows for rebooting by checking ``` host.capability.rebootSupported```.
Other methods such as ```EnterMaintenanceMode``` and ``` ExitMaintenanceMode``` work without any issues within the same script on the same host. 

Is there something I am missing?

**Comment by rmdcoding** [comment]
@prziborowski Any thoughts?

**Comment by prziborowski** [comment]
Sorry for the delay in responding as I was away from my computer last week.
If you look at the docs for [HostSystem](https://code.vmware.com/apis/358/vsphere#/doc/vim.HostSystem.html), you can see the method name in parenthesis ([reboot](https://code.vmware.com/apis/358/vsphere#/doc/vim.HostSystem.html#reboot)). That is the name that you use for pyVmomi. I think it also allows you to use the wsdl name RebootHost_Task, but that is a bit of a mouthful.

**Comment by rmdcoding** [comment]
@prziborowski Thanks for the explanation!

**Comment by rmdcoding** [comment]
Issue has been resolved. Ended up using ```RebootHost_Task(bool)```. Thanks again for the help!

**Comment by kiranmohite6004** [comment]
AttributeError: 'vim.HostSystem' object has no attribute 'updatePassthruConfig'
On which object , i need to use this to run the updatePassthruConfig

host.configManager.pciPassthruSystem.updatePassthruConfig
host.configManager.updatePassthruConfig

host.config.pciPassthruSystem.updatePassthruConfig
host.config.updatePassthruConfig

host.pciPassthruSystem.updatePassthruConfig
host.updatePassthruConfig

None of the above working , Any help ?

**Comment by prziborowski** [comment]
For python, the methods need to be in a TitleCase format, so it would be:
`host.configManager.pciPassthruSystem.UpdatePassthruConfig(config)`
