### ISSUE TITLE
How to use thread

### ISSUE THREAD

**Issue by olex777** [vmware/pyvmomi-community-samples#488]
When I try to use HardwareSummary.rst
https://github.com/vmware/pyvmomi/blob/master/docs/vim/host/Summary/HardwareSummary.rst
I had such an error:
> /etc/network/scripts/functions/sdk_hpsm_ipplan_sync.py(298)get_sdk_data()
-> hosthardware=host.summary.HardwareSummary
(Pdb) next
AttributeError: "'vim.host.Summary' object has no attribute 'HardwareSummary'"
Whats wrong, how to fix it?

**Comment by prziborowski** [comment]
@hartsock might know what went on with the documentation.
HardwareSummary is just a class of vim.host.Summary namespace.
It doesn't mean it is part of `host.summary` (https://code.vmware.com/apis/358/vsphere#/doc/vim.host.Summary.html)

You can get HardwareSummary with `host.summary.hardware`

**Comment by olex777** [comment]
Yes, in such a way I could see what I need. Thank you very much!

2018-06-04 19:40 GMT+03:00 prziborowski <notifications@github.com>:
