### ISSUE TITLE
Unresolved import: vmodl

### ISSUE THREAD

**Issue by bobfraser1** [vmware/pyvmomi-community-samples#49]
When using Eclipse PyDev, in many samples (e.g. getallvms.py) the line:
from pyVmomi import vmodl

results in the error marker:
Unresolved import: vmodl

Is there any way to resolve this without error?

**Comment by hartsock** [comment]
NOTE: a common work-around is to "suppress inspection" or the equivalent. I use PyCharm and this is how you [suppress](https://www.jetbrains.com/help/pycharm/2016.1/suppressing-inspections.html) in that IDE. Your IDE's instructions may vary.
