### ISSUE TITLE
deploy_ovf script does not honour thin provisioning

### ISSUE THREAD

**Issue by chris-david-taylor** [vmware/pyvmomi-community-samples#502]
Hi,

I'm using the deploy_ovf.py script to experiment deploying a Virtual Machine from a locally stored ova and VMDK.  It is a thin provisioned template VMDK , but the script always creates a thick provisioned disk.

I tried updating the Import Spec Params; but it isn't honoured;

spec_params = vim.OvfManager.CreateImportSpecParams(diskProvisioning = "thin" ). 
 
I'm on vSphere 6.5, and there are no errors in the verbosity - any suggestions about what I might be doing wrong?

Thank you.

**Comment by sylflo** [comment]
I did not use the script but `diskProvisioning = "thin"` works for me.
I guess the issue must have been solved
