### ISSUE TITLE
Search folder by absolute path

### ISSUE THREAD

**Issue by srinivasguttur** [vmware/pyvmomi-community-samples#505]
Hi Team,

Is there any chance to search a Folder under datacenter with absolute path of that folder using PyVmomi? I am in a situation where multiple folders in a same same DC with same name.

Please suggest me any help.

Thanks
Srini

**Comment by prziborowski** [comment]
Yes, you can use the [FindByInventoryPath](https://code.vmware.com/apis/358/vsphere#/doc/vim.SearchIndex.html#findByInventoryPath) function of SearchIndex.

```
obj = si.content.searchIndex.FindByInventoryPath('Datacenter Name/vm/folder1/folder2/Folder Name that appears in lots of places')
if obj is None:
   raise Exception("Folder / VM not found")
```

**Comment by srinivasguttur** [comment]
Thanks a lot @prziborowski .

**Comment by srinivasguttur** [comment]
Hi @prziborowski , I have tried but I am always get "None" return, even though the "Folder" exist and inside the Datacenter path.

But, I am able to list the same folder from vim.Folder.

obj = self.content.searchIndex.FindByInventoryPath('PROD-STG/Templates/Folder1/Folder')


Thanks
Srini

**Comment by srinivasguttur** [comment]
Thanks a ton @prziborowski . It worked!!!!!

**Comment by nandishnagaraj** [comment]
![image](https://user-images.githubusercontent.com/47733024/64754668-e3a1c400-d545-11e9-9aec-695b7400d145.png)


I am unable to give the VMPath, Need Help, thanks
