### ISSUE TITLE
pyVim no module

### ISSUE THREAD

**Issue by Ram-kuruva-nokia** [vmware/pyvmomi-community-samples#514]
Hi,
i have a requirement to get the pci details for my centos machine,hence i used above code and i am getting below error.

Traceback (most recent call last):
  File "pci.py", line 22, in <module>
    from pyVim import connect
ImportError: No module named pyVim

**Comment by shekharHPE** [comment]
I am facing same issue, were you able to solve this issue ?

**Comment by kumahesh** [comment]
Hi @shekharHPE ,
I know it is late. From my understanding, I think you had not included pyVmomi into PYTHONPATH. please set PYTHONPATH.

**Comment by hunter32292** [comment]
You're installing `pyvim` not `pyVim`
https://github.com/prompt-toolkit/pyvim

**Comment by chris-kiick-sp** [comment]
I had a similar issue.  **_DO NOT_** install "pyvim".  This is a completely separate package (vim editor implemented in python).  However, the name conflicts enough that the files get messed up.
This is what cleared it up for me:
```
pip3 uninstall pyvim
# may complain about manually added files.
cd /usr/local/lib/python3.7/site-packages
rm -rf pyvim
pip3 install --force pyvmomi
```

**Comment by kennyphampoway** [comment]
I'm getting the same issue. Requests is already installed. ansible_python_interpreter=/usr/bin/python3.6. I really cant find what is causing the issue. This is when ansible calls the docker_image module. Please help

- name: Build container image
  hosts: localhost
  vars:
    ansible_python_interpreter: /usr/bin/python3.6
  become: yes
  tasks:
    - name: test docker image
      community.docker.docker_image:
            name: image_base:latest
            source: build
            build:
                path: /tmp/container



  "msg": "Failed to import the required Python library (requests) on vdev.bde.net's Python /usr/bin/python3.6. Please read the module documentation and install it in the appropriate location. If the required library is installed, but Ansible is using the wrong Python interpreter, please consult the documentation on ansible_python_interpreter"


My ansible 
ansible [core 2.11.12]
  config file = /home/sandbox/test_docker_ansible/ansible.cfg
  configured module search path = ['/home/sandbox/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/sandbox/.local/lib/python3.6/site-packages/ansible
  ansible collection location = /home/sandbox/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/sandbox/.local/bin/ansible
  python version = 3.6.8 (default, Nov 16 2020, 16:55:22) [GCC 4.8.5 20150623 (Red Hat 4.8.5-44)]
  jinja version = 3.0.3
  libyaml = True

 pip3.6 list
ansible            4.10.0
ansible-core       2.11.12
requests           2.27.1
