### ISSUE TITLE
How to pull active snapshot VM details in Vcenter

### ISSUE THREAD

**Issue by muraliselva10** [vmware/pyvmomi-community-samples#522]
Hello, 

I am trying to explore way to get the details of snapshots exists in VCenter.

That is, I need to collect the active Snapshots available for VM, and details of the snapshot(age, created on etc)

Is there any possibilities available using Pyvmomi ?

Thanks

**Comment by rmdcoding** [comment]
https://github.com/vmware/pyvmomi-community-samples/blob/master/samples/snapshot_operations.py

Specifically "list_all" and "list_current".
