### ISSUE TITLE
Sample: Import ova

### ISSUE THREAD

**Issue by hartsock** [vmware/pyvmomi-community-samples#54]
Based on: https://github.com/vmware/pyvmomi/issues/12

Demonstrate the full process of obtaining an OVA and then uploading the OVA into a connected vSphere environment. Do this with pyVmomi and show how to access the OVF Manager.

**Comment by hartsock** [comment]
I've had a priority shift since last looking at this. I'll reschedule once we have an idea of approximate velocity for this project.

**Comment by VarunUmesh** [comment]
@hartsock Could you please let me know if you have an example for this?

**Comment by stormbeard** [comment]
I had to import an OVF for something at work, so hopefully someone finds this useful:
http://www.stormbeard.net/jekyll/update/2015/04/13/pyvmomi-ovf-deployment.html

**Comment by hartsock** [comment]
@stormbeard thanks for posting, I'm trying to free up some time to create some samples but it's been tough. If someone has some cycles that blog post would make a good basis for a sample for here.

**Comment by VarunUmesh** [comment]
@stormbeard thanks for this pointer. I think i can extend it for what i want!

**Comment by arjunsinghvi** [comment]
@hartsock @stormbeard - Do you have a sample for importing ova in vSphere ?

**Comment by arjunsinghvi** [comment]
The state of the lease goes from initializing to error. How can I debug the cause for this error ? @hartsock

**Comment by stormbeard** [comment]
The lease should have a 'msg' string component for the error that gives a brief statement on why it failed.

Also, there is a pull request that provides a working example of ova deployment that is under review.

**Comment by arjunsinghvi** [comment]
@stormbeard - I am looking at that as a reference. 

http://stackoverflow.com/questions/32119143/unsupported-operation-leading-to-lease-error-in-pyvmomi

A few of us keep getting this error. What can be the cause ?

**Comment by stormbeard** [comment]
I've gotten the 'The operation is not supported on the object.' error when trying to deploy the VM to a vCenter server instead of a host. Are you specifying the host IP address or the vCenter IP?

**Comment by arjunsinghvi** [comment]
@stormbeard - Thanks! I was using the vCenter IP.

The template gets deployed even though the cURL fails to find the .vmdk file. How is this possible ? Even when I commented out the cURL command, the deplyment succeeds.

**Comment by stormbeard** [comment]
I'm not sure of your definition for deployment success here, but I'd bet money that whatever was deployed has nothing useful attached to its disk. It's up to you to verify the POST was successful, otherwise you're left with a half-baked VM.

What I typically do in the event of an error like the one you had (unable to find the VMDK) is to report some error and delete the leftover VM object (returned by lease.info.entity).

**Comment by arjunsinghvi** [comment]
@stormbeard - Is it possible to download a .ova file directly to a datastore, extract the .ovf and .vmdk from there and use the datastore path to read the ovf descriptor and upload the .vmdk file ?

**Comment by arjunsinghvi** [comment]
I am able to convert it to a template and power on the vm. Therefore, I assumed it was a successful deployment.

@stormbeard - Is it possible to download a .ova file directly to a datastore, extract the .ovf and .vmdk from there and use the datastore path to read the ovf descriptor and upload the .vmdk file ?

**Comment by prashasthip** [comment]
@hartsock  @stormbeard - I was looking at the pull request ift.tt/1ESuAxK 
However, the cURL keeps giving 
curl: Can't '/path/to/file.vmdk'!
curl: try 'curl --help' or 'curl --manual' for more information

The path is correct and the file has all permission. Could someone shed some light on this ? @arjunsinghvi - are you getting the same error ?

**Comment by prashasthip** [comment]
@stormbeard @hartsock 
I am trying to run the sample deploy_ovf. However, the minute it reaches the cURL to upload the .vmdk, the deployment stops at 50%. It never progresses beyond that. However when I look at tasks & events, it shows that the instance UUID, BIOS UUID, MAC Address are all assigned and the VM is created. It then times out and the VM is deleted. Can you provide any insights ?

**Comment by krishn2014** [comment]
@stormbeard I can export a VM in .vmdk format. I am not getting any clue how to export in .ova format. Can you give me some pointers.

**Comment by stormbeard** [comment]
@krishn2014 an OVA file is just a tarball containing .ovf and its associated .vmdk files.

@prashasthip sorry, I'm not sure what could be going on there. In the example, I manually had it set the progress to 50% to keep the connection alive. You may want to verify whether or not the API calls are successful.

@hartsock : Doesn't pull request #199 takes care of this open issue?

**Comment by michaelrice** [comment]
@stormbeard did you add something like: fixes #54 to the commit message? If you would have it should have closed this issue when the code was merged. Otherwise it will have to be manually closed.

**Comment by hartsock** [comment]
@stormbeard yes. Closing this. We have a sample now, but that doesn't mean there isn't room for improvement. :-)

**Comment by krishn2014** [comment]
@stormbeard  thanks very much that helped.
