### ISSUE TITLE
running getallvms.py against vcenter 6.7 getting no info

### ISSUE THREAD

**Issue by tdubb123** [vmware/pyvmomi-community-samples#553]

**Comment by tdubb123** [comment]
I am getting blank info when running getallvms.py against my vcsa 6.7 appliance 

python3 getallvms.py -s x.x.x.x -u administrator@vsphere.local -p xxxxxxx

no erros and no output

**Comment by pgbidkar** [comment]
Hi @tdubb123 , I dont see this issue in my setup. Please can you check your setup again? Verified against 6.7 VC

**Comment by tdubb123** [comment]
I do not understand what it is. 

I am using python 3.7.2

I tried changing my ssl to v23 but still same result. no output. 

<img width="1026" alt="Screen Shot 2019-03-21 at 12 28 00 PM" src="https://user-images.githubusercontent.com/33203231/54779762-38870200-4bd5-11e9-8f63-738d90a891ba.png">

**Comment by kumahesh** [comment]
Hi @tdubb123 ,
I tried with python 3.7.2 against 6.7 VC. I could not reproduce the issue. I found your code is different from the one in master's branch. Could you share code instead of the screen shot?

**Comment by ravic499** [comment]
@tdubb123 Looks like you have modification to the actual file or addressing to a wrong file. I just compared your screenshot with the actual file and couldn't find the issue which you are reporting.
As @kumahesh requested share your actual file for us to help you.

**Comment by pgbidkar** [comment]
Hi @tdubb123 Can we close issue?
