### ISSUE TITLE
'NoneType' object has no attribute 'RetrieveContent'

### ISSUE THREAD

**Issue by houcinedz** [vmware/pyvmomi-community-samples#561]
when i try to create a machine i was get this erro 

return _get_obj(si.RetrieveContent(), [vim.VirtualMachine], name)
AttributeError: 'NoneType' object has no attribute 'RetrieveContent'

i use python 3.6   and vshere 6.0

**Comment by pgbidkar** [comment]
Hi @houcinedz Please can you print 'si'? You need to call SmartConnect() to get si instance. Looks like connection is not successful

Thanks

**Comment by houcinedz** [comment]
usage: clone_vm.py [-h] -s HOST [-o PORT] -u USER [-p PASSWORD] -v VM_NAME
                   [--no-ssl] --template TEMPLATE
                   [--datacenter-name DATACENTER_NAME] [--vm-folder VM_FOLDER]
                   [--datastore-name DATASTORE_NAME]
                   [--datastorecluster-name DATASTORECLUSTER_NAME]
                   [--cluster-name CLUSTER_NAME]
                   [--resource-pool RESOURCE_POOL] [--power-on]
                   [--opaque-network OPAQUE_NETWORK]
clone_vm.py: error: the following arguments are required: --template

**Comment by houcinedz** [comment]
how i can create a vm with pyvmomi ?


Le jeu. 11 avr. 2019 à 11:05, Pavan Bidkar <notifications@github.com> a
écrit :
