### ISSUE TITLE
New Sample: Promoting Existing VMDK as First Class Disk

### ISSUE THREAD

**Issue by Chandan-Hegde** [vmware/pyvmomi-community-samples#570]
Need a script to promote existing VMDK to FCD.

**Comment by Chandan-Hegde** [comment]
Resolved  in the pull request https://github.com/vmware/pyvmomi-community-samples/pull/568#commitcomment-33362829

**Comment by harjitsinghntnx** [comment]
@Chandan-Hegde Do you have any idea about this issue?
##Exception in making disk as FCD (vmodl.fault.InvalidArgument) {
   dynamicType = <unset>,
   dynamicProperty = (vmodl.DynamicProperty) [],
   msg = 'A specified parameter was not correct: dc',
   faultCause = <unset>,
   faultMessage = (vmodl.LocalizableMessage) [],
   invalidProperty = u'dc'
}

**Comment by Chandan-Hegde** [comment]
> @Chandan-Hegde Do you have any idea about this issue?
> ##Exception in making disk as FCD (vmodl.fault.InvalidArgument) {
> dynamicType = ,
> dynamicProperty = (vmodl.DynamicProperty) [],
> msg = 'A specified parameter was not correct: dc',
> faultCause = ,
> faultMessage = (vmodl.LocalizableMessage) [],
> invalidProperty = u'dc'
> }

This issue might be due to wrong path parameter.
