### ISSUE TITLE
Assign storage policy to a VM and its disks (vSphere -> Select VM -> VM Policies -> Edit VM Storage Policies)

### ISSUE THREAD

**Issue by ravic499** [vmware/pyvmomi-community-samples#575]
I could see support provided for create/update/delete storage policy. Similarly I need support for assigning a storage policy to a VM and its hard disks

vSphere -> Select VM -> VM Policies -> Edit VM Storage Policies

Please help me with it.

**Comment by carceneaux** [comment]
There's currently an open PR with code surrounding your question. 

https://github.com/vmware/pyvmomi-community-samples/pull/571

Hope this helps!

**Comment by DanielDraganov** [comment]
https://github.com/vmware/pyvmomi-community-samples/pull/571 is merged. I'm closing the issue.
