### ISSUE TITLE
Do you have pyVmomi sample code for disabling Vmotion on a single VM?

### ISSUE THREAD

**Issue by les-tallman** [vmware/pyvmomi-community-samples#578]
Do you have pyVmomi sample code for disabling Vmotion on a single VM? We are attempting to deploy a VM from a template, and when it powers on, We need to be able to disable Vmotion or set an override for a period of time, until it finishes customization. We only have access to a Python interpreter, so we can't use the Powershell example.

Best regards,
Les

**Comment by pgbidkar** [comment]
If I go through API reference there are only check operations on the vMotion for VM https://vdc-download.vmware.com/vmwb-repository/dcr-public/6b586ed2-655c-49d9-9029-bc416323cb22/fa0b429a-a695-4c11-b7d2-2cbc284049dc/doc/vim.vm.check.ProvisioningChecker.html#checkMigrate.

Disabling vMotion is application at Cluster Level. 

Thanks

**Comment by kumahesh** [comment]
As @pgbidkar said, the feature Vmotion has wide coverage of use cases at the cluster level. Disable switch at cluster level is much more compelling use case. So, I am curious to understand your scenario. Could you shed more light on your case?
