### ISSUE TITLE
How to get vCenter appliance (VCSA) disk usage by pyvmomi for Vcenter 6.0 or 6.5 or 6.7. Is there is way we can do this in Vcenter 6.0

### ISSUE THREAD

**Issue by Imranatnisum** [vmware/pyvmomi-community-samples#581]
python version:
3.7
vSphere version:
6.0, 6.5 and 6.7
Operating System/Shell (used to run SDK-based apps):
Mac os

**Comment by carceneaux** [comment]
Hi @Imranatnisum,

pyvmomi uses VMware's SOAP API to retrieve information. VCSA disk usage is not accessible using this API.

So how can you retrieve this information?

6.0 - You won't find this information in any vSphere API. You'll have to work with the guest OS of the VCSA to pull this information.

6.5/6.7 - VCSA now has it's own Rest API that's separate from vSphere's SOAP/Rest API. This API dedicated to VCSA operations contains the data you're looking for:

[Capacity Monitoring of the vCenter Server Appliance](https://code.vmware.com/docs/6529/vmware-vcenter-server-appliance-management-programming-guide#/doc/GUID-22B58718-8156-45E6-9772-7DB775F5015A.html)
