### ISSUE TITLE
Datastore Over Provisioning 

### ISSUE THREAD

**Issue by Imranatnisum** [vmware/pyvmomi-community-samples#582]
Do we have some way to  get Datastore Over Provisioning 

python version:
3.7
vSphere version:
6.0, 6.5 and 6.7
Operating System/Shell (used to run SDK-based apps):
Mac os

**Comment by kumahesh** [comment]
The same issue has been raised in [pyvmomi official project](https://github.com/vmware/pyvmomi/issues/802). So, marking this as duplicate to avoid confusion. It will be followed there.
