### ISSUE TITLE
How to get vm created time

### ISSUE THREAD

**Issue by mosheronen** [vmware/pyvmomi-community-samples#586]
Hello,

Do you have any example for getting VirtualMachine CreatedTime using pyvmomi?

Best Regards, Moshe

**Comment by carceneaux** [comment]
To determine when a VM was created, you must search the vCenter events database.

Here's an example using PowerCLI: https://communities.vmware.com/thread/608125

For `pyvmomi`, the closest sample I could find in this repository is in the link below. You'll have to modify the search criteria but at least it gives you a start. 😄

https://github.com/vmware/pyvmomi-community-samples/blob/master/samples/relocate_events.py

**Comment by mosheronen** [comment]
Hi @carceneaux ,
Thanks a lot
I'll review https://github.com/vmware/pyvmomi-community-samples/blob/master/samples/relocate_events.py and make my filter

**Comment by pgbidkar** [comment]
Hi @carceneaux , Please can you confirm if your query is answered. Close if it is solved

Thanks

**Comment by pgbidkar** [comment]
Sorry, Closed by mistake. Will close once confirmed

**Comment by carceneaux** [comment]
@pgbidkar I think you mentioned me by mistake. 😊

Hi @mosheronen, Can you please confirm if your query is answered and close this issue if it is solved?

**Comment by pgbidkar** [comment]
Closing the issue. Please reopen if issue is not resolved.

Thanks
