### ISSUE TITLE
Question: How to Uninstall vmware tools?

### ISSUE THREAD

**Issue by TUncleSan** [vmware/pyvmomi-community-samples#592]
I use the UnmountToolsInstaller() method to try to uninstall vmware tools. But in the virtual machine operating system, I see that the vmware tools program still appears in the uninstall list (windows) or in the corresponding directory (Linux). Can UnmountToolsInstaller actually uninstall vmware tools? Or need to use other methods?

**Comment by carceneaux** [comment]
`UnmountToolsInstaller` is only unmounting the VMware Tools ISO from the CD drive on a VM. It is not uninstalling VMware Tools. Uninstalling VMware tools happens at the guest OS level and not the vSphere level.

Uninstallation process will differ depending on the OS. Here's an example:

[Uninstalling VMware Tools](https://docs.vmware.com/en/VMware-vSphere/6.0/com.vmware.vsphere.vm_admin.doc/GUID-6F7BE33A-3B8A-4C57-9C35-656CE05BE22D.html?hWord=N4IghgNiBcIK4DsCWCDOAXSEAEA3AtgO5gBOAptugPZUSogC+QA)

**Comment by TUncleSan** [comment]
Thank you very mach, Your answer is very helpful to me.
