### ISSUE TITLE
QUESTION: How to get the network ID

### ISSUE THREAD

**Issue by djsmiddy** [vmware/pyvmomi-community-samples#595]
Hi I have been using the script to  deploy OVA and using the rest API to get the network ID so that i can pick the network, but i'm trying to run this on an older cluster v6 so cant use the rest API, is there a way to get the network ID using the python script ?

**Comment by carceneaux** [comment]
Hi @djsmiddy,

Please provide more information so that we can help you. What script are you currently using? What Rest API call are you running to retrieve the Network ID? Is the network ID for a VSS Portgroup or a DVS Portgroup?

Once we have this info, we should be able to help. The pyvmomi uses the vSphere SOAP API and will be able to get you pretty much anything you want.

**Comment by djsmiddy** [comment]
Hi @carceneaux 

Thanks for the quick response, sorry about the lack of info 

This is what i am using to get the network ID, I pass in the name (netname)of the network from vcenter, usually something like VLAN_555, this then gets me 'Network-28' i can then use that Network-28 to assign the network to the interface when deploying ova 


def get_vcenter_network(netname):
    resp = get_api_data('{}/vcenter/network'.format(api_url))
    networks = resp.json()
    for network in networks['value']:
        
        if network['name'] == netname:
            vcnet = network['network']
            
            return(vcnet)
    return(vcnet)

I then pass the vcnet to 

 net_id = vim.Network(vcnet )
 network = [vim.OvfManager.NetworkMapping(name='LAN', network=net_id),vim.OvfManager.NetworkMapping(name='WAN', network=net_id)]


hope this helps

**Comment by carceneaux** [comment]
@djsmiddy - Please find my sample code in this PR. This code will not only get you the network ID your looking for in a Standard Port Group but it will also work if you ever switch to a Distributed Port Group.

https://github.com/vmware/pyvmomi-community-samples/pull/596

**Comment by djsmiddy** [comment]
Sorry for the late response but thanks very much it works a treat 

Sent from Mail for Windows 10

**Comment by carceneaux** [comment]
@djsmiddy Glad to hear it worked! If your question has been answered, please close this issue.
