### ISSUE TITLE
Script to acknowledge "I moved it"

### ISSUE THREAD

**Issue by Gerardwx** [vmware/pyvmomi-community-samples#598]
When a VM is removed from one VM and then registered in VCenter 6.7, there's a prompt when starting asking whether the VM was copied or moved -- is there a pyvmomi way of acknowledging that in advance? (That is, something that can be executed after it's been registered but before attempting to start it?)

**Comment by carceneaux** [comment]
https://github.com/vmware/pyvmomi-community-samples/blob/master/samples/virtual_machine_power_cycle_and_question.py
