### ISSUE TITLE
wait_for_tasks and WaitForTash both not working

### ISSUE THREAD

**Issue by RobertLHarris** [vmware/pyvmomi-community-samples#599]
This is likely my problem, but I'm missing something.

I've tried all 3 of these:

1)  task = si.content.customFieldsManager.SetField(entity=data['vm_obj'], key=data['Keys'][Attribute], value=data['args'].SetValue)
     wait_for_tasks( si, [task] )
2)  wait_for_tasks( si, [si.content.customFieldsManager.SetField(entity=data['vm_obj'], key=data['Keys'][Attribute], value=data['args'].SetValue)] )
3)  task = si.content.customFieldsManager.SetField(entity=data['vm_obj'], key=data['Keys'][Attribute], value=data['args'].SetValue)
     WaitForTask(task)

At this point I only need 1 task, but I can see not too far out I'll have multiple so I started looking at "wait_for_tasks".

If I run #1 or #2, it does run the task, but if I do 'print(repr(task))' I get a NoneType back.

Anyone have a good example of how to fix this?

Robert

**Comment by prziborowski** [comment]
[SetField](https://code.vmware.com/apis/358/vsphere#/doc/vim.CustomFieldsManager.html#setField) method is not a task. It is synchronous, so when the call returns to you, it has completed.

**Comment by RobertLHarris** [comment]
Ok, I can deal with that.  The RemoveCustomFieldDef definitely isn't though.  I can do the Remove, then immediately print the CustomeFields again and it's still there,  a minute later it's gone.

**Comment by RobertLHarris** [comment]
For the Curious I had to re-get the custom fields after I SetIt it, that's why the SetField was still sowing the same value.  For the Delete, can't use that, it nukes the field out-right for all VM's not just the one in the vm_obj I'm working on.

**Comment by kumahesh** [comment]
Is that issue got resolved? If resolved,
Could you convert short snippet of your code into sample code for setting/getting up custom field for VM? At present, we do not have any sample for setting up custom fields of vms. It might be useful for the community.

**Comment by Akasurde** [comment]
For posterity - https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/vmware/vmware_guest_custom_attributes.py is good example for setting up custom field for VM.

**Comment by RobertLHarris** [comment]
@kumahesh I have the whole script put up on Github since it might help people.  I use it to set tags for the purpose of Grouping for some Recovery systems.  The Script will list and change current keys as well as set New.

https://github.com/RobertLHarris/MiscTools/blob/master/VMware/vCenterVMSetTags.py

Feedback and suggestions are very welcome.
