### ISSUE TITLE
Extract multiple IP with pyvmomi

### ISSUE THREAD

**Issue by redmine-cosi** [vmware/pyvmomi-community-samples#600]
Hi all,
I'm using a python script for listing the vms on an ESX / vCenter host. I see that I can get a single IP address associate with a VM using, but in my case, I have five NICs and there are five IP addresses. This object returns random IP address of the three (after every reboot of the vm).

...
import atexit
from pyVim import connect
from pyVmomi import vmodl
from pyVmomi import vim
from decimal import Decimal
import apitools.cli as cli
...
...
if summary.guest is not None:
ip_address = summary.guest.ipAddress
tools_version = summary.guest.toolsStatus
if tools_version is not None:
print("VMware-tools: ", tools_version)
else:
print("Vmware-tools: None")
if ip_address:
print("Default IP : ", ip_address)
else:
print("IP : None")
if summary.runtime.question is not None:
print("Question : ", summary.runtime.question.text)
print("")
...

**Comment by redmine-cosi** [comment]
Hi all,
I'm using a python script for listing the vms on an ESX / vCenter host. I see that I can get a single IP address associate with a VM using, but in my case, I have five NICs and there are five IP addresses. This object returns random IP address of the three (after every reboot of the vm).

...
import atexit
from pyVim import connect
from pyVmomi import vmodl
from pyVmomi import vim
from decimal import Decimal
import apitools.cli as cli
...
...
    if summary.guest is not None:
        ip_address = summary.guest.ipAddress
        tools_version = summary.guest.toolsStatus
        if tools_version is not None:
            print("VMware-tools: ", tools_version)
        else:
            print("Vmware-tools: None")
        if ip_address:
            print("Default IP  : ", ip_address)
        else:
            print("IP            : None")
    if summary.runtime.question is not None:
        print("Question  : ", summary.runtime.question.text)
    print("")
...

**Comment by redmine-cosi** [comment]
Hi all,
I'm using a python script for listing the vms on an ESX / vCenter host. I see that I can get a single IP address associate with a VM using, but in my case, I have five NICs and there are five IP addresses. This object returns random IP address of the three (after every reboot of the vm).

...
import atexit
from pyVim import connect
from pyVmomi import vmodl
from pyVmomi import vim
from decimal import Decimal
import apitools.cli as cli
...
...
if summary.guest is not None:
ip_address = summary.guest.ipAddress
tools_version = summary.guest.toolsStatus
if tools_version is not None:
print("VMware-tools: ", tools_version)
else:
print("Vmware-tools: None")
if ip_address:
print("Default IP : ", ip_address)
else:
print("IP : None")
if summary.runtime.question is not None:
print("Question : ", summary.runtime.question.text)
print("")
...

**Comment by carceneaux** [comment]
This question was answered previously here:

https://github.com/vmware/pyvmomi-community-samples/issues/218#issuecomment-258384700

The area you're currently pulling the IP Address from only supports a single IP. Upon reboot, whichever IP is first in the array wins the prize. To get what you need, pull the IP Address from the area in the aforementioned issue.
