### ISSUE TITLE
How to set das.respectvmvmantiaffinityrules using pyvmomi

### ISSUE THREAD

**Issue by raagha-b** [vmware/pyvmomi-community-samples#601]
I am been exploring a way to set this advanced option das.respectvmvmantiaffinityrules using pyvmomi.  No luck

**Comment by prziborowski** [comment]
I will assume you have an object to the [cluster](https://code.vmware.com/apis/358/vsphere#/doc/vim.ClusterComputeResource.html)
From that you should be able to [ReconfigureEx](https://code.vmware.com/apis/358/vsphere#/doc/vim.ComputeResource.html#reconfigureEx) passing in the [configSpec](https://code.vmware.com/apis/358/vsphere#/doc/vim.cluster.ConfigSpecEx.html) that has option set.

Example:
```
from pyVim.task import WaitForTask
from pyVmomi import vim
...
key = "das.respectVmVmAntiAffinityRules"
optVal = vim.option.OptionValue(key=key, value="true")
dasConfig = vim.cluster.DasConfigInfo(option=[optVal])
configSpec = vim.cluster.ConfigSpecEx(dasConfig=dasConfig)
WaitForTask(cluster.ReconfigureEx(configSpec, True))
```

**Comment by raagha-b** [comment]
Thanks a lot.. that seems to work
