### ISSUE TITLE
Question：--port-group

### ISSUE THREAD

**Issue by happyhelloworld** [vmware/pyvmomi-community-samples#606]
add_nic_to_vm.py  parameter --port-group，what does it main ?
Can anyone give an example?
python add_nic_to_vm.py -s IP -u root -p PASSWD -v VMNANE --port-group (XXX)
How to view by Command esxcli?

**Comment by prziborowski** [comment]
It is the portgroup name for a standard vSwitch. A default that is created is typically "VM Network".
An esxcli that will list VM portgroup as well as vmkernel would be `esxcli network vswitch standard portgroup list`
I'm not sure if it is possible to exclude non-VM portgroups from the esxcli command.

**Comment by happyhelloworld** [comment]
> It is the portgroup name for a standard vSwitch. A default that is created is typically "VM Network".
> An esxcli that will list VM portgroup as well as vmkernel would be `esxcli network vswitch standard portgroup list`
> I'm not sure if it is possible to exclude non-VM portgroups from the esxcli command.

**Comment by happyhelloworld** [comment]
@prziborowski Thanks,
I have solved this problem. I passed in the wrong parameter.
