### ISSUE TITLE
How do you delete a virtual disk with pyvmomi

### ISSUE THREAD

**Issue by bfranske** [vmware/pyvmomi-community-samples#608]
I am trying to write a Python program using the pyvmomi library to "erase" a virtual hard drive associated with a VM. The way this is done manually is to remove the virtual disk and create a new virtual disk with the same specs. I am expecting that I will need to do the same thing with pyvmomi so I have started down that path. My issue is that I can use ReconfigVM_Task to remove the virtual drive but that leaves the VMDK file itself.

I originally tried using DeleteVStorageObject_Task (since DeleteVirtualDisk_Task is deprecated) to remove the virtual disk file but that requires the ID of the object (the VMDK file) which I am unable to find anywhere. Theoretically that's available from the VirtualDisk property vDiskId but that is null. In further research it seems to only be populated for first class disks.

So I am instead trying to delete the VMDK file directly using DeleteDatastoreFile_Task but when I do that I end up with a XXXX-flat.vmdk file in the datastore so it seems to not actually delete the file.

Any idea on where I'm going wrong here or how to better do this? I've seen #352 and #216 but those seem to be outdated for recent versions of vsphere and I'm unable to locate any documentation on this.

Thanks!

**Comment by carceneaux** [comment]
Have you tried the below?

https://github.com/vmware/pyvmomi-community-samples/blob/master/samples/delete_disk_from_vm.py

**Comment by carceneaux** [comment]
In case the aforementioned script only removes and does not delete, how about this?

https://github.com/vmware/pyvmomi/issues/303

**Comment by bfranske** [comment]
Right, the script only removes the disk from the VM, it does not delete the VMDK from the datastore. vmware/pyvmomi#303 uses the DeleteVirtualDisk_Task which is deprecated. Since it's deprecated I'm looking for what replaces it. Thanks!

**Comment by carceneaux** [comment]
Per [VMware API Documentation](https://vdc-download.vmware.com/vmwb-repository/dcr-public/790263bc-bd30-48f1-af12-ed36055d718b/e5f17bfc-ecba-40bf-a04f-376bbb11e811/vim.VirtualDiskManager.html#deleteVirtualDisk), this call should be used:

[HostVStorageObjectManager](https://vdc-download.vmware.com/vmwb-repository/dcr-public/790263bc-bd30-48f1-af12-ed36055d718b/e5f17bfc-ecba-40bf-a04f-376bbb11e811/vim.vslm.host.VStorageObjectManager.html)

**Comment by bfranske** [comment]
Since I'm using Vcenter I think a better one would be [DeleteVStorageObject_Task](https://vdc-download.vmware.com/vmwb-repository/dcr-public/790263bc-bd30-48f1-af12-ed36055d718b/e5f17bfc-ecba-40bf-a04f-376bbb11e811/vim.vslm.vcenter.VStorageObjectManager.html#deleteVStorageObject) but therein lies the problem. Both HostDeleteVStorageObject_Task and DeleteVStorageObject_Task require an id field with the Data Object - ID type. See my original issue: 

> I originally tried using DeleteVStorageObject_Task (since DeleteVirtualDisk_Task is deprecated) to remove the virtual disk file but that requires the ID of the object (the VMDK file) which I am unable to find anywhere. Theoretically that's available from the VirtualDisk property vDiskId but that is null. In further research it seems to only be populated for first class disks.

In order to use what appear to be the new correct APIs: HostDeleteVStorageObject_Task or DeleteVStorageObject_Task you need to get an ID data object for the virtual disk but it's unclear how you can get that for a file other than a first class disk.

**Comment by carceneaux** [comment]
I see. I wrote something very similar that should allow you to retrieve the object you're looking for. I wrote the function for FIrst Class Disks but it should work with little/no change for your VMDK.

**retrieve_fcd** - https://github.com/vmware/pyvmomi-community-samples/blob/master/samples/tools/disk.py

Hope this helps!

**Comment by bfranske** [comment]
I actually had taken a look at that. Unfortunately it won't work for non-first class disks as the ID simply does not exist for non-FCDs as far as I can tell. In other words there is actually no ID to retrieve and the  DeleteVStorageObject_Task simply cannot be used for non-FCDs.

The good news is eventually someone did point me in the right direction and I was able to figure it out and have some very simple prototype code now working. It turns out removing the backing file actually needs to be done with a ReconfigVM_Task with the VirtualDeviceConfigSpec fileOperation set to destroy. See https://pubs.vmware.com/vi3/sdk/ReferenceGuide/vim.vm.device.VirtualDeviceSpec.html

Here's a brief code snippit in the hope it helps someone else. If I get some time I'll do a proper example and submit a pull request.
```
#Assuming dev is already set to the vim.vm.device.VirtualDisk you want to delete...
virtual_hdd_spec = vim.vm.device.VirtualDeviceSpec()
virtual_hdd_spec.fileOperation = vim.vm.device.VirtualDeviceSpec.FileOperation.destroy
virtual_hdd_spec.operation = vim.vm.device.VirtualDeviceSpec.Operation.remove
virtual_hdd_spec.device = dev
spec = vim.vm.ConfigSpec()
spec.deviceChange = [virtual_hdd_spec]
WaitForTask(vm.ReconfigVM_Task(spec=spec))
```
