### ISSUE TITLE
Deploy_ovf from a http server(nginx), error: HTTPError: HTTPError: HTTP Error 416: Requested Range Not Satisfiable

### ISSUE THREAD

**Issue by shrekee** [vmware/pyvmomi-community-samples#617]
Hello @prziborowski
  I try to deploy OVF from a file server(nginx),  when go to progress ~99%-100%, an error occurs: HTTPError: HTTP Error 416: Requested Range Not Satisfiable.
  Really need your help.

ENV:
  python: 2.7.13
  pyvmomi: 6.7.1
  linux: SLES 12-SP3 
  vCenter server: 6.5.0.20000 (build)

Code: 
`class OvfHandler(object):
    """
    OvfHandler handles most of the OVA operations.
    It processes the tarfile, matches disk keys to files and
    uploads the disks, while keeping the progress up to date for the lease.
    """

    def __init__(self, ovf_file, vmdk_file):
        """
        Performs necessary initialization, opening the OVA file,
        processing the files and reading the embedded ovf file.
        """
        self.descriptor, self.handle = self._create_file_handle(ovf_file, vmdk_file)
        self.file_name = self.handle.file_name

    def _create_file_handle(self, ovf_file, vmdk_file):
        """
        A simple mechanism to pick whether the file is local or not.
        This is not very robust.
        """
        try:
            if os.path.exists(ovf_file) and os.path.exists(vmdk_file):
                return (FileHandle(ovf_file).read(), FileHandle(vmdk_file))
            else:
                return (WebHandle(ovf_file).read(), WebHandle(vmdk_file))
        except Exception as e:
            logger.error("#Error: create ovf_handler instance failed!")
            raise e

    def get_descriptor(self):
        # self.descriptor = self.handle.read()
        return self.descriptor

    def set_spec(self, spec):
        """
        The import spec is needed for later matching disks keys with
        file names.
        """
        self.spec = spec

    def get_disk(self, fileItem):
        """
        Does translation for disk key to file name, returning a file handle.
        """
        if self.file_name == fileItem.path:
            return self.handle
        else:
            raise Exception("#Error: get fileItem.path failed!!!")

    def get_device_url(self, fileItem, lease):
        for deviceUrl in lease.info.deviceUrl:
            if deviceUrl.importKey == fileItem.deviceId:
                return deviceUrl
        raise Exception("Failed to find deviceUrl for file %s" % fileItem.path)

    def upload_disks(self, lease, host):
        """
        Uploads all the disks, with a progress keep-alive.
        """
        self.lease = lease
        try:
            self.start_timer()
            n = 1
            for fileItem in self.spec.fileItem:
                logger.debug("======fileItem====={}=====".format(str(n)))
                n += 1
                self.upload_disk(fileItem, lease, host)
            lease.Complete()
            logger.info("Finished deploy successfully.")
            return 0
        except vmodl.MethodFault as e:
            logger.error("Hit an error in upload: {}".format(e))
            lease.Abort(e)
            raise
        except Exception as e:
            logger.error("Lease: %s".format(lease.info))
            logger.error("Hit an error in upload: {}".format(e))
            lease.Abort(vmodl.fault.SystemError(reason=str(e)))
            raise

    def upload_disk(self, fileItem, lease, host):
        """
        Upload an individual disk. Passes the file handle of the
        disk directly to the urlopen request.
        """
        # ovffile = self.get_disk(fileItem)
        # if ovffile is None:
        #     return
        deviceUrl = self.get_device_url(fileItem, lease)
        url = deviceUrl.url.replace('*', host)
        headers = {'Content-length': self.handle.st_size}
        if hasattr(ssl, '_create_unverified_context'):
            sslContext = ssl._create_unverified_context()
        else:
            sslContext = None
        req = Request(url, self.handle, headers)
        try:
            urlopen(req, context=sslContext)
        except HTTPError as e:
            msg = e.msg
            reason = e.reason
            if re.search('416', msg):
                logger.warning("{}".format(msg))
            elif re.search('416', reason):
                logger.warning("{}".format(reason))
            else:
                raise e

    def start_timer(self):
        """
        A simple way to keep updating progress while the disks are transferred.
        """
        Timer(5, self.timer).start()

    def timer(self):
        """
        Update the progress and reschedule the timer if not complete.
        """
        try:
            prog = self.handle.progress()
            self.lease.Progress(prog)
            if self.lease.state not in [vim.HttpNfcLease.State.done,
                                        vim.HttpNfcLease.State.error]:
                self.start_timer()
            # sys.stderr.write("Uploading progress: %d%%\r" % prog)
            logger.info("Uploading vm_disk_img, progress: %d%%\r" % prog)
        except Exception as e:  # Any exception means we should stop updating progress.
            logger.warning("Warning: timer has warning: {}".format(str(e)))
            raise e
`
========================================================================
`class WebHandle(object):
    def __init__(self, url):
        self.url = url
        self.file_name = os.path.basename(url)
        r = urlopen(url)
        self.rep = r
        if r.code != 200:
            raise FileNotFoundError(url)
        self.headers = self._headers_to_dict(r)
        r.close()
        if 'accept-ranges' not in self.headers:
            raise Exception("Site does not accept ranges")
        self.st_size = int(self.headers['content-length'])
        logger.info("Name: {}, size: {}".format(self.file_name, self.st_size))
        self.offset = 0

    def _headers_to_dict(self, r):
        result = {}
        if hasattr(r, 'getheaders'):
            for n, v in r.getheaders():
                result[n.lower()] = v.strip()
        else:
            for line in r.info().headers:
                if line.find(':') != -1:
                    n, v = line.split(': ', 1)
                    result[n.lower()] = v.strip()
        return result

    def tell(self):
        return self.offset

    def seek(self, offset, whence=0):
        if whence == 0:
            self.offset = offset
        elif whence == 1:
            self.offset += offset
        elif whence == 2:
            self.offset = self.st_size - offset
        return self.offset

    def seekable(self):
        return True

    def read(self, amount=None):
        start = self.offset
        if amount is None:
            end = self.st_size - 1
            self.offset = self.st_size -1
        else:
            end = self.offset + amount - 1
            self.offset += amount
        req = Request(self.url,
                      headers={'Range': 'bytes=%d-%d' % (start, end)})
        r = urlopen(req)
        result = r.read()
        r.close()
        return result

    # A slightly more accurate percentage
    def progress(self):
        return int(100.0 * self.offset / self.st_size)
`

Error stack:
`Exception occur >>>
Traceback (most recent call last):
  File "xxxx_vmware_vm_implemention_2.1.0_ovf.py", line 398, in main
    vCenter_ins.run()
  File "/code-repos/vmware/ovf/vc.py", line 130, in run
    self.deploy_vm_with_ovf()
  File "/code-repos/vmware/ovf/vc.py", line 905, in deploy_vm_with_ovf
    return ovf_handle.upload_disks(lease, self.vc_name)
  File "/code-repos/vmware/ovf/ovf.py", line 86, in upload_disks
    self.upload_disk(fileItem, lease, host)
  File "/code-repos/vmware/ovf/ovf.py", line 119, in upload_disk
    urlopen(req, context=sslContext)
  File "/usr/lib64/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib64/python2.7/urllib2.py", line 429, in open
    response = self._open(req, data)
  File "/usr/lib64/python2.7/urllib2.py", line 447, in _open
    '_open', req)
  File "/usr/lib64/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib64/python2.7/urllib2.py", line 1241, in https_open
    context=self._context)
  File "/usr/lib64/python2.7/urllib2.py", line 1195, in do_open
    h.request(req.get_method(), req.get_selector(), req.data, headers)
  File "/usr/lib64/python2.7/httplib.py", line 1042, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib64/python2.7/httplib.py", line 1082, in _send_request
    self.endheaders(body)
  File "/usr/lib64/python2.7/httplib.py", line 1038, in endheaders
    self._send_output(message_body)
  File "/usr/lib64/python2.7/httplib.py", line 886, in _send_output
    self.send(message_body)
  File "/usr/lib64/python2.7/httplib.py", line 856, in send
    datablock = data.read(blocksize)
  File "/code-repos/vmware/ovf/ovf.py", line 196, in read
    r = urlopen(req)
  File "/usr/lib64/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib64/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/usr/lib64/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib64/python2.7/urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "/usr/lib64/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib64/python2.7/urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 416: Requested Range Not Satisfiable`

**Comment by prziborowski** [comment]
My guess would be that in the last request for the range that leads to the end of the file, it actually requests more than the file and nginx gives an error rather than a partial read.

You may have to experiment with the read function to find something that works.
My only stab at it without being able to reproduce it would be:
```
def read(self, amount=None):
    start = self.offset
    if start >= self.st_size:
        return ""
    if amount is None:
        end = self.st_size - 1
        self.offset = self.st_size -1
    else:
        end = self.offset + amount - 1
        if end > self.st_size - 1:
            end = self.st_size - 1
        self.offset += amount
    req = Request(self.url,
                  headers={'Range': 'bytes=%d-%d' % (start, end)})
    r = urlopen(req)
    result = r.read()
    r.close()
    return result
```

**Comment by shrekee** [comment]
@prziborowski  It works! Thank you very muth. I changed my read() fucntion, then work expected.
