### ISSUE TITLE
How can I make a snapshot creation of a virtual machine in task scheduler?

### ISSUE THREAD

**Issue by MrNegatiff** [vmware/pyvmomi-community-samples#618]
Hi ! Please help me in this matter.

used:
python version 3.6
vSphere 6.0
pyvmomi    6.7.0.2018.9

many thanks

**Comment by prziborowski** [comment]
I have never tried this with snapshot creation before, but let me see if I can wing it and then I'll try it once I have a test environment up.

Inputs needed: si = ServiceInstance, vm = VirtualMachine
```
from pyVmomi import vim
from datetime import timedelta
...
action = vim.action.MethodAction(name=vim.VirtualMachine.CreateSnapshot)
action.argument = [
   vim.action.MethodActionArgument(value="snapshot name"),
   vim.action.MethodActionArgument(value="snapshot description"),
   vim.action.MethodActionArgument(value=True), # snapshot memory
   vim.action.MethodActionArgument(value=False), # quiesce
]
runAt = si.CurrentTime() + timedelta(seconds=30) # as an example, schedule the job 30 seconds from now.
scheduler = vim.scheduler.OnceTaskScheduler(runAt=runAt)
taskSpec = vim.scheduler.ScheduledTaskSpec(name="CreateSnapshot-%s" % vm.name,
                                           description="",
                                           action=action,
                                           scheduler=scheduler,
                                           enabled=True)
stm = si.content.scheduledTaskManager
scheduledTask = stm.Create(vm, spec=taskSpec)
```
And with the [scheduledTask](https://code.vmware.com/apis/358/vsphere/doc/vim.scheduler.ScheduledTask.html) you could run it immediately, reconfigure it to do something else, etc.

**Comment by MrNegatiff** [comment]
Thanks a lot! It really works.  02.12.2019, 21:45, "prziborowski" <notifications@github.com>:I have never tried this with snapshot creation before, but let me see if I can wing it and then I'll try it once I have a test environment up.Inputs needed: si = ServiceInstance, vm = VirtualMachinefrom pyVmomi import vim
from datetime import timedelta
...
action = vim.action.MethodAction(name=vim.VirtualMachine.CreateSnapshot)
action.argument = [
   vim.action.MethodActionArgument(value="snapshot name"),
   vim.action.MethodActionArgument(value="snapshot description"),
   vim.action.MethodActionArgument(value=True), # snapshot memory
   vim.action.MethodActionArgument(value=False), # quiesce
]
runAt = si.CurrentTime() + timedelta(seconds=30) # as an example, schedule the job 30 seconds from now.
scheduler = vim.scheduler.OnceTaskScheduler(runAt=runAt)
taskSpec = vim.scheduler.ScheduledTaskSpec(name="CreateSnapshot-%s" % vm.name,
                                           description="",
                                           action=action,
                                           scheduler=scheduler,
                                           enabled=True)
stm = si.content.scheduledTaskManager
scheduledTask = stm.Create(vm, spec=taskSpec)
And with the scheduledTask you could run it immediately, reconfigure it to do something else, etc.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
