### ISSUE TITLE
Add Custom LinuxPrep

### ISSUE THREAD

**Issue by r4rajat** [vmware/pyvmomi-community-samples#620]
I have Made a custom LinuxPrep

adaptermap.adapter = vim.vm.customization.IPSettings \
                    (ip=vim.vm.customization.DhcpIpGenerator(), dnsDomain='domain.local')
globalip = vim.vm.customization.GlobalIPSettings()
ident = vim.vm.customization.LinuxPrep(domain='domain.local',
                                                       hostName=vim.vm.customization.FixedName(
                                                           name=hostname))
customspec = vim.vm.customization.Specification(nicSettingMap=[adaptermap],
                                                                globalIPSettings=globalip,
                                                                identity=ident)
clone_spec = vim.vm.CloneSpec(powerOn=True, template=False,
                                              config=vmconf, location=relocate_spec,
                                              customization=customspec)

But while cloning it from template it is giving error of spec.identity.hostName is not correct, actually what I want to do is to change the host name while creation of VM from template

**Comment by prziborowski** [comment]
I'm not 100% sure I understand the question. I assume this clone you are doing is from a template and you are giving it the above customization spec.
The part is doesn't like is: hostName=vim.vm.customization.FixedName(name=hostname),
but without knowing what you are setting for `hostname` I don't know why it is complaining.

But I'll tell you the restrictions and you can decide the name you picked is valid or not.
It must be less than 64 ascii characters, can contain upper and lowercase letters, numbers and hyphens. It can't contain other characters (such as spaces or periods). It also can't begin or end with a hyphen.

**Comment by r4rajat** [comment]
got it Thanks !!
