### ISSUE TITLE
How to deploy OVA, if there is no resource pool

### ISSUE THREAD

**Issue by rajeshpp** [vmware/pyvmomi-community-samples#654]
https://github.com/vmware/pyvmomi-community-samples/blob/bc14f63065aa360ceca0cca477a8b271d582a090/samples/deploy_ova.py#L158

In my case, I don't have any resource pool. how can I deploy OVA in that case?

Also, I have some other cases, where I don't have a proper data store. How can I deploy OVA by using only host, username, password, cluster, folder?

**Comment by rajeshpp** [comment]
Hi Team,

Any help with priority is appreciated.

**Comment by joelelmercarlson** [comment]
Interested in what a default resourcepool might look like which might be possible to use as workaround.

**Comment by rajeshpp** [comment]
Adding executed part here:

```
+ sudo python3 deploy_OVA.py -s HOST.COM -u **** -p **** --ova-path ./ots-rhel-server-7.7_v74.ova -d DATACENTER -ds DATASTORE -n v8-rhel-7.7_beta_1 -m 'v000 - Dist. Test' -f _Templates
Traceback (most recent call last):
  File "deploy_OVA.py", line 517, in <module>
    exit(main())
  File "deploy_OVA.py", line 81, in main
    rp = get_largest_free_rp(si, dc)
  File "deploy_OVA.py", line 204, in get_largest_free_rp
    raise Exception("Failed to find a resource pool in dc %s" % dc.name)
Exception: Failed to find a resource pool in dc DATACENTER
```

**Comment by sathvikm** [comment]
A quick solution would be to Provide the resource pool using the -r option. so that script won't look for the largest RP.

**Comment by rajeshpp** [comment]
> A quick solution would be to Provide the resource pool using the -r option. so that script won't look for the largest RP.

That's when we have a resource pool in the vCenter. How to deploy, if there is no resource pool at all?

**Comment by benafischer94** [comment]
I've had success using the --resource-pool flag and passing it "Resources"
`pyvmomi-community-samples/samples/deploy_ova.py -s vcsa.contoso.com -u "administrator@lab.contoso.com" -p "abadpassword" -nossl --ova-path 20.04-cloud.ova --datacenter-name Lab --resource-pool Resources --datastore-name 512SSD`
