### ISSUE TITLE
pyvmomi add host usb to VM

### ISSUE THREAD

**Issue by menvol3** [vmware/pyvmomi-community-samples#659]
I’m looking for possibility passthrough Host USB devices  to VM via pyvmomi.

I’m new with python, and asking for help with it.

I have ESXI host with 1 VM running. Also each ESXI host have some USB devices connected to it, and i need to passthrough all available USB devices to existing VM on this host.

Also it will be good to pass an argument the ip address of the ESXI host where passthrough will be proceeded.

For now i have a script which prints name of first available for passthrough USB device on host.

https://gist.github.com/menvol3/b5e60343f021c2048c7b0536ddfc4f90

**Comment by janpelikan** [comment]
Hi @menvol3 I solving something similar like you. Do you have the script? Could you re-upload them please?
Thank you kindly.

**Comment by menvol3** [comment]
Hello,

https://gist.github.com/menvol3/07df3bf5ea75fc9cfffa8e0c3d0dbf53

**Comment by janpelikan** [comment]
Wonderful. That really helped. Thank you very much.
