### ISSUE TITLE
add_nic_to_vm.py doesn't work for VDS case

### ISSUE THREAD

**Issue by ckjhljcy** [vmware/pyvmomi-community-samples#666]
The add_nic_to_vm.py assumes the network passed in must be of the type of opaque network. If it is not, then it will use the backing which is used by port group of standard switch. If user pass a VDS DVPG, the wrong backing is set.

**Comment by prziborowski** [comment]
Perhaps you can refer to this sample: https://github.com/vmware/pyvmomi-community-samples/blob/master/samples/add_vm_nic_to_dvs.py for vDS.
