### ISSUE TITLE
password=args.vm_password

### ISSUE THREAD

**Issue by rapgro** [vmware/pyvmomi-community-samples#668]
According to command line option named --vm-password as see in tools/cli.py line 167, there's **args.vm_password** to be used. 
Tested on RHEL8 with Python 3.6.8 .

https://github.com/vmware/pyvmomi-community-samples/blob/889a2fadcb24e6b1bc1e30caab66f1a41a950988/samples/upload_file_to_vm.py#L57

https://github.com/vmware/pyvmomi-community-samples/blob/889a2fadcb24e6b1bc1e30caab66f1a41a950988/samples/tools/cli.py#L167

**Comment by DanielDraganov** [comment]
Fixed in https://github.com/vmware/pyvmomi-community-samples/pull/709
