### ISSUE TITLE
Help! OVA export function

### ISSUE THREAD

**Issue by srg1177** [vmware/pyvmomi-community-samples#705]
### Is your feature request related to a problem? Please describe.

Need a script for OVA export, currently can find a only for OVF.

### Describe the solution you'd like

Functionally to be able to export an OVA from Vsphere.

**Comment by pgbidkar** [comment]
Hi @srg1177 , Please can you check this https://github.com/vmware/pyvmomi-community-samples/blob/master/samples/deploy_ova.py ? Does this fit your requirement?

**Comment by prziborowski** [comment]
Hi @srg1177, I noticed your message in #532. OVA is just a packaging of the ovf file along with signature and other files (e.g. disks).
You could do it inside python itself (leveraging tarfile), or just calling some other binary (e.g. tar).

https://stackoverflow.com/questions/21118311/ordering-files-inside-tar-created-from-bash has some details on that.
For proper streaming support, it should be ordered (ovf, mf, followed by the order the files are in the ovf file).

As for exporting the VM, there is an export_vm.py sample.
