### ISSUE TITLE
args.vm_pwd should be args.vm_password

### ISSUE THREAD

**Issue by we-shall** [vmware/pyvmomi-community-samples#715]
### Describe the bug

The command execute_program_in_vm.py fails with 
```
Traceback (most recent call last):
  File "commands/execute_program_in_vm.py", line 119, in <module>
    main()
  File "commands/execute_program_in_vm.py", line 70, in main
    username=args.vm_user, password=args.vm_pwd
AttributeError: 'Namespace' object has no attribute 'vm_pwd'
make: *** [Makefile:164: mkdir-artifacts] Error 1
```

### Reproduction steps

1. Just the run the command 
2.
3.
...

### Expected behavior

Instead of using the args.vm_pwd use args.vm_password and the program will work fine

**Comment by DanielDraganov** [comment]
Fixed in https://github.com/vmware/pyvmomi-community-samples/pull/709
